@extends('layouts.auth')
@section('title','Complete Seller Registration')
@section('auth-card')
<div class="w-full max-w-3xl"><div class="card p-6 sm:p-8"><h1 class="text-2xl font-bold text-navy-900">Complete your Seller registration</h1><p class="mt-1 text-sm text-slate-500">Google provided your account details. Add the required address and store information for review.</p><div class="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><b>{{ auth()->user()->name }}</b><p class="text-slate-500">{{ auth()->user()->email }}</p></div>
<form method="POST" action="{{ route('profile.complete.seller.update') }}" enctype="multipart/form-data" class="mt-6 space-y-6">@csrf
<section><h2 class="text-sm font-bold uppercase text-brand-600">Personal Address</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Mobile Number *</label><input class="input" name="phone" value="{{ old('phone',auth()->user()->phone) }}" required></div><div class="sm:col-span-2"><label class="label">Address Line *</label><input class="input" name="address_line" value="{{ old('address_line',$address?->address_line) }}" required></div>@foreach(['barangay'=>'Barangay','city'=>'City / Municipality','province'=>'Province','postal_code'=>'Postal Code'] as $field=>$label)<div><label class="label">{{ $label }} *</label><input class="input" name="{{ $field }}" value="{{ old($field,$address?->{$field}) }}" required></div>@endforeach<input type="hidden" name="country" value="{{ old('country',$address?->country??'PH') }}"></div></section>
<section x-data="{same:true}"><h2 class="text-sm font-bold uppercase text-brand-600">Store Information</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><div><label class="label">Store Name *</label><input class="input" name="store_name" value="{{ old('store_name') }}" required></div><div class="sm:col-span-2"><label class="label">Store Description *</label><textarea class="input" name="store_description" required>{{ old('store_description') }}</textarea></div><label class="sm:col-span-2 flex gap-2 text-sm"><input type="checkbox" name="same_address" value="1" x-model="same"> Use my personal address as my store address</label><div x-show="!same" class="grid gap-4 sm:col-span-2 sm:grid-cols-2"><input class="input sm:col-span-2" name="store_address_line" placeholder="Store address line">@foreach(['store_barangay'=>'Barangay','store_city'=>'City','store_province'=>'Province','store_postal_code'=>'Postal code'] as $field=>$label)<input class="input" name="{{ $field }}" placeholder="{{ $label }}">@endforeach</div><div><label class="label">Store Logo</label><input class="input" type="file" name="logo" accept="image/jpeg,image/png,image/webp"></div><div><label class="label">Store Banner</label><input class="input" type="file" name="banner" accept="image/jpeg,image/png,image/webp"></div><div class="sm:col-span-2"><label class="label">Business Information (optional)</label><textarea class="input" name="business_information">{{ old('business_information') }}</textarea></div></div></section>
<label class="flex items-start gap-2 text-sm"><input type="checkbox" name="seller_terms" value="1" required class="mt-1">I agree to the Terms, Privacy Policy, and Seller Policy.</label><button class="btn-primary w-full">Submit Seller Registration</button></form></div></div>
@endsection
