@extends('layouts.auth')
@section('title','Complete Seller Registration')
@section('auth-card')
<div class="w-full max-w-3xl"><div class="card p-6 sm:p-8"><h1 class="text-2xl font-bold text-navy-900">Complete your Seller registration</h1><p class="mt-1 text-sm text-slate-500">Google supplied your email. Complete all required identity and business details for Admin review.</p>
<form method="POST" action="{{ route('profile.complete.seller.update') }}" enctype="multipart/form-data" class="mt-6 space-y-6">@csrf
<section><h2 class="text-sm font-bold uppercase text-brand-600">Personal Information</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><input class="input" name="first_name" value="{{ old('first_name',auth()->user()->first_name) }}" placeholder="First Name" required><input class="input" name="middle_initial" value="{{ old('middle_initial',auth()->user()->middle_initial) }}" maxlength="5" placeholder="Middle Initial"><input class="input" name="last_name" value="{{ old('last_name',auth()->user()->last_name) }}" placeholder="Last Name" required><select class="input" name="sex" required><option value="">Sex</option><option value="female" @selected(old('sex',auth()->user()->sex)==='female')>Female</option><option value="male" @selected(old('sex',auth()->user()->sex)==='male')>Male</option></select><x-birthday-age-fields :birthday="old('birthday',auth()->user()->birthday?->toDateString())" /><input class="input" type="file" name="valid_id" accept="image/jpeg,image/png,application/pdf" required></div></section>
<section><h2 class="text-sm font-bold uppercase text-brand-600">Address</h2><div class="mt-3 space-y-4"><div class="grid gap-4 sm:grid-cols-2"><input class="input" name="phone" placeholder="Contact Number" required><input class="input" name="address_line" placeholder="Street / House Number" required></div><x-philippine-location-fields :region="old('region')" :region-code="old('region_code')" :province="old('province')" :province-code="old('province_code')" :city="old('city')" :city-code="old('city_code')" :barangay="old('barangay')" :barangay-code="old('barangay_code')" /><input class="input" name="postal_code" value="{{ old('postal_code') }}" placeholder="Postal Code" required><input type="hidden" name="country" value="PH"></div></section>
<section x-data="{same:true}"><h2 class="text-sm font-bold uppercase text-brand-600">Business Information</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><input class="input" name="store_name" placeholder="Business / Store Name" required><select class="input" name="category_id" required><option value="">Line of Business</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><textarea class="input sm:col-span-2" name="store_description" placeholder="Store Description" required></textarea><label class="sm:col-span-2 flex gap-2 text-sm"><input type="checkbox" name="same_address" value="1" x-model="same"> Use personal address as business address</label><div x-show="!same" class="space-y-4 sm:col-span-2"><input class="input" name="store_address_line" placeholder="Business street address"><x-philippine-location-fields prefix="store_" :required="false" /><input class="input" name="store_postal_code" placeholder="Postal Code"></div><textarea class="input sm:col-span-2" name="business_information" placeholder="Additional business information"></textarea><div><label class="label">Business Permit *</label><input class="input" type="file" name="business_permit" accept="image/jpeg,image/png,application/pdf" required></div><div><label class="label">Store Logo</label><input class="input" type="file" name="logo" accept="image/jpeg,image/png,image/webp"></div></div></section>
<label class="flex gap-2 text-sm"><input type="checkbox" name="seller_terms" value="1" required> I agree to the Seller Policy.</label><button class="btn-primary w-full">Submit for Admin Approval</button></form></div></div>
@endsection
