@extends('layouts.auth')
@section('title','Register as Seller')
@section('auth-card')
<div class="w-full max-w-3xl"><div class="card p-6 sm:p-8"><h1 class="text-2xl font-bold text-navy-900">Start selling on SHOPPICK</h1><p class="mt-1 text-sm text-slate-500">Create your account and submit your store for review.</p>
<a href="{{ route('auth.google.redirect',['account_type'=>'seller']) }}" class="btn-outline mt-6 flex w-full items-center justify-center gap-3"><b class="text-brand-600">G</b>Continue with Google as Seller</a><div class="my-5 flex items-center gap-3 text-xs uppercase text-slate-400"><span class="h-px flex-1 bg-slate-200"></span>Or<span class="h-px flex-1 bg-slate-200"></span></div>
<form method="POST" action="{{ route('register.seller.submit') }}" enctype="multipart/form-data" class="space-y-6">@csrf
<section><h2 class="text-sm font-bold uppercase tracking-wide text-brand-600">1. Account Information</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Full Name *</label><input class="input" name="name" value="{{ old('name') }}" required>@error('name')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="label">Email Address *</label><input class="input" type="email" name="email" value="{{ old('email') }}" required>@error('email')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="label">Mobile Number *</label><input class="input" name="phone" value="{{ old('phone') }}" placeholder="09171234567" required>@error('phone')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="label">Password *</label><input class="input" type="password" name="password" required></div><div><label class="label">Confirm Password *</label><input class="input" type="password" name="password_confirmation" required></div></div></section>
<section><h2 class="text-sm font-bold uppercase tracking-wide text-brand-600">2. Seller Address</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Address Line *</label><input class="input" name="address_line" value="{{ old('address_line') }}" required></div>@foreach(['barangay'=>'Barangay','city'=>'City / Municipality','province'=>'Province','postal_code'=>'Postal Code'] as $field=>$label)<div><label class="label">{{ $label }} *</label><input class="input" name="{{ $field }}" value="{{ old($field) }}" required></div>@endforeach<input type="hidden" name="country" value="PH"></div></section>
<section x-data="{same:{{ old('same_address',1)?'true':'false' }}}"><h2 class="text-sm font-bold uppercase tracking-wide text-brand-600">3. Store Information</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><div><label class="label">Store Name *</label><input class="input" name="store_name" value="{{ old('store_name') }}" required>@error('store_name')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label class="label">Store Description *</label><textarea class="input" name="store_description" required>{{ old('store_description') }}</textarea></div><label class="sm:col-span-2 flex items-center gap-2 text-sm"><input type="checkbox" name="same_address" value="1" x-model="same"> Use my personal address as my store address</label><div x-show="!same" class="grid gap-4 sm:col-span-2 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Store Address Line</label><input class="input" name="store_address_line" value="{{ old('store_address_line') }}"></div>@foreach(['store_barangay'=>'Barangay','store_city'=>'City','store_province'=>'Province','store_postal_code'=>'Postal Code'] as $field=>$label)<div><label class="label">{{ $label }}</label><input class="input" name="{{ $field }}" value="{{ old($field) }}"></div>@endforeach</div><div><label class="label">Store Logo</label><input class="input" type="file" name="logo" accept="image/jpeg,image/png,image/webp"></div><div><label class="label">Store Banner (optional)</label><input class="input" type="file" name="banner" accept="image/jpeg,image/png,image/webp"></div></div></section>
<section><h2 class="text-sm font-bold uppercase tracking-wide text-brand-600">4. Seller Information</h2><div class="mt-3"><label class="label">Business Information (optional)</label><textarea class="input" name="business_information">{{ old('business_information') }}</textarea></div><label class="mt-4 flex items-start gap-2 text-sm text-slate-600"><input type="checkbox" name="seller_terms" value="1" required class="mt-1">I agree to the Terms, Privacy Policy, and Seller Policy.</label>@error('seller_terms')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</section>
<button class="btn-primary w-full">Submit Seller Registration</button></form></div><p class="mt-4 text-center text-sm"><a href="{{ route('register') }}" class="font-semibold text-slate-500">← Choose account type</a></p></div>
@endsection
