@extends('layouts.auth') @section('title','Apply as Rider') @section('auth-card')
<div class="w-full max-w-3xl"><div class="card p-6 sm:p-8"><h1 class="text-2xl font-bold text-navy-900">Apply as a SHOPPICK Rider</h1><p class="mt-1 text-sm text-slate-500">Submit your information for SHOPPICK Logistics review. This does not immediately activate a Rider account.</p>
@if($errors->any())<div class="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><b>Please review the highlighted information.</b><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ route('register.rider.submit') }}" class="mt-6 space-y-5">@csrf
<section><h2 class="text-xs font-bold uppercase tracking-wider text-brand-700">Personal Information</h2><div class="mt-3 grid gap-4 sm:grid-cols-3"><label class="label">First Name *<input class="input mt-1" name="first_name" value="{{ old('first_name') }}" required></label><label class="label">Middle Initial<input class="input mt-1" name="middle_initial" maxlength="5" value="{{ old('middle_initial') }}"></label><label class="label">Last Name *<input class="input mt-1" name="last_name" value="{{ old('last_name') }}" required></label><label class="label">Sex *<select class="input mt-1" name="sex" required><option value="">Select</option><option value="female" @selected(old('sex')==='female')>Female</option><option value="male" @selected(old('sex')==='male')>Male</option></select></label><x-birthday-age-fields :birthday="old('birthday')" /></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="label">Email *<input class="input mt-1" type="email" name="email" value="{{ old('email') }}" required></label><label class="label">Mobile Number *<input class="input mt-1" name="phone" value="{{ old('phone') }}" required></label></div></section>
<section><h2 class="text-xs font-bold uppercase tracking-wider text-brand-700">Address</h2><label class="label mt-3 block">House No. / Street *<input class="input mt-1" name="address_line" value="{{ old('address_line') }}" required></label><div class="mt-4"><x-philippine-location-fields :region="old('region')" :region-code="old('region_code')" :province="old('province')" :province-code="old('province_code')" :city="old('city')" :city-code="old('city_code')" :barangay="old('barangay')" :barangay-code="old('barangay_code')" /></div><label class="label mt-4 block">Postal Code<input class="input mt-1" name="postal_code" value="{{ old('postal_code') }}"></label></section>
<section><h2 class="text-xs font-bold uppercase tracking-wider text-brand-700">Rider Documents</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><label class="label">Valid ID *<input class="input mt-1" type="file" name="valid_id" accept=".pdf,.jpg,.jpeg,.png" capture="environment" required><small class="block font-normal text-slate-500">Private JPG, PNG, or PDF.</small></label><label class="label">Driver's License Number *<input class="input mt-1" name="driver_license_number" value="{{ old('driver_license_number') }}" maxlength="80" required></label><label class="label">License Classification / Type *<input class="input mt-1" name="driver_license_classification" value="{{ old('driver_license_classification') }}" maxlength="100" required></label><label class="label">License Expiration Date *<input class="input mt-1" type="date" name="driver_license_expires_at" value="{{ old('driver_license_expires_at') }}" required></label><label class="label">License Front *<input class="input mt-1" type="file" name="driver_license_front" accept=".pdf,.jpg,.jpeg,.png" capture="environment" required><small class="block font-normal text-slate-500">Take a photo or upload a file.</small></label><label class="label">License Back *<input class="input mt-1" type="file" name="driver_license_back" accept=".pdf,.jpg,.jpeg,.png" capture="environment" required></label></div></section>
<section><h2 class="text-xs font-bold uppercase tracking-wider text-brand-700">Optional Operations Information</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><label class="label">Emergency Contact<input class="input mt-1" name="emergency_contact_name" value="{{ old('emergency_contact_name') }}"></label><label class="label">Emergency Contact Phone<input class="input mt-1" name="emergency_contact_phone" value="{{ old('emergency_contact_phone') }}"></label><label class="label">Preferred Vehicle Type<select class="input mt-1" name="preferred_vehicle_type"><option value="">No preference</option>@foreach(['motorcycle'=>'Motorcycle','scooter'=>'Scooter','car'=>'Car','van'=>'Van'] as $value=>$label)<option value="{{ $value }}" @selected(old('preferred_vehicle_type')===$value)>{{ $label }}</option>@endforeach</select><small class="block font-normal text-slate-500">Logistics assigns official vehicles after approval.</small></label></div></section>
<section><h2 class="text-xs font-bold uppercase tracking-wider text-brand-700">Account Security</h2><div class="mt-3 grid gap-4 sm:grid-cols-2"><label class="label">Password *<input class="input mt-1" type="password" name="password" required></label><label class="label">Confirm Password *<input class="input mt-1" type="password" name="password_confirmation" required></label></div></section>
<label class="flex items-start gap-2 text-sm text-slate-600"><input class="mt-1 h-4 w-4" type="checkbox" name="terms" value="1" required>I agree to the Terms and Privacy Policy.</label><button class="btn-primary min-h-11 w-full">Submit Rider Application</button></form></div><p class="mt-4 text-center text-sm"><a href="{{ route('register') }}" class="font-semibold text-brand-600">← Choose account type</a></p></div>
@endsection
