<style>
.rider-details{color:#334155;font-size:13px}.rider-details [hidden]{display:none!important}
.rider-details .rd-card{background:white;border:1px solid #e2e8f0;border-radius:16px;padding:20px;box-shadow:0 2px 5px #15233f05;min-width:0}
.rider-details .rider-header{display:flex;align-items:center;gap:16px;margin:16px 0 20px;flex-wrap:wrap}
.rider-details h1{font-size:27px;font-weight:800;letter-spacing:-.025em;color:#15233f;line-height:1.2}.rider-details h2{font-size:16px;font-weight:700;color:#15233f}
.rider-details .rd-avatar{display:flex;align-items:center;justify-content:center;width:56px;height:56px;border-radius:16px;background:#f0fdfa;color:#0f766e;font-size:22px;font-weight:800;flex-shrink:0;overflow:hidden}.rider-details .rd-avatar img{width:100%;height:100%;object-fit:cover}
.rider-details .rd-eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:#64748b;font-weight:700;margin-bottom:5px}.rider-details .rd-muted{font-size:12px;color:#64748b;line-height:1.6}.rider-details .rd-email{overflow-wrap:anywhere;margin-top:5px}
.rider-details .rd-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.rider-details .rd-metric{padding:18px}.rider-details .rd-metric-heading{display:flex;align-items:center;gap:9px;margin-bottom:15px}.rider-details .rd-metric-heading h2{font-size:10px;margin:0;color:#64748b}.rider-details .rd-value{font-size:27px;color:#15233f;font-weight:800;margin-bottom:5px;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}
.rider-details .rd-icon{display:flex;align-items:center;justify-content:center;width:32px;height:32px;border-radius:10px;background:#f0fdfa;color:#0f766e;flex-shrink:0}.rider-details .rd-metric:nth-child(2) .rd-icon{color:#c2410c;background:#fff7ed}
.rider-details .rd-columns{display:grid;grid-template-columns:1.15fr 1fr;gap:20px;margin-top:20px}.rider-details .rd-current{border-top:3px solid #14b8a6;padding-top:18px}.rider-details .rd-section{margin-top:24px}.rider-details .rd-section-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:16px}
.rider-details .rd-info{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.rider-details dt{font-size:11px;color:#64748b;margin-bottom:4px}.rider-details dd{font-size:13px;color:#15233f;font-weight:600;overflow-wrap:anywhere}.rider-details .rd-tracking{font-size:21px;font-weight:800;color:#15233f;overflow-wrap:anywhere}
.rider-details .rd-badge{display:inline-flex;padding:4px 8px;border-radius:7px;font-size:11px;font-weight:600;white-space:nowrap}.rider-details .rd-teal{color:#047857;background:#ecfdf5}.rider-details .rd-blue{color:#1d4ed8;background:#eff6ff}.rider-details .rd-orange{color:#c2410c;background:#fff7ed}.rider-details .rd-red{color:#be123c;background:#fff1f2}.rider-details .rd-gray{color:#475569;background:#f1f5f9}
.rider-details .rd-action{display:inline-flex;align-items:center;gap:6px;border:1px solid #ccfbf1;border-radius:9px;padding:7px 10px;background:#f0fdfa;color:#0f766e;font-size:12px;font-weight:600;white-space:nowrap}.rider-details .rd-action:hover{background:#ccfbf1}.rider-details a:focus-visible,.rider-details button:focus-visible{outline:3px solid #14b8a6;outline-offset:3px}
.rider-details .rd-filters{display:flex;gap:14px;align-items:flex-end;flex-wrap:wrap;background:#f8fafc;border:1px solid #f1f5f9;padding:14px;border-radius:12px;margin-bottom:16px}.rider-details .rd-filters label{font-size:11px;font-weight:600;color:#475569;min-width:180px}.rider-details .rd-filters .input{margin-top:6px;height:40px;font-size:13px;width:100%;font-weight:400}
.rider-details .rd-table-wrap{overflow-x:auto;border:1px solid #e2e8f0;border-radius:12px}.rider-details .rd-table{width:100%;text-align:left;border-collapse:collapse;font-size:12px}.rider-details .rd-table th{background:#f1f7f7;color:#526577;padding:12px;font-size:10px;text-transform:uppercase;letter-spacing:.04em;white-space:nowrap}.rider-details .rd-table td{padding:13px 12px;border-top:1px solid #f1f5f9;vertical-align:middle}.rider-details .rd-table tr:hover td{background:#f8fdfc}
.rider-details .rd-pagination{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-top:16px}.rider-details .rd-pagination nav{display:flex;align-items:center;gap:12px}.rider-details .rd-pagination a{font-size:12px;font-weight:600;padding:7px 10px;border:1px solid #e2e8f0;border-radius:8px;color:#0f766e}.rider-details .rd-pagination a:hover{background:#f0fdfa}
.rider-details .rd-empty{padding:20px 12px;background:#f8fafc;border-radius:10px;color:#475569;text-align:center}.rider-details .rd-timeline{margin:0 0 0 8px;padding:0;list-style:none}.rider-details .rd-event{position:relative;border-left:2px solid #e2e8f0;padding:0 0 20px 22px;overflow-wrap:anywhere}.rider-details .rd-event:last-child{padding-bottom:0;border-color:transparent}.rider-details .rd-dot{position:absolute;left:-6px;top:7px;width:10px;height:10px;border:2px solid white;border-radius:50%;background:#14b8a6;box-shadow:0 0 0 2px #ccfbf1}.rider-details .rd-event-heading{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.rider-details .rd-event-tracking{display:inline-block;font-size:12px;font-weight:600;color:#0f766e;margin-top:6px}.rider-details .rd-event-note{font-size:13px;margin-top:4px;line-height:1.6}.rider-details .rd-feedback{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-size:12px;color:#0f766e}.rider-details .rd-feedback:not(:empty){margin-bottom:10px}.rider-details [data-rider-error]{color:#be123c}
@media(max-width:1200px){.rider-details .rd-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:640px){.rider-details .rd-metrics,.rider-details .rd-columns{grid-template-columns:1fr}.rider-details .rd-card{padding:16px}.rider-details h1{font-size:23px}.rider-details .rd-filters label{width:100%;min-width:0}.rider-details .rd-info{grid-template-columns:1fr}.rider-details .rd-pagination nav{gap:8px;flex-wrap:wrap}}
.rider-details .rd-dot[data-event-status="exception"],.rider-details .rd-dot[data-event-status="delivery_failed"]{background:#f97316;box-shadow:0 0 0 2px #ffedd5}.rider-details .rd-dot[data-event-status="returned"]{background:#e11d48;box-shadow:0 0 0 2px #ffe4e6}.rider-details .rd-dot[data-event-status="in_transit"],.rider-details .rd-dot[data-event-status="out_for_delivery"]{background:#3b82f6;box-shadow:0 0 0 2px #dbeafe}
</style>
