@extends('layouts.admin')
@section('title','Registration Applications')
@section('content')
<div><h1 class="text-2xl font-extrabold text-navy-900">Registration Applications</h1><p class="mt-1 text-sm text-slate-500">Review new Buyer identities and Seller business applications.</p></div>
<div class="mt-5 flex flex-wrap gap-2">@foreach(['all'=>'All Applications','buyers'=>'Buyers','sellers'=>'Sellers'] as $value=>$label)<a href="{{ route('admin.sellers.applications.index',['tab'=>$value]+request()->only(['q','status'])) }}" class="rounded-xl px-4 py-2 text-sm font-semibold {{ $tab===$value?'bg-brand-600 text-white':'border bg-white text-slate-600' }}">{{ $label }} <span class="ml-1 opacity-75">{{ $value==='buyers'?$buyers->count():($value==='sellers'?$sellers->count():$buyers->count()+$sellers->count()) }}</span></a>@endforeach</div>
<form class="card mt-4 flex flex-wrap gap-3 p-4"><input type="hidden" name="tab" value="{{ $tab }}"><input class="input min-w-52 flex-1" name="q" value="{{ request('q') }}" placeholder="Search applicant, email, or business"><select class="input max-w-xs" name="status"><option value="">All statuses</option>@foreach(['pending','approved','rejected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn-outline">Filter</button></form>

@if(in_array($tab,['all','buyers']))<section class="mt-6"><div class="mb-3"><h2 class="font-bold text-navy-900">Buyer Applications</h2><p class="text-xs text-slate-500">Identity, contact, address, and valid-ID review.</p></div><div class="space-y-4">@forelse($buyers as $buyer)@php($address=$buyer->defaultAddress())<article class="card p-5"><div class="flex flex-wrap justify-between gap-3"><div><h3 class="font-bold">{{ $buyer->name }}</h3><p class="text-sm text-slate-500">{{ $buyer->email }} · {{ $buyer->phone }}</p><p class="mt-1 text-xs text-slate-500">{{ ucfirst($buyer->sex) }} · {{ $buyer->birthday?->format('M d, Y') }} · Age {{ $buyer->age }}</p><p class="mt-1 text-xs text-slate-500">{{ collect([$address?->barangay,$address?->city,$address?->province])->filter()->join(', ') }}</p></div><div class="text-right"><x-admin.status-badge :status="$buyer->registration_status"/><p class="mt-2 text-xs text-slate-400">Submitted {{ $buyer->created_at->format('M d, Y') }}</p></div></div><div class="mt-4 flex flex-wrap items-center gap-3"><a class="btn-outline btn-sm" href="{{ route('admin.registrations.buyers.document',$buyer) }}">View Valid ID</a>@if($buyer->registration_status==='pending')<form method="POST" action="{{ route('admin.registrations.buyers.review',$buyer) }}" class="flex flex-1 flex-wrap gap-2">@csrf<input name="review_notes" class="input min-w-52 flex-1" placeholder="Reason required when rejecting"><button name="status" value="approved" class="btn-primary">Approve</button><button name="status" value="rejected" class="btn-outline text-rose-600">Reject</button></form>@elseif($buyer->registration_review_notes)<p class="text-sm text-slate-500">Review note: {{ $buyer->registration_review_notes }}</p>@endif</div></article>@empty<div class="card p-10 text-center text-slate-500">No Buyer applications match these filters.</div>@endforelse</div></section>@endif

@if(in_array($tab,['all','sellers']))<section class="mt-7"><div class="mb-3"><h2 class="font-bold text-navy-900">Seller Applications</h2><p class="text-xs text-slate-500">One Admin decision activates both the Seller account and Shop.</p></div><div class="space-y-4">@forelse($sellers as $application)<article class="card p-5"><div class="flex flex-wrap justify-between gap-3"><div><h3 class="font-bold">{{ $application->store_name }}</h3><p class="text-sm text-slate-500">{{ $application->user->name }} · {{ $application->user->email }} · {{ $application->phone }}</p><p class="mt-1 text-xs text-slate-500">Line of Business: <b>{{ $application->category?->name ?? 'Not recorded' }}</b></p><p class="mt-1 text-xs text-slate-500">{{ $application->address }}</p></div><div class="text-right"><x-admin.status-badge :status="$application->status"/><p class="mt-2 text-xs text-slate-400">Submitted {{ $application->created_at->format('M d, Y') }}</p></div></div><div class="mt-4 flex flex-wrap items-center gap-2">@if($application->valid_id_path)<a class="btn-outline btn-sm" href="{{ route('admin.registrations.sellers.document',[$application,'valid-id']) }}">View Valid ID</a>@endif @if($application->business_permit_path)<a class="btn-outline btn-sm" href="{{ route('admin.registrations.sellers.document',[$application,'business-permit']) }}">View Business Permit</a>@endif @if(in_array($application->status,['pending','escalated','awaiting_final_review'],true))<form method="POST" action="{{ route('admin.sellers.applications.review',$application) }}" class="flex flex-1 flex-wrap gap-2">@csrf<input name="review_notes" class="input min-w-52 flex-1" placeholder="Reason required when rejecting"><button name="status" value="approved" class="btn-primary">Approve</button><button name="status" value="rejected" class="btn-outline text-rose-600">Reject</button></form>@elseif($application->review_notes)<p class="text-sm text-slate-500">Review note: {{ $application->review_notes }}</p>@endif</div></article>@empty<div class="card p-10 text-center text-slate-500">No Seller applications match these filters.</div>@endforelse</div></section>@endif
@endsection
