<?php
namespace App\Services;
use App\Models\{DeliveryArea,Shipment,User};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class ParcelWorkflowService {
 public function assignPickup(Shipment $shipment,User $actor,User $rider):Shipment{return DB::transaction(function()use($shipment,$actor,$rider){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();$this->available($rider);if($shipment->status!=='ready_for_pickup')throw ValidationException::withMessages(['status'=>'Only Pickup Requests can be assigned.']);$shipment->update(['pickup_rider_id'=>$rider->id,'pickup_assigned_by'=>$actor->id,'assigned_at'=>now(),'status'=>'pickup_assigned']);$rider->riderProfile->update(['availability'=>'assigned']);$this->event($shipment,$actor,'pickup_assigned',$rider->name.' assigned for Seller pickup.');NotificationService::send($rider->id,'New parcel pickup assignment',"Collect {$shipment->parcel_code} from {$shipment->store?->name}.",'logistics',route('rider.shipments.show',$shipment),['shipment_id'=>$shipment->id],'package');return $shipment;});}
 public function acceptPickup(Shipment $shipment,User $rider):Shipment{$this->pickupOwner($shipment,$rider);$result=$this->change($shipment,$rider,'pickup_assigned','pickup_accepted',['pickup_accepted_at'=>now()],$rider->name.' accepted the pickup assignment.');$rider->riderProfile?->update(['availability'=>'on_pickup']);return $result;}
 public function confirmPickup(Shipment $shipment,User $rider,string $code):Shipment{$this->pickupOwner($shipment,$rider);$this->code($shipment,$code);if(!$shipment->pickup_accepted_at)throw ValidationException::withMessages(['status'=>'Accept the Pickup Assignment before collecting the Parcel.']);return $this->change($shipment,$rider,'pickup_accepted','picked_up',['picked_up_at'=>now()],'Parcel collected from Seller by '.$rider->name.'.');}
 public function arriveSortingCenter(Shipment $shipment,User $rider):Shipment{$this->pickupOwner($shipment,$rider);return DB::transaction(function()use($shipment,$rider){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();if($shipment->status!=='picked_up'||$shipment->pickup_arrived_at)throw ValidationException::withMessages(['status'=>'This Parcel is not awaiting Sorting Center arrival.']);$shipment->update(['pickup_arrived_at'=>now()]);$this->event($shipment,$rider,'pickup_arrived','Pickup Rider arrived at the Sorting Center.');$this->releaseIfIdle($rider,$shipment);return $shipment;});}
 public function receive(Shipment $shipment,User $actor):Shipment{return DB::transaction(function()use($shipment,$actor){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();if($shipment->status!=='picked_up'||!$shipment->pickup_arrived_at)throw ValidationException::withMessages(['status'=>'Pickup Rider must arrive at the Sorting Center first.']);$shipment->update(['status'=>'at_sorting_center','received_by'=>$actor->id,'received_at'=>now()]);$this->event($shipment,$actor,'at_sorting_center','Parcel received at the Sorting Center.');app(OrderProgressService::class)->syncShipment($shipment);return $shipment;});}
 public function confirmScan(Shipment $shipment,User $actor,string $code):Shipment{$this->code($shipment,$code);return DB::transaction(function()use($shipment,$actor){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();if($shipment->status!=='at_sorting_center'||!$shipment->received_at||$shipment->parcel_scanned_at)throw ValidationException::withMessages(['status'=>'Receive the Parcel before confirming its code.']);$shipment->update(['parcel_scanned_at'=>now()]);$this->event($shipment,$actor,'parcel_confirmed','Parcel code validated.');return $shipment;});}
 public function sort(Shipment $shipment,User $actor,DeliveryArea $area):Shipment{return DB::transaction(function()use($shipment,$actor,$area){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();if($shipment->status!=='at_sorting_center'||!$shipment->received_at||!$shipment->parcel_scanned_at)throw ValidationException::withMessages(['status'=>'Receive and confirm the Parcel code before sorting.']);abort_unless($area->is_active,422);$shipment->update(['delivery_area_id'=>$area->id,'sorted_by'=>$actor->id,'sorted_at'=>now(),'status'=>'sorted']);$this->event($shipment,$actor,'sorted','Sorted to '.$area->name,$area->name);return $shipment;});}
 public function assignDelivery(Shipment $shipment,User $actor,User $rider):Shipment{return DB::transaction(function()use($shipment,$actor,$rider){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();$this->available($rider);if($shipment->status!=='sorted'||!$shipment->delivery_area_id)throw ValidationException::withMessages(['status'=>'Parcel must be sorted into a Delivery Area first.']);if(!$rider->riderProfile->deliveryAreas()->whereKey($shipment->delivery_area_id)->exists())throw ValidationException::withMessages(['rider_id'=>'This Rider is not assigned to the Parcel delivery area.']);$shipment->update(['rider_id'=>$rider->id,'delivery_assigned_by'=>$actor->id,'delivery_assigned_at'=>now(),'assigned_at'=>now(),'status'=>'assigned_to_rider']);$rider->riderProfile->update(['availability'=>'assigned']);$this->event($shipment,$actor,'assigned_to_rider','Delivery Rider assigned for '.$shipment->deliveryArea->name,$shipment->deliveryArea->name);NotificationService::send($rider->id,'New parcel delivery assignment',"Deliver {$shipment->parcel_code} in {$shipment->deliveryArea->name}.",'logistics',route('rider.shipments.show',$shipment),['shipment_id'=>$shipment->id],'package');return $shipment;});}
 public function acceptDelivery(Shipment $shipment,User $rider):Shipment{$this->deliveryOwner($shipment,$rider);return DB::transaction(function()use($shipment,$rider){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();if($shipment->status!=='assigned_to_rider'||$shipment->delivery_accepted_at)throw ValidationException::withMessages(['status'=>'This delivery assignment cannot be accepted.']);$shipment->update(['delivery_accepted_at'=>now()]);$rider->riderProfile?->update(['availability'=>'on_delivery']);$this->event($shipment,$rider,'delivery_accepted','Delivery Rider accepted the Parcel assignment.');return $shipment;});}
 public function startDelivery(Shipment $shipment,User $rider):Shipment{$this->deliveryOwner($shipment,$rider);if(!$shipment->delivery_accepted_at)throw ValidationException::withMessages(['status'=>'Accept the Delivery Assignment first.']);$result=$this->change($shipment,$rider,'assigned_to_rider','out_for_delivery',[],'Parcel is out for delivery.');app(BuyerOrderNotificationService::class)->send($result->order,'out_for_delivery',$result->sellerOrder);return $result;}
 public function deliver(Shipment $shipment,User $rider):Shipment{$this->deliveryOwner($shipment,$rider);if(!$shipment->proofOfDelivery)throw ValidationException::withMessages(['pod'=>'Submit Proof of Delivery before completing this delivery.']);app(CodCollectionService::class)->settleForDelivery($shipment);$result=$this->change($shipment,$rider,'out_for_delivery','delivered',['delivered_at'=>now()],'Parcel delivered to Buyer.');$this->releaseIfIdle($rider,$result);app(BuyerOrderNotificationService::class)->send($result->order,'delivered',$result->sellerOrder);NotificationService::send($result->store->user_id,'Parcel delivered',"{$result->parcel_code} was delivered to the Buyer.",'logistics',route('seller.orders.show',$result->sellerOrder),['shipment_id'=>$result->id],'package');return $result;}
 public function fail(Shipment $shipment,User $rider,string $reason):Shipment{$this->deliveryOwner($shipment,$rider);$result=$this->change($shipment,$rider,'out_for_delivery','delivery_failed',['failure_reason'=>$reason],$reason);$rider->riderProfile?->update(['availability'=>'available']);NotificationService::send($result->order->user_id,'Delivery attempt failed',"Parcel {$result->parcel_code} could not be delivered: {$reason}",'buyer_order_progress',route('orders.show',$result->order->order_number),['shipment_id'=>$result->id,'status'=>'delivery_failed'],'package');foreach(User::where('is_active',true)->whereHas('roles',fn($q)=>$q->where('slug','logistics'))->get() as $manager)NotificationService::send($manager->id,'Delivery failed',"{$result->parcel_code}: {$reason}",'logistics',route('logistics.tracking',['shipment'=>$result->id]),['shipment_id'=>$result->id],'package');return $result;}
 public function reschedule(Shipment $shipment,User $actor):Shipment{if(!$shipment->rider)throw ValidationException::withMessages(['rider_id'=>'Assign a Delivery Rider before rescheduling.']);$this->available($shipment->rider);$result=$this->change($shipment,$actor,'delivery_failed','assigned_to_rider',['failure_reason'=>null],'Delivery rescheduled.');$shipment->rider->riderProfile->update(['availability'=>'assigned']);return $result;}
 public function return(Shipment $shipment,User $actor,string $reason):Shipment{return $this->change($shipment,$actor,'delivery_failed','returned',['returned_at'=>now(),'failure_reason'=>$reason],$reason);}
 protected function change(Shipment $shipment,User $actor,string $from,string $to,array $values,string $note):Shipment{return DB::transaction(function()use($shipment,$actor,$from,$to,$values,$note){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();if($shipment->status!==$from)throw ValidationException::withMessages(['status'=>'That Parcel transition is not allowed.']);$shipment->update($values+['status'=>$to]);$this->event($shipment,$actor,$to,$note);app(OrderProgressService::class)->syncShipment($shipment);return $shipment;});}
 protected function available(User $rider):void{$profile=$rider->riderProfile;if(!$rider->hasRole('rider')||!$rider->is_active||!$profile||!$profile->isAssignmentEligible())throw ValidationException::withMessages(['rider_id'=>'This Rider is not assignment-eligible. Check account, availability, and verified Driver license validity.']);$conflict=Shipment::where(fn($q)=>$q->where('pickup_rider_id',$rider->id)->orWhere('rider_id',$rider->id))->whereNotIn('status',['delivered','returned','completed'])->exists();if($conflict)throw ValidationException::withMessages(['rider_id'=>'This Rider already has an active assignment.']);}
 protected function pickupOwner(Shipment $shipment,User $rider):void{abort_unless($shipment->pickup_rider_id===$rider->id,403);}
 protected function deliveryOwner(Shipment $shipment,User $rider):void{abort_unless($shipment->rider_id===$rider->id,403);}
 protected function code(Shipment $shipment,string $code):void{if($code!==($shipment->parcel_code?:$shipment->shipment_number))throw ValidationException::withMessages(['parcel_code'=>'Parcel code does not match.']);}
 protected function releaseIfIdle(User $rider,Shipment $except):void{$active=Shipment::whereKeyNot($except->id)->where(fn($q)=>$q->where('pickup_rider_id',$rider->id)->orWhere('rider_id',$rider->id))->whereNotIn('status',['delivered','returned','completed'])->exists();$rider->riderProfile?->update(['availability'=>$active?'assigned':'available']);}
 protected function event(Shipment $shipment,User $actor,string $status,string $note,?string $location=null):void{$shipment->events()->create(['actor_id'=>$actor->id,'status'=>$status,'location'=>$location,'note'=>$note,'metadata'=>['actor_roles'=>$actor->roles()->pluck('slug')->all()]]);}
}
