<?php
namespace App\Services;
use App\Models\{LogisticsSetting,Order,Shipment,ShipmentTrackingPoint,User};use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class ShipmentTrackingService {
 public const ACTIVE=['assigned','pickup_scheduled','picked_up','at_hub','hub_transfer','in_transit','out_for_delivery','delivery_attempted','exception'];
 public function record(Shipment $shipment,User $rider,array $data):ShipmentTrackingPoint {abort_unless($this->enabled(),403);abort_unless($rider->hasRole('rider')&&$shipment->rider_id===$rider->id,403);if(!in_array($shipment->status,self::ACTIVE,true))throw ValidationException::withMessages(['shipment'=>'No active authorized tracking session exists.']);return DB::transaction(function()use($shipment,$rider,$data){$locked=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();abort_unless($locked->rider_id===$rider->id,403);return ShipmentTrackingPoint::create(['shipment_id'=>$locked->id,'rider_id'=>$rider->id,'source'=>'device','latitude'=>$data['latitude'],'longitude'=>$data['longitude'],'accuracy'=>$data['accuracy']??null,'heading'=>$data['heading']??null,'speed'=>$data['speed']??null,'recorded_at'=>now()]);});}
 public function simulate(Shipment $shipment,array $data):ShipmentTrackingPoint {abort_unless(app()->environment('local')&&$shipment->rider_id&&in_array($shipment->status,self::ACTIVE,true),403);return ShipmentTrackingPoint::create(['shipment_id'=>$shipment->id,'rider_id'=>$shipment->rider_id,'source'=>'simulation','latitude'=>$data['latitude'],'longitude'=>$data['longitude'],'recorded_at'=>now()]);}
 public function logisticsFeed(Shipment $shipment):array{return $this->feed($shipment,true);}
 public function buyerFeed(Order $order,Shipment $shipment,User $buyer):array {abort_unless($this->enabled()&&LogisticsSetting::valueFor('buyer_tracking_visibility',config('logistics.buyer_live_tracking'))&&$order->user_id===$buyer->id&&$shipment->order_id===$order->id,403);return $this->feed($shipment,false);}
 protected function feed(Shipment $shipment,bool $full):array {$point=$shipment->latestTrackingPoint()->first();$interval=(int)LogisticsSetting::valueFor('tracking_interval_seconds',config('logistics.tracking_interval_seconds'));$location=$point?['latitude'=>(float)$point->latitude,'longitude'=>(float)$point->longitude,'source'=>$point->source,'recorded_at'=>$point->recorded_at->toIso8601String()]:null;if($location&&$full)$location+=['accuracy'=>$point->accuracy!==null?(float)$point->accuracy:null,'heading'=>$point->heading!==null?(float)$point->heading:null,'speed'=>$point->speed!==null?(float)$point->speed:null];return ['shipment_id'=>$shipment->id,'status'=>$shipment->status,'live'=>(bool)$point&&$point->recorded_at->gt(now()->subSeconds(max(60,$interval*3))),'location'=>$location,'eta'=>$shipment->estimated_delivery_at?->toIso8601String(),'routing_available'=>filled(config('logistics.routing_provider'))&&filled(config('logistics.routing_api_key'))];}
 protected function enabled():bool{return (bool)LogisticsSetting::valueFor('enable_live_tracking',config('logistics.live_tracking_enabled'));}
}
