<?php
namespace App\Http\Controllers\Rider;
use App\Http\Controllers\Controller;use App\Models\{ProofOfDelivery,Shipment};use App\Services\{CodCollectionService,ShipmentService,ShipmentTrackingService};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class RiderController extends Controller {
 public function dashboard(Request $r){$shipments=Shipment::with(['store','order'])->where('rider_id',$r->user()->id)->whereNotIn('status',['delivered'])->latest()->get();return view('rider.dashboard',compact('shipments'));}
 public function show(Request $r,Shipment $shipment){abort_unless($shipment->rider_id===$r->user()->id,403);$shipment->load(['store','order','sellerOrder.items','vehicle','events.actor','proofOfDelivery']);return view('rider.show',compact('shipment'));}
 public function status(Request $r,Shipment $shipment,ShipmentService $service){abort_unless($shipment->rider_id===$r->user()->id,403);$d=$r->validate(['status'=>'required|in:out_for_delivery,delivery_attempted,delivered,exception','note'=>'nullable|string|max:500']);$service->transition($shipment,$r->user(),$d['status'],$d['note']??null);return back()->with('success','Delivery status updated.');}
 public function collectCod(Request $r,Shipment $shipment,CodCollectionService $service){$service->collect($shipment,$r->user());return back()->with('success','COD collection confirmed.');}
 public function location(Request $r,Shipment $shipment,ShipmentTrackingService $tracking){$d=$r->validate(['latitude'=>'required|numeric|between:-90,90','longitude'=>'required|numeric|between:-180,180','accuracy'=>'nullable|numeric|min:0|max:10000','heading'=>'nullable|numeric|between:0,360','speed'=>'nullable|numeric|min:0|max:500']);$point=$tracking->record($shipment,$r->user(),$d);return response()->json(['saved'=>true,'recorded_at'=>$point->recorded_at->toIso8601String()]);}
 public function pod(Request $r,Shipment $shipment){abort_unless($shipment->rider_id===$r->user()->id,403);$d=$r->validate(['recipient_name'=>'required|string|max:100','photo'=>'nullable|image|max:5120','notes'=>'nullable|string|max:1000']);$pod=DB::transaction(function()use($r,$shipment,$d){$path=$r->file('photo')?->store('pod');return ProofOfDelivery::updateOrCreate(['shipment_id'=>$shipment->id],['submitted_by'=>$r->user()->id,'recipient_name'=>$d['recipient_name'],'photo_path'=>$path,'notes'=>$d['notes']??null,'status'=>'pending','submitted_at'=>now()]);});foreach(\App\Models\Role::where('slug','logistics')->with('users')->first()?->users??[] as $user)\App\Services\NotificationService::send($user->id,'Proof of Delivery submitted.',"{$shipment->shipment_number} requires POD review.",'logistics',route('logistics.pod'),['pod_id'=>$pod->id],'package');return back()->with('success','Proof of Delivery submitted.');}
}
