@extends('layouts.admin')
@section('title','Manage Shops')
@section('content')
@php $viewer=auth()->user(); $can=fn($permission)=>$viewer->hasPermissionTo($permission); $tabs=[''=>'All','active'=>'Active','pending'=>'Pending','restricted'=>'Restricted','suspended'=>'Suspended']; @endphp
<div><p class="text-sm font-semibold text-brand-600">Marketplace</p><h1 class="text-2xl font-extrabold">Manage Shops</h1></div>
<div class="mt-6 flex gap-5 border-b">@foreach($tabs as $key=>$label)<a href="{{ route('admin.shops.index',['status'=>$key]) }}" class="border-b-2 px-1 pb-3 text-sm font-semibold {{ request('status','')===$key?'border-brand-500 text-brand-700':'border-transparent text-slate-500' }}">{{ $label }}</a>@endforeach</div>
<form class="mt-5 max-w-md"><input type="hidden" name="status" value="{{ request('status') }}"><input class="input" name="q" value="{{ request('q') }}" placeholder="Search shop, seller, or email"></form>
<div class="card mt-5 overflow-x-auto"><table class="w-full min-w-[950px] text-left text-sm"><thead><tr class="border-b"><th class="p-4">Shop</th><th>Seller</th><th>Products</th><th>Orders</th><th>Rating</th><th>Reports</th><th>Violations</th><th>Status</th><th>Joined</th><th></th></tr></thead><tbody>
@forelse($shops as $shop) @php($application=$shop->user->sellerApplications->sortByDesc('created_at')->first())
<tr class="border-b"><td class="p-4"><b>{{ $shop->name }}</b></td><td>{{ $shop->user->name }}<p class="text-xs text-slate-400">{{ $shop->user->email }}</p></td><td>{{ $shop->products_count }}</td><td>{{ $shop->seller_orders_count }}</td><td>{{ number_format($shop->rating_avg,1) }}</td><td>{{ $shop->reports_count }}</td><td>{{ $shop->violations_count }}</td><td><x-admin.status-badge :status="$shop->status"/></td><td>{{ $shop->created_at->format('M d, Y') }}</td><td><div class="flex min-w-[190px] flex-wrap gap-2"><a class="font-semibold text-brand-600" href="{{ route('admin.shops.show',$shop) }}">View Shop</a>@if($shop->status==='pending'&&in_array($application?->status,['pending','escalated','awaiting_final_review'],true)&&$can('approve_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}">@csrf<input type="hidden" name="action" value="approve"><button class="font-semibold text-leaf-600">Approve</button></form>@endif @if($shop->status==='pending'&&in_array($application?->status,['pending','escalated','awaiting_final_review'],true)&&$can('reject_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" data-confirm-title="Reject this application?" data-confirm-action="Reject" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="reject"><button class="font-semibold text-rose-600">Reject</button></form>@endif</div></td></tr>
@empty<tr><td colspan="10" class="p-10 text-center text-slate-500">No shops found.</td></tr>@endforelse
</tbody></table></div><div class="mt-4">{{ $shops->links() }}</div>
@endsection
