@extends('layouts.admin')
@section('title', $shop->name)
@section('content')
@php
    $viewer = auth()->user();
    $can = fn ($permission) => $viewer->hasPermissionTo($permission);
    $productImage = fn ($product) => $product->main_image ? asset('storage/'.$product->main_image) : null;
@endphp
<a href="{{ route('admin.shops.index') }}" class="text-sm font-semibold text-brand-700">&larr; Manage Shops</a>
<section class="card mt-4 overflow-hidden">
    @if($shop->banner)<img src="{{ asset('storage/'.$shop->banner) }}" alt="{{ $shop->name }} banner" class="h-40 w-full object-cover">@endif
    <div class="flex flex-wrap items-center gap-4 p-6"><x-shop-avatar :shop="$shop" size="h-20 w-20" /><div class="min-w-0 flex-1"><h1 class="text-2xl font-extrabold text-navy-900">{{ $shop->name }}</h1><p class="mt-1 text-sm text-slate-600">Seller: <strong>{{ $shop->user->name }}</strong> · {{ $shop->user->email }}</p></div><x-admin.status-badge :status="$shop->status" /><a href="{{ route('shops.show', $shop->slug) }}" class="btn-outline">View Public Shop</a></div>
</section>
<div class="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach(['Products' => $shop->products_count, 'Orders' => $shop->seller_orders_count, 'Completed Orders' => $stats['completed_orders'], 'Cancelled Orders' => $stats['cancelled_orders'], 'Sales' => '₱'.number_format($stats['sales'], 2), 'Reviews' => $stats['reviews'], 'Reports' => $shop->reports_count, 'Violations' => $shop->violations_count] as $label => $value)<div class="card p-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-1 text-xl font-black text-navy-900">{{ $value }}</p></div>@endforeach</div>
@if($shop->status === 'pending' && $application && in_array($application->status, ['pending', 'escalated', 'awaiting_final_review'], true) && ($can('approve_shops') || $can('reject_shops')))<section class="card mt-6 p-5"><h2 class="font-bold text-navy-900">Admin Review</h2><p class="mt-1 text-sm text-slate-500">Final approval is managed from this connected Seller Application.</p><div class="mt-4 flex flex-wrap gap-3">@if($can('approve_shops'))<form method="POST" action="{{ route('admin.shops.status', $shop) }}" data-confirm-title="Approve this seller shop?" data-confirm-action="Approve Shop" data-confirm-type="success">@csrf<input type="hidden" name="action" value="approve"><button class="btn-primary">Approve</button></form>@endif @if($can('reject_shops'))<form method="POST" action="{{ route('admin.shops.status', $shop) }}" data-confirm-title="Reject this application?" data-confirm-action="Reject" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="reject"><button class="btn-outline text-rose-600">Reject</button></form>@endif</div></section>@endif
@if(($shop->status === 'active' && ($can('restrict_shops') || $can('suspend_shops'))) || (in_array($shop->status, ['restricted', 'suspended'], true) && $can('reactivate_shops')))<section class="card mt-6 p-5"><h2 class="font-bold text-navy-900">Shop Status Actions</h2><div class="mt-3 flex flex-wrap gap-3">@if($shop->status === 'active' && $can('restrict_shops'))<form method="POST" action="{{ route('admin.shops.status', $shop) }}" data-confirm-title="Restrict this shop?" data-confirm-action="Restrict" data-confirm-type="warning" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="restrict"><button class="btn-outline text-orange-700">Restrict Shop</button></form>@endif @if(in_array($shop->status, ['active', 'restricted'], true) && $can('suspend_shops'))<form method="POST" action="{{ route('admin.shops.status', $shop) }}" data-confirm-title="Suspend this shop?" data-confirm-action="Suspend" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="suspend"><button class="btn-outline text-rose-600">Suspend Shop</button></form>@endif @if(in_array($shop->status, ['restricted', 'suspended'], true) && $can('reactivate_shops'))<form method="POST" action="{{ route('admin.shops.status', $shop) }}" data-confirm-title="Restore this shop?" data-confirm-action="Restore" data-confirm-type="success">@csrf<input type="hidden" name="action" value="reactivate"><button class="btn-primary">Restore Shop</button></form>@endif</div></section>@endif
<div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="card p-5"><div class="flex items-center justify-between"><h2 class="font-bold text-navy-900">Products</h2><a href="{{ route('admin.products.index', ['shop_id' => $shop->id]) }}" class="text-sm font-semibold text-brand-700">View All Products &rarr;</a></div>@forelse($shop->products->take(8) as $product)<div class="flex items-center gap-3 border-t py-3"><div class="h-11 w-11 shrink-0 overflow-hidden rounded-lg bg-slate-100">@if($productImage($product))<img src="{{ $productImage($product) }}" alt="{{ $product->name }}" class="h-full w-full object-cover">@endif</div><div class="min-w-0 flex-1"><p class="truncate font-semibold text-navy-800">{{ $product->name }}</p><p class="text-xs text-slate-500">{{ $product->category?->name ?: 'Uncategorized' }} · {{ $product->stock }} in stock</p></div><x-admin.status-badge :status="$product->is_active ? 'active' : 'inactive'" /></div>@empty<p class="mt-4 text-sm text-slate-500">No products yet.</p>@endforelse</section><section class="card p-5"><h2 class="font-bold text-navy-900">Administrative Activity</h2>@forelse($activity as $item)<div class="border-t py-3 text-sm"><p class="font-semibold text-navy-800">{{ str_replace('.', ' ', ucwords($item->action, '.')) }}</p><p class="text-xs text-slate-500">{{ $item->user?->name ?? 'System' }} · {{ $item->created_at->format('M d, Y g:i A') }}</p>@if(data_get($item->details, 'reason'))<p class="mt-1 text-sm text-slate-600">{{ data_get($item->details, 'reason') }}</p>@endif</div>@empty<p class="mt-4 text-sm text-slate-500">No administrative activity yet.</p>@endforelse</section></div>
@if($can('add_shop_notes'))<section class="card mt-6 p-5"><h2 class="font-bold text-navy-900">Private Administrative Note</h2><p class="mt-1 text-sm text-slate-500">Visible only to SHOPPICK administrators.</p><form method="POST" action="{{ route('admin.shops.notes', $shop) }}" class="mt-4 space-y-3">@csrf<textarea class="input min-h-28" name="note" required maxlength="1500" placeholder="Add an internal note about this shop..."></textarea><button class="btn-outline">Add Note</button></form>@if($shop->administrative_notes)<div class="mt-5 border-t pt-4"><p class="whitespace-pre-line text-sm text-slate-600">{{ $shop->administrative_notes }}</p></div>@endif</section>@endif
@endsection
