@extends('layouts.admin')
@section('title',$shop->name)
@section('content')
@php
    $prefix=request()->routeIs('superadmin.*')?'superadmin':'admin';
    $user=auth()->user(); $full=$user->isSuperAdmin();
    $protected=!$full && in_array($shop->status,['restricted','suspended'],true) && $shop->statusChangedBy?->isSuperAdmin();
    $can=fn($permission)=>$full||$user->hasPermissionTo($permission);
@endphp
<a href="{{ route($prefix.'.shops.index') }}" class="text-sm text-brand-600">← Shops</a>
<div class="card mt-4 overflow-hidden">@if($shop->banner)<img src="{{ asset('storage/'.$shop->banner) }}" class="h-40 w-full object-cover">@endif<div class="flex flex-wrap items-center gap-4 p-5">@if($shop->logo)<img src="{{ asset('storage/'.$shop->logo) }}" class="h-20 w-20 rounded-xl object-cover">@endif<div class="flex-1"><h1 class="text-2xl font-extrabold">{{ $shop->name }}</h1><p class="text-sm text-slate-500">{{ $shop->user->name }} · {{ $shop->user->email }} · Joined {{ $shop->created_at->format('M d, Y') }}</p><p class="mt-1 text-xs text-slate-500">Seller: {{ $shop->user->sellerProfile?->status ?? 'No seller profile' }}</p></div><x-admin.status-badge :status="$shop->status"/></div></div>
@if($protected)<div class="alert-error mt-4">Restricted by Super Admin. Admin users cannot override this decision.</div>@endif
@if($shop->status_reason)<div class="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><strong>Status reason:</strong> {{ $shop->status_reason }}</div>@endif
@if($application?->status==='escalated')<div class="mt-4 rounded-xl border border-sun-200 bg-sun-50 p-4 text-sm"><p class="font-bold uppercase text-sun-700">Escalation</p><p class="mt-2"><b>Escalated by:</b> {{ $application->escalator?->name }}</p><p><b>Escalated at:</b> {{ $application->escalated_at?->format('M d, Y g:i A') }}</p><p><b>Reason:</b> {{ $application->escalation_reason }}</p></div>@endif
@if($application)<section class="card mt-6 p-5"><h2 class="font-bold text-navy-900">Seller Application</h2><div class="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><div><p class="text-xs text-slate-400">Seller</p><b>{{ $shop->user->name }}</b><p>{{ $shop->user->email }}</p></div><div><p class="text-xs text-slate-400">Mobile Number</p><p>{{ $application->phone }}</p></div><div><p class="text-xs text-slate-400">Submitted</p><p>{{ $application->created_at->format('M d, Y g:i A') }}</p></div><div class="sm:col-span-2"><p class="text-xs text-slate-400">Seller / Store Address</p><p>{{ $application->address }}</p></div><div><p class="text-xs text-slate-400">Application Status</p><x-admin.status-badge :status="$application->status"/></div><div class="sm:col-span-2 lg:col-span-3"><p class="text-xs text-slate-400">Store Description</p><p>{{ $application->store_description ?: 'No description.' }}</p></div>@if($application->admin_recommendation)<div class="sm:col-span-2 lg:col-span-3 rounded-xl bg-slate-50 p-4"><p class="text-xs font-bold uppercase text-slate-400">Admin Recommendation</p><p class="font-semibold capitalize">{{ $application->admin_recommendation }}</p><p>{{ $application->admin_review_notes ?: 'No additional notes.' }}</p><p class="mt-1 text-xs text-slate-400">{{ $application->adminReviewer?->name }} · {{ $application->admin_reviewed_at?->format('M d, Y g:i A') }}</p></div>@endif @if($application->review_notes)<div class="sm:col-span-2 lg:col-span-3"><p class="text-xs text-slate-400">Final Decision Notes</p><p>{{ $application->review_notes }}</p></div>@endif</div>
@if(!$full&&$shop->status==='pending'&&$application->status==='pending'&&($can('approve_shops')||$can('reject_shops')))<div class="mt-5 border-t pt-5"><h3 class="text-sm font-bold uppercase tracking-wide text-slate-500">Admin Review</h3><p class="mt-1 text-sm text-slate-500">Approve or reject normal applications. Escalate only applications requiring Super Admin review.</p><div class="mt-3 flex flex-wrap gap-3">@if($can('approve_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" data-confirm-title="Approve this seller shop?" data-confirm-message="This will activate the Shop and allow the Seller to start selling on SHOPPICK." data-confirm-action="Approve Shop" data-confirm-type="success">@csrf<input type="hidden" name="action" value="approve"><button class="btn-primary">Approve</button></form>@endif @if($can('reject_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" data-confirm-title="Reject this seller application?" data-confirm-action="Reject Application" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="reject"><button class="btn-outline text-rose-600">Reject</button></form>@endif</div></div>
@elseif($full&&$shop->status==='pending'&&$application->status==='escalated')<div class="mt-5 border-t pt-5"><h3 class="text-sm font-bold uppercase tracking-wide text-slate-500">Super Admin Escalation Review</h3><div class="mt-3 flex flex-wrap gap-3"><form method="POST" action="{{ route('superadmin.shops.status',$shop) }}" data-confirm-title="Approve this escalated seller shop?" data-confirm-message="This activates the shop and enables Seller access." data-confirm-action="Approve Shop" data-confirm-type="success">@csrf<input type="hidden" name="action" value="approve"><button class="btn-primary">Approve Shop</button></form><form method="POST" action="{{ route('superadmin.shops.status',$shop) }}" data-confirm-title="Reject this escalated seller application?" data-confirm-message="This rejects the application and keeps Seller access blocked." data-confirm-action="Reject Application" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="reject"><button class="btn-outline text-rose-600">Reject Application</button></form></div></div>
@elseif($full&&$application->status==='pending')<p class="mt-5 border-t pt-5 text-sm font-semibold text-sun-600">Pending Admin review. Super Admin may view this application for oversight.</p>@endif
</section>@endif
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach(['Products'=>$shop->products_count,'Orders'=>$shop->seller_orders_count,'Completed Orders'=>$stats['completed_orders'],'Cancelled Orders'=>$stats['cancelled_orders'],'Rating'=>number_format($shop->rating_avg,1),'Reports'=>$shop->reports_count,'Confirmed Violations'=>$shop->violations_count,'Reviews'=>$stats['reviews']] as $label=>$value)<div class="card p-4"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-1 text-xl font-black">{{ $value }}</p></div>@endforeach @if($can('view_reports'))<div class="card p-4"><p class="text-sm text-slate-500">Completed Sales</p><p class="mt-1 text-xl font-black">₱{{ number_format($stats['sales'],2) }}</p></div>@endif</div>

@if(!$protected)<section class="card mt-6 p-5"><h2 class="font-bold">Available Actions</h2><div class="mt-4 flex flex-wrap gap-3">
@if($shop->status==='active'&&$can('restrict_shops'))<form method="POST" action="{{ route($prefix.'.shops.status',$shop) }}" data-confirm-title="Restrict this shop?" data-confirm-message="This will temporarily limit the shop's selling capabilities." data-confirm-action="Restrict" data-confirm-type="warning" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="restrict"><button class="btn-outline">Restrict</button></form>@endif
@if(in_array($shop->status,['active','restricted'],true)&&$can('suspend_shops'))<form method="POST" action="{{ route($prefix.'.shops.status',$shop) }}" data-confirm-title="Suspend this shop?" data-confirm-message="This shop will temporarily stop selling products. Existing order records will remain available." data-confirm-action="Suspend" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="suspend"><button class="btn-outline text-rose-600">Suspend</button></form>@endif
@if(in_array($shop->status,['restricted','suspended'],true)&&$can('reactivate_shops'))<form method="POST" action="{{ route($prefix.'.shops.status',$shop) }}" data-confirm-title="Reactivate this shop?" data-confirm-message="This will restore the shop and allow it to operate on SHOPPICK again." data-confirm-action="Reactivate" data-confirm-type="success">@csrf<input type="hidden" name="action" value="reactivate"><button class="btn-primary">Reactivate</button></form>@endif
</div></section>@endif

<div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="card p-5"><div class="flex justify-between"><h2 class="font-bold">Shop Products</h2>@if($user->hasPermissionTo('manage_products')||$full)<a href="{{ route('admin.products.index',['q'=>$shop->name]) }}" class="text-sm text-brand-600">View Products</a>@endif</div>@forelse($shop->products->take(8) as $product)<div class="flex items-center gap-3 border-t py-3"><div class="min-w-0 flex-1"><b>{{ $product->name }}</b><p class="text-xs text-slate-500">{{ $product->category?->name }} · ₱{{ number_format($product->price,2) }} · Stock {{ $product->stock }}</p></div><x-admin.status-badge :status="$product->moderation_status"/></div>@empty<p class="mt-4 text-sm text-slate-500">No products.</p>@endforelse</section>
@if($can('view_shop_violations'))<section class="card p-5"><h2 class="font-bold">Confirmed Violations</h2>@forelse($shop->violations->sortByDesc('created_at') as $violation)<div class="border-t py-3"><b>{{ ucwords(str_replace('_',' ',$violation->category)) }}</b><p class="text-sm">{{ $violation->description }}</p><p class="text-xs text-slate-400">{{ $violation->action_taken }} · {{ $violation->created_at->format('M d, Y') }}</p></div>@empty<p class="mt-4 text-sm text-slate-500">No confirmed violations.</p>@endforelse</section>@endif
@if($can('view_shop_reports'))<section class="card p-5"><h2 class="font-bold">Shop Reports</h2>@forelse($shop->reports->sortByDesc('created_at')->take(8) as $report)<div class="border-t py-3"><b>{{ $report->report_number }}</b><p class="text-sm">{{ ucwords(str_replace('_',' ',$report->reason)) }} · {{ ucwords(str_replace('_',' ',$report->status)) }}</p></div>@empty<p class="mt-4 text-sm text-slate-500">No direct shop reports.</p>@endforelse @if($user->hasPermissionTo('manage_reports')||$full)<a href="{{ route($prefix.'.reports.index',['target_type'=>\App\Models\Store::class]) }}" class="btn-outline btn-sm mt-4">View Report Management</a>@endif</section>@endif
<section class="card p-5"><h2 class="font-bold">Administrative Activity</h2>@forelse($activity as $entry)<div class="border-t py-3 text-sm"><b>{{ ucwords(str_replace(['.','_'],' ',$entry->action)) }}</b><p class="text-slate-500">{{ $entry->user?->name ?? 'System' }} · {{ $entry->created_at->format('M d, Y g:i A') }}</p>@if(data_get($entry->details,'reason'))<p>{{ data_get($entry->details,'reason') }}</p>@endif</div>@empty<p class="mt-4 text-sm text-slate-500">No administrative activity.</p>@endforelse</section></div>

<div class="mt-6 grid gap-6 lg:grid-cols-2">@if($can('add_shop_notes'))<form method="POST" action="{{ route($prefix.'.shops.notes',$shop) }}" class="card space-y-3 p-5">@csrf<h2 class="font-bold">Private Administrative Note</h2><textarea class="input" name="note" required maxlength="1500" placeholder="Internal note (not visible to Buyers)"></textarea><button class="btn-outline">Add Note</button><pre class="whitespace-pre-wrap text-xs text-slate-500">{{ $shop->administrative_notes }}</pre></form>@endif @if(!$full && $application?->status==='pending' && $user->hasRole('admin') && $user->hasPermissionTo('review_shops'))<form method="POST" action="{{ route('admin.shops.escalate',$shop) }}" class="card space-y-3 p-5">@csrf<h2 class="font-bold">Escalate to Super Admin</h2><textarea class="input" name="reason" required maxlength="1000" placeholder="Required escalation reason"></textarea><button class="btn-outline text-rose-600">Escalate</button></form>@endif</div>
@endsection
