@extends('layouts.admin')
@section('title',$shop->name)
@section('content')
@php $user=auth()->user(); $can=fn($permission)=>$user->hasPermissionTo($permission); @endphp
<a href="{{ route('admin.shops.index') }}" class="text-sm text-brand-600">← Shops</a>
<div class="card mt-4 overflow-hidden">@if($shop->banner)<img src="{{ asset('storage/'.$shop->banner) }}" class="h-40 w-full object-cover">@endif<div class="flex flex-wrap items-center gap-4 p-5"><div class="flex-1"><h1 class="text-2xl font-extrabold">{{ $shop->name }}</h1><p class="text-sm text-slate-500">{{ $shop->user->name }} · {{ $shop->user->email }}</p></div><x-admin.status-badge :status="$shop->status"/></div>
@if($shop->status==='pending'&&$application&&in_array($application->status,['pending','escalated','awaiting_final_review'],true)&&($can('approve_shops')||$can('reject_shops')))<div class="border-t p-5"><h3 class="text-sm font-bold uppercase text-slate-500">Admin Review</h3><p class="mt-1 text-sm text-slate-500">Admin makes the final approval or rejection decision.</p><div class="mt-3 flex gap-3">@if($can('approve_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" data-confirm-title="Approve this seller shop?" data-confirm-action="Approve Shop" data-confirm-type="success">@csrf<input type="hidden" name="action" value="approve"><button class="btn-primary">Approve</button></form>@endif @if($can('reject_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" data-confirm-title="Reject this application?" data-confirm-action="Reject" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="reject"><button class="btn-outline text-rose-600">Reject</button></form>@endif</div></div>@endif</div>
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach(['Products'=>$shop->products_count,'Orders'=>$shop->seller_orders_count,'Completed Orders'=>$stats['completed_orders'],'Cancelled Orders'=>$stats['cancelled_orders'],'Sales'=>'₱'.number_format($stats['sales'],2),'Reviews'=>$stats['reviews'],'Reports'=>$shop->reports_count,'Violations'=>$shop->violations_count] as $label=>$value)<div class="card p-4"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-1 text-xl font-black">{{ $value }}</p></div>@endforeach</div>
@if($shop->status==='active'&&($can('restrict_shops')||$can('suspend_shops')))<div class="card mt-6 p-5"><h2 class="font-bold">Shop Status Actions</h2><div class="mt-3 flex flex-wrap gap-3">@if($can('restrict_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" data-confirm-title="Restrict this shop?" data-confirm-action="Restrict" data-confirm-type="warning" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="restrict"><button class="btn-outline">Restrict Shop</button></form>@endif @if($can('suspend_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" data-confirm-title="Suspend this shop?" data-confirm-action="Suspend" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="action" value="suspend"><button class="btn-outline text-rose-600">Suspend Shop</button></form>@endif</div></div>@elseif(in_array($shop->status,['restricted','suspended'],true)&&$can('reactivate_shops'))<form method="POST" action="{{ route('admin.shops.status',$shop) }}" class="card mt-6 p-5">@csrf<input type="hidden" name="action" value="reactivate"><h2 class="font-bold">Shop Status Actions</h2><button class="btn-primary mt-3">Reactivate Shop</button></form>@endif
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="card p-5"><h2 class="font-bold">Products</h2>@forelse($shop->products->take(8) as $product)<div class="border-t py-3 text-sm"><b>{{ $product->name }}</b><p class="text-xs text-slate-500">{{ $product->category?->name }} · {{ $product->stock }} in stock</p></div>@empty<p class="mt-4 text-sm text-slate-500">No products.</p>@endforelse</div><div class="card p-5"><h2 class="font-bold">Administrative Activity</h2>@forelse($activity as $item)<div class="border-t py-3 text-sm"><b>{{ str_replace('.',' ',ucwords($item->action,'.')) }}</b><p class="text-xs text-slate-500">{{ $item->user?->name ?? 'System' }} · {{ $item->created_at->format('M d, Y g:i A') }}</p></div>@empty<p class="mt-4 text-sm text-slate-500">No activity.</p>@endforelse</div></div>
@if($can('add_shop_notes'))<form method="POST" action="{{ route('admin.shops.notes',$shop) }}" class="card mt-6 space-y-3 p-5">@csrf<h2 class="font-bold">Private Administrative Note</h2><textarea class="input" name="note" required maxlength="1500"></textarea><button class="btn-outline">Add Note</button><pre class="whitespace-pre-wrap text-xs text-slate-500">{{ $shop->administrative_notes }}</pre></form>@endif
@endsection
