<?php
use App\Http\Controllers\Logistics\LogisticsController;use Illuminate\Support\Facades\Route;
Route::prefix('logistics')->name('logistics.')->middleware(['auth','role:logistics'])->group(function(){
 Route::get('dashboard',[LogisticsController::class,'dashboard'])->name('dashboard')->middleware('permission:view_logistics_dashboard');Route::post('dashboard/create-load',[LogisticsController::class,'quickCreateLoad'])->name('quick.create-load')->middleware('permission:manage_shipments');Route::post('dashboard/generate-invoice',[LogisticsController::class,'quickInvoice'])->name('quick.invoice')->middleware('permission:manage_logistics_billing');Route::get('shipments',[LogisticsController::class,'shipments'])->name('shipments.index')->middleware('permission:view_shipments');Route::get('shipments/{shipment}',[LogisticsController::class,'show'])->name('shipments.show')->middleware('permission:view_shipments');
 Route::get('dispatch',[LogisticsController::class,'dispatch'])->name('dispatch')->middleware('permission:manage_shipments');Route::post('shipments/{shipment}/assign',[LogisticsController::class,'assign'])->name('shipments.assign')->middleware('permission:assign_shipments');Route::post('shipments/{shipment}/status',[LogisticsController::class,'status'])->name('shipments.status')->middleware('permission:manage_shipments');Route::get('tracking',[LogisticsController::class,'tracking'])->name('tracking')->middleware('permission:view_shipments');Route::get('tracking/{shipment}/feed',[LogisticsController::class,'trackingFeed'])->name('tracking.feed')->middleware('permission:view_shipments');
 if(app()->environment('local'))Route::post('tracking/{shipment}/simulate',[LogisticsController::class,'trackingSimulate'])->name('tracking.simulate')->middleware('permission:manage_shipments');
 Route::get('fleet',[LogisticsController::class,'fleet'])->name('fleet')->middleware('permission:manage_fleet');Route::post('fleet',[LogisticsController::class,'vehicleStore'])->name('fleet.store')->middleware('permission:manage_fleet');Route::put('fleet/{vehicle}',[LogisticsController::class,'vehicleStatus'])->name('fleet.update')->middleware('permission:manage_fleet');
 Route::get('riders',[LogisticsController::class,'riders'])->name('riders')->middleware('permission:manage_riders');Route::post('riders',[LogisticsController::class,'riderStore'])->name('riders.store')->middleware('permission:manage_riders');Route::put('riders/{rider}',[LogisticsController::class,'riderUpdate'])->name('riders.update')->middleware('permission:manage_riders');
 Route::get('hubs',[LogisticsController::class,'hubs'])->name('hubs')->middleware('permission:manage_hubs');Route::post('hubs',[LogisticsController::class,'hubStore'])->name('hubs.store')->middleware('permission:manage_hubs');Route::post('shipments/{shipment}/hub',[LogisticsController::class,'hubMove'])->name('shipments.hub')->middleware('permission:manage_hubs');Route::get('proof-of-delivery',[LogisticsController::class,'pod'])->name('pod')->middleware('permission:review_pod');Route::post('proof-of-delivery/{pod}',[LogisticsController::class,'podReview'])->name('pod.review')->middleware('permission:review_pod');Route::get('proof-of-delivery/{pod}/file',[LogisticsController::class,'podFile'])->name('pod.file')->middleware('permission:review_pod');
 Route::get('billing',[LogisticsController::class,'billing'])->name('billing')->middleware('permission:manage_logistics_billing');Route::put('billing/{invoice}',[LogisticsController::class,'billingUpdate'])->name('billing.update')->middleware('permission:manage_logistics_billing');Route::get('reports',[LogisticsController::class,'reports'])->name('reports')->middleware('permission:view_logistics_reports');Route::get('ai-assistant',[LogisticsController::class,'ai'])->name('ai')->middleware('permission:manage_ai_logistics');Route::post('ai-assistant/analyze',[LogisticsController::class,'analyze'])->name('ai.analyze')->middleware('permission:manage_ai_logistics');Route::post('ai-assistant/{insight}',[LogisticsController::class,'insight'])->name('ai.update')->middleware('permission:manage_ai_logistics');
 Route::get('notifications',[LogisticsController::class,'notifications'])->name('notifications');Route::get('notifications/{notification}',[LogisticsController::class,'openNotification'])->name('notifications.open');Route::post('notifications/read-all',[LogisticsController::class,'readAllNotifications'])->name('notifications.read-all');Route::get('settings',[LogisticsController::class,'settings'])->name('settings')->middleware('permission:manage_logistics_settings');Route::put('settings',[LogisticsController::class,'settingsUpdate'])->name('settings.update')->middleware('permission:manage_logistics_settings');
});
