@extends('layouts.seller')
@section('title','Order '.$sellerOrder->seller_order_number)
@section('content')
@php
    $nextStatus=$sellerOrder->nextSellerStatus();
    $nextLabels=['confirmed'=>'Confirm Order','processing'=>'Start Processing','packed'=>'Mark as Packed','ready_to_ship'=>'Mark Ready to Ship'];
    $address=$sellerOrder->order->shipping_address;
@endphp
<div class="flex flex-wrap items-center justify-between gap-3"><div><a href="{{ route('seller.orders.index') }}" class="text-sm text-brand-600">← Back to orders</a><h1 class="mt-1 text-2xl font-extrabold text-navy-900">{{ $sellerOrder->seller_order_number }}</h1><p class="text-sm text-slate-500">Main order #{{ $sellerOrder->order->order_number }} · {{ $sellerOrder->created_at->format('M d, Y g:i A') }}</p></div><x-admin.status-badge :status="$sellerOrder->status"/></div>

@if($nextStatus)
<div class="card mt-5 flex flex-wrap items-center justify-between gap-3 border-brand-100 bg-brand-50/40 p-4"><div><p class="font-semibold text-navy-900">Next fulfillment step</p><p class="text-sm text-slate-600">Move this order forward when it is ready.</p></div><form method="POST" action="{{ route('seller.orders.status',$sellerOrder) }}">@csrf<input type="hidden" name="status" value="{{ $nextStatus }}"><button class="btn-primary">{{ $nextLabels[$nextStatus] }}</button></form></div>
@elseif($sellerOrder->status==='ready_to_ship')
<div class="alert-success mt-5">This order is ready for logistics pickup. Seller preparation is complete.</div>
@endif
@if($sellerOrder->shipment)<div class="card mt-5 p-5"><h2 class="font-bold">Delivery Progress</h2><div class="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div><p class="text-slate-400">Shipment</p><b>{{ $sellerOrder->shipment->shipment_number }}</b></div><div><p class="text-slate-400">Status</p><x-admin.status-badge :status="$sellerOrder->shipment->status"/></div><div><p class="text-slate-400">Rider</p><b>{{ $sellerOrder->shipment->rider?->name??'Unassigned' }}</b></div><div><p class="text-slate-400">Vehicle</p><b>{{ $sellerOrder->shipment->vehicle?->code??'Unassigned' }}</b></div><div><p class="text-slate-400">POD</p><b>{{ ucfirst($sellerOrder->shipment->proofOfDelivery?->status??'none') }}</b></div></div><p class="mt-3 text-xs text-slate-500">Delivery stages are managed by SHOPPICK Logistics and the assigned Rider.</p></div>@endif

<div class="mt-6 grid gap-6 lg:grid-cols-3"><div class="space-y-6 lg:col-span-2">
<section class="card p-5"><h2 class="font-bold text-navy-900">Products</h2>@foreach($sellerOrder->items as $item)<div class="flex gap-4 border-t py-4">@if($item->product_image)<img src="{{ asset('storage/'.$item->product_image) }}" alt="" class="h-16 w-16 rounded-xl object-cover">@endif<div class="min-w-0 flex-1"><p class="font-semibold">{{ $item->product_name }}</p>@if($item->variant_label)<p class="text-xs text-slate-500">{{ $item->variant_label }}</p>@endif<p class="text-xs text-slate-500">SKU {{ $item->sku ?: '—' }}</p></div><p>{{ $item->quantity }} × ₱{{ number_format($item->price,2) }}</p><strong>₱{{ number_format($item->total,2) }}</strong></div>@endforeach</section>
<section class="card p-5"><h2 class="font-bold">Order Timeline</h2>@foreach($sellerOrder->histories as $history)<div class="mt-4 border-l-2 border-brand-200 pl-4"><p class="font-semibold">{{ ucwords(str_replace('_',' ',$history->status)) }}</p><p class="text-xs text-slate-500">{{ $history->created_at->format('M d, Y g:i A') }}@if($history->changedBy) · {{ $history->changedBy->name }} ({{ $history->changedBy->roles->pluck('name')->join(', ') ?: 'User' }})@endif</p>@if($history->note)<p class="mt-1 text-sm">{{ $history->note }}</p>@endif</div>@endforeach</section>
</div><aside class="space-y-6">
<section class="card p-5"><h2 class="font-bold">Payment</h2><div class="mt-3 space-y-2 text-sm"><div class="flex justify-between"><span>Method</span><span>{{ $sellerOrder->order->paymentMethodLabel() }}</span></div><div class="flex justify-between"><span>Status</span><span class="font-semibold">{{ $sellerOrder->order->paymentStatusLabel() }}</span></div></div></section>
<section class="card p-5"><h2 class="font-bold">Buyer & Shipping</h2><p class="mt-3 font-semibold">{{ $sellerOrder->order->buyer_name }}</p><p class="text-sm text-slate-500">{{ $sellerOrder->order->buyer_phone }}</p><p class="mt-3 text-sm">{{ is_array($address) ? implode(', ',array_filter([$address['address_line']??$address['complete_address']??null,$address['barangay']??null,$address['city']??null,$address['province']??null,$address['postal_code']??null])) : '' }}</p></section>
<section class="card p-5"><h2 class="font-bold">Seller Earnings</h2><div class="mt-3 space-y-2 text-sm"><div class="flex justify-between"><span>Subtotal</span><span>₱{{ number_format($sellerOrder->subtotal,2) }}</span></div><div class="flex justify-between"><span>Commission</span><span>-₱{{ number_format($sellerOrder->commission_amount,2) }}</span></div><div class="flex justify-between border-t pt-2 font-bold"><span>Net</span><span>₱{{ number_format($sellerOrder->seller_total,2) }}</span></div></div></section>
@if(in_array($sellerOrder->status,['pending','confirmed','processing','packed'],true))<section class="card border-rose-100 p-5"><h2 class="font-bold text-rose-700">Cancel Order</h2><form method="POST" action="{{ route('seller.orders.status',$sellerOrder) }}" class="mt-3 space-y-3">@csrf<input type="hidden" name="status" value="cancelled"><textarea class="input" name="note" required maxlength="500" placeholder="Cancellation reason"></textarea><button class="btn-outline w-full text-rose-600">Cancel Order</button></form></section>@endif
</aside></div>
@endsection
