@extends('layouts.seller')
@section('title','Archived Product')
@section('content')
<div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm font-semibold text-brand-600">Archived Product</p><h1 class="text-2xl font-extrabold">{{ $product->name }}</h1></div><a href="{{ route('seller.products.index',['status'=>'archived']) }}" class="btn-outline">Back to Archived</a></div>
<div class="mt-6 grid gap-6 lg:grid-cols-[280px_1fr]">
    <div class="card overflow-hidden p-4"><div class="flex aspect-square items-center justify-center overflow-hidden rounded-xl bg-slate-100">@if($product->main_image)<img src="{{ asset('storage/'.$product->main_image) }}" class="h-full w-full object-cover" alt="{{ $product->name }}">@else<span class="text-sm text-slate-400">No product image</span>@endif</div></div>
    <div class="card p-6"><div class="grid gap-5 sm:grid-cols-2"><div><p class="text-xs uppercase text-slate-400">Category</p><p class="mt-1 font-semibold">{{ $product->category?->name ?? 'Uncategorized' }}</p></div><div><p class="text-xs uppercase text-slate-400">Status</p><div class="mt-1"><x-admin.status-badge status="archived"/></div></div><div><p class="text-xs uppercase text-slate-400">Price</p><p class="mt-1 font-semibold">₱{{ number_format($product->salePrice(),2) }}</p></div><div><p class="text-xs uppercase text-slate-400">Stock</p><p class="mt-1 font-semibold">{{ $product->stock }}</p></div><div><p class="text-xs uppercase text-slate-400">Archived date</p><p class="mt-1 font-semibold">{{ $product->deleted_at?->format('M d, Y g:i A') }}</p></div></div><p class="mt-6 text-sm text-slate-500">{{ $product->sellerVisibilityReason() }}</p><div class="mt-6 flex flex-wrap gap-3"><form method="POST" action="{{ route('seller.products.restore',$product) }}">@csrf<button class="btn-primary">Restore as Draft</button></form>@if(! $product->orderItems()->exists())<form method="POST" action="{{ route('seller.products.force-destroy',$product) }}" onsubmit="return confirm('Permanently delete this product? This cannot be undone.')">@csrf @method('DELETE')<button class="btn-outline text-rose-600">Delete Permanently</button></form>@endif</div></div>
</div>
@endsection
