@extends('layouts.seller')
@section('title','Add Product')
@section('content')
<div class="flex items-center justify-between"><div><p class="text-sm font-semibold text-brand-600">Catalog</p><h1 class="text-2xl font-extrabold">Add Product</h1></div><a href="{{ route('seller.products.index') }}" class="btn-outline">Cancel</a></div>
<form class="card mt-6 grid gap-5 p-6" method="POST" enctype="multipart/form-data" action="{{ route('seller.products.store') }}">@csrf
<div><label class="label">Product Name</label><input class="input" name="name" required value="{{ old('name') }}">@error('name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Category</label><select class="input" name="category_id" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="label">Brand</label><input class="input" name="brand" value="{{ old('brand') }}"></div><div><label class="label">SKU</label><input class="input" name="sku" value="{{ old('sku') }}"></div><div><label class="label">Price</label><input class="input" type="number" step=".01" min="0.01" name="price" required value="{{ old('price') }}"></div><div><label class="label">Discount %</label><input class="input" type="number" step=".01" min="0" max="100" name="discount" value="{{ old('discount',0) }}"></div><div><label class="label">Stock</label><input class="input" type="number" min="0" name="stock" required value="{{ old('stock',0) }}"></div><div><label class="label">Low-stock Threshold</label><input class="input" type="number" min="0" name="low_stock_threshold" value="{{ old('low_stock_threshold',5) }}"></div></div>
<div><label class="label">Description</label><textarea class="input" rows="5" name="description">{{ old('description') }}</textarea></div>
<div><label class="label">Product Images</label><input class="input" type="file" name="images[]" multiple accept="image/jpeg,image/png,image/webp"><p class="mt-1 text-xs text-slate-500">Uploaded images are checked before the product becomes public.</p>@error('images.*')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
<div class="flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><button type="submit" name="publication_action" value="draft" class="btn-outline">Save as Draft</button><button type="submit" name="publication_action" value="publish" class="btn-primary">Publish Product</button></div>
</form>
@endsection
