@extends('layouts.seller')
@section('title','Edit Product')
@section('content')
<div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm font-semibold text-brand-600">Catalog</p><h1 class="text-2xl font-extrabold">Edit Product</h1><p class="text-sm text-slate-500">Update {{ $product->name }} without creating a duplicate listing.</p></div><a href="{{ route('seller.products.index') }}" class="btn-outline">Cancel</a></div>
<form class="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]" method="POST" enctype="multipart/form-data" action="{{ route('seller.products.update',$product) }}">@csrf @method('PUT')
<div class="space-y-6">
<section class="card grid gap-4 p-6"><h2 class="font-bold">Product Information</h2>
<div><label class="label">Product Name</label><input class="input" name="name" required value="{{ old('name',$product->name) }}">@error('name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Category</label><select class="input" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$product->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="label">Brand</label><input class="input" name="brand" value="{{ old('brand',$product->brand) }}"></div><div><label class="label">SKU</label><input class="input" name="sku" value="{{ old('sku',$product->sku) }}">@error('sku')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="label">Price</label><input class="input" type="number" step=".01" min="0" name="price" required value="{{ old('price',$product->price) }}">@error('price')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="label">Discount %</label><input class="input" type="number" step=".01" min="0" max="100" name="discount" value="{{ old('discount',$product->discount) }}"></div><div><label class="label">Stock</label><input class="input" type="number" min="0" name="stock" required value="{{ old('stock',$product->stock) }}">@error('stock')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="label">Low-stock Threshold</label><input class="input" type="number" min="0" name="low_stock_threshold" value="{{ old('low_stock_threshold',$product->low_stock_threshold) }}"></div></div>
<div><label class="label">Description</label><textarea rows="5" class="input" name="description">{{ old('description',$product->description) }}</textarea></div></section>

<section class="card p-6"><h2 class="font-bold">Product Images</h2><p class="mt-1 text-xs text-slate-500">Existing images stay unchanged unless you select Remove. New images will pass image moderation.</p>
<div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">@forelse($product->images as $image)<label class="relative overflow-hidden rounded-xl border border-slate-200 bg-slate-50"><img src="{{ asset('storage/'.$image->path) }}" class="aspect-square w-full object-cover"><span class="flex items-center gap-2 p-2 text-xs text-rose-600"><input type="checkbox" name="remove_image_ids[]" value="{{ $image->id }}" @disabled($product->images->count()===1)>Remove</span>@if($image->is_primary)<span class="absolute left-2 top-2 rounded bg-brand-600 px-2 py-1 text-[10px] text-white">Primary</span>@endif</label>@empty<p class="col-span-full text-sm text-slate-500">No current images.</p>@endforelse</div>
<div class="mt-4"><label class="label">Add Images</label><input class="input" type="file" name="images[]" multiple accept="image/jpeg,image/png,image/webp">@error('images.*')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div></section>

<section class="card p-6"><div class="flex items-center justify-between"><div><h2 class="font-bold">Variants</h2><p class="text-xs text-slate-500">Edit SKU, price, and stock without replacing unchanged variants.</p></div></div>
<div class="mt-4 space-y-3">@forelse($product->variants as $index=>$variant)<div class="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-5"><input type="hidden" name="variants[{{ $index }}][id]" value="{{ $variant->id }}"><input class="input" name="variants[{{ $index }}][type]" value="{{ old("variants.$index.type",$variant->type) }}" placeholder="Type"><input class="input" name="variants[{{ $index }}][value]" value="{{ old("variants.$index.value",$variant->value) }}" placeholder="Value"><input class="input" name="variants[{{ $index }}][sku]" value="{{ old("variants.$index.sku",$variant->sku) }}" placeholder="SKU"><input class="input" type="number" step=".01" min="0" name="variants[{{ $index }}][price]" value="{{ old("variants.$index.price",$variant->price) }}" placeholder="Price"><input class="input" type="number" min="0" name="variants[{{ $index }}][stock]" value="{{ old("variants.$index.stock",$variant->stock) }}" placeholder="Stock"></div>@empty<p class="text-sm text-slate-500">This product has no variants. Basic edits will not create any.</p>@endforelse</div></section>
</div>
<aside><div class="card sticky top-20 p-5"><h2 class="font-bold">Publication</h2><p class="mt-2 text-sm text-slate-600">Current status: <strong>{{ $product->sellerStatus() }}</strong></p><p class="mt-1 text-xs text-slate-500">{{ $product->sellerVisibilityReason() }}</p><label class="mt-5 flex items-start gap-3 rounded-xl bg-slate-50 p-3"><input type="checkbox" name="is_active" value="1" class="mt-1" @checked(old('is_active',$product->publication_status==='published'))><span><strong class="block text-sm">Publish product</strong><span class="text-xs text-slate-500">The listing becomes visible only after moderation and marketplace checks pass.</span></span></label><button class="btn-primary mt-5 w-full">Save Changes</button><a href="{{ route('seller.products.index') }}" class="btn-ghost mt-2 w-full">Cancel</a></div></aside>
</form>
@endsection
