<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::table('stores', function(Blueprint $table){ $table->string('status')->default('active')->change(); $table->text('administrative_notes')->nullable(); $table->text('status_reason')->nullable(); });
        Schema::table('products', function(Blueprint $table){ $table->string('moderation_status')->default('clean')->after('is_active'); $table->text('suspension_reason')->nullable(); $table->index(['moderation_status','is_active']); });
        Schema::create('reports', function(Blueprint $table){ $table->id(); $table->string('report_number',30)->unique(); $table->foreignId('reporter_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('target_type'); $table->unsignedBigInteger('target_id'); $table->string('reason'); $table->text('description')->nullable(); $table->enum('priority',['low','normal','high','critical'])->default('normal'); $table->string('source')->default('user_report'); $table->enum('status',['open','under_review','resolved','dismissed','escalated'])->default('open'); $table->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('parent_report_id')->nullable()->constrained('reports')->nullOnDelete(); $table->unsignedInteger('related_count')->default(1); $table->timestamp('resolved_at')->nullable(); $table->timestamps(); $table->index(['target_type','target_id']); $table->index(['status','priority']); });
        Schema::create('report_evidence', function(Blueprint $table){ $table->id(); $table->foreignId('report_id')->constrained()->cascadeOnDelete(); $table->string('path'); $table->timestamps(); });
        Schema::create('report_notes', function(Blueprint $table){ $table->id(); $table->foreignId('report_id')->constrained()->cascadeOnDelete(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->text('note'); $table->boolean('is_super_admin')->default(false); $table->timestamps(); });
        Schema::create('report_actions', function(Blueprint $table){ $table->id(); $table->foreignId('report_id')->constrained()->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->string('action'); $table->text('reason')->nullable(); $table->json('metadata')->nullable(); $table->timestamps(); });
        Schema::create('moderation_scans', function(Blueprint $table){ $table->id(); $table->foreignId('product_id')->constrained()->cascadeOnDelete(); $table->foreignId('product_image_id')->constrained()->cascadeOnDelete(); $table->foreignId('seller_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('store_id')->nullable()->constrained()->nullOnDelete(); $table->string('provider')->default('local'); $table->string('provider_reference')->nullable(); $table->string('status')->default('pending_scan'); $table->string('detected_category')->nullable(); $table->decimal('confidence',5,4)->nullable(); $table->string('risk_level')->default('low'); $table->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamp('reviewed_at')->nullable(); $table->string('decision')->nullable(); $table->text('review_notes')->nullable(); $table->text('failure_message')->nullable(); $table->timestamps(); $table->index(['status','risk_level']); });
        Schema::create('violations', function(Blueprint $table){ $table->id(); $table->foreignId('seller_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('store_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('product_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('report_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('moderation_scan_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete(); $table->string('category'); $table->string('severity')->default('normal'); $table->text('description')->nullable(); $table->string('action_taken')->nullable(); $table->string('status')->default('confirmed'); $table->timestamps(); $table->index(['seller_id','status']); $table->index(['store_id','status']); });
    }
    public function down(): void { Schema::dropIfExists('violations'); Schema::dropIfExists('moderation_scans'); Schema::dropIfExists('report_actions'); Schema::dropIfExists('report_notes'); Schema::dropIfExists('report_evidence'); Schema::dropIfExists('reports'); Schema::table('products',fn(Blueprint $t)=>$t->dropColumn(['moderation_status','suspension_reason'])); Schema::table('stores',fn(Blueprint $t)=>$t->dropColumn(['administrative_notes','status_reason'])); }
};
