@extends('layouts.storefront')
@section('title','Seller Application')
@section('content')
<div class="mx-auto max-w-3xl px-4 py-10"><div class="card p-6 sm:p-8">
@if($application)
    @if($application->status==='pending')<h1 class="text-2xl font-black text-navy-900">Pending Admin review</h1><p class="mt-2 text-slate-500">Your Seller and Shop information is waiting for review.</p>
    @elseif($application->status==='rejected')<h1 class="text-2xl font-black text-rose-700">Your seller application was not approved</h1><p class="mt-2 text-slate-500">Reason: {{ $application->review_notes ?: 'Please review your documents and resubmit.' }}</p>
    @else<h1 class="text-2xl font-black text-leaf-600">Your SHOPPICK store is approved!</h1><a href="{{ route('seller.dashboard') }}" class="btn-primary mt-5">Open Seller Center</a>@endif
    <div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><b>{{ $application->store_name }}</b><p>Status: {{ str($application->status)->headline() }} · Submitted {{ $application->created_at->format('M d, Y') }}</p></div>
@else<h1 class="text-2xl font-black text-navy-900">Become a SHOPPICK Seller</h1><p class="mt-2 text-slate-500">Apply using your existing Buyer account. Your Buyer account remains active during review.</p>@endif
@if(!$application || $application->status==='rejected')
<form method="POST" action="{{ route('seller.apply.store') }}" enctype="multipart/form-data" class="mt-6 grid gap-4">@csrf
<div><label class="label">Business / Store Name *</label><input class="input" name="store_name" value="{{ old('store_name',$application?->store_name) }}" required></div><div><label class="label">Line of Business *</label><select class="input" name="category_id" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$application?->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="label">Description *</label><textarea class="input" name="store_description" required>{{ old('store_description',$application?->store_description) }}</textarea></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Contact Number *</label><input class="input" name="phone" value="{{ old('phone',auth()->user()->phone) }}" required></div><div><label class="label">Business Information</label><input class="input" name="business_information" value="{{ old('business_information',$application?->business_information) }}"></div></div><div><label class="label">Business Address *</label><textarea class="input" name="address" required>{{ old('address',$application?->address) }}</textarea></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Valid ID *</label><input type="file" name="valid_id" class="input" accept="image/jpeg,image/png,application/pdf" required></div><div><label class="label">Business Permit *</label><input type="file" name="business_permit" class="input" accept="image/jpeg,image/png,application/pdf" required></div><div><label class="label">Logo</label><input type="file" name="logo" class="input" accept="image/jpeg,image/png,image/webp"></div><div><label class="label">Banner</label><input type="file" name="banner" class="input" accept="image/jpeg,image/png,image/webp"></div></div><p class="text-xs text-slate-500">Identity and permit files are stored privately for authorized Admin review.</p><button class="btn-primary">{{ $application?'Resubmit Application':'Submit Application' }}</button></form>
@endif
</div></div>
@endsection
