@extends('layouts.storefront')
@section('title','Seller Application')
@section('content')
<div class="mx-auto max-w-3xl px-4 py-10"><div class="card p-6 sm:p-8">
@if($application)
    @if($application->status==='pending')<div class="text-center"><span class="text-5xl">🏪</span><h1 class="mt-4 text-2xl font-black text-navy-900">Pending Admin review.</h1><p class="mt-2 text-slate-500">An Admin will review your Seller and Shop information first.</p></div>
    @elseif(in_array($application->status,['escalated','awaiting_final_review'],true))<div class="text-center"><span class="text-5xl">🏪</span><h1 class="mt-4 text-2xl font-black text-navy-900">Additional review in progress.</h1><p class="mt-2 text-slate-500">Your application requires additional internal review.</p></div>
    @elseif($application->status==='rejected')<h1 class="text-2xl font-black text-rose-700">Your seller application was not approved.</h1><p class="mt-2 text-slate-500">You may update the information below and submit a new application.</p>
    @else<h1 class="text-2xl font-black text-leaf-600">Your SHOPPICK store is approved!</h1><a href="{{ route('seller.dashboard') }}" class="btn-primary mt-5">Open Seller Center</a>@endif
    <div class="mt-6 grid gap-3 rounded-xl bg-slate-50 p-5 sm:grid-cols-3"><div><p class="text-xs text-slate-400">Application Status</p><b class="capitalize">{{ str_replace('_',' ',$application->status) }}</b></div><div><p class="text-xs text-slate-400">Store</p><b>{{ $application->store_name }}</b></div><div><p class="text-xs text-slate-400">Submitted</p><b>{{ $application->created_at->format('M d, Y') }}</b></div>@if($application->review_notes)<p class="sm:col-span-3 text-sm text-slate-600"><strong>Final review note:</strong> {{ $application->review_notes }}</p>@endif</div>
@else<h1 class="text-2xl font-black text-navy-900">Become a SHOPPICK Seller</h1><p class="mt-2 text-slate-500">Apply using your existing Buyer account.</p>@endif

@if(!$application || $application->status==='rejected')<form method="POST" action="{{ route('seller.apply.store') }}" enctype="multipart/form-data" class="mt-6 grid gap-4">@csrf<div><label class="label">Store name</label><input class="input" name="store_name" value="{{ old('store_name',$application?->store_name) }}" required></div><div><label class="label">Description</label><textarea class="input" name="store_description">{{ old('store_description',$application?->store_description) }}</textarea></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Phone</label><input class="input" name="phone" value="{{ old('phone',auth()->user()->phone) }}" required></div><div><label class="label">Business information</label><input class="input" name="business_information" value="{{ old('business_information',$application?->business_information) }}"></div></div><div><label class="label">Address</label><textarea class="input" name="address" required>{{ old('address',$application?->address) }}</textarea></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Logo</label><input type="file" name="logo" class="input" accept="image/jpeg,image/png,image/webp"></div><div><label class="label">Banner</label><input type="file" name="banner" class="input" accept="image/jpeg,image/png,image/webp"></div></div><button class="btn-primary">{{ $application?'Resubmit Application':'Submit Application' }}</button></form>@endif
</div></div>
@endsection
