@extends('layouts.seller')
@section('title','Seller Dashboard')
@section('content')
<div class="seller-dashboard-heading flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-semibold text-brand-600">Seller Center</p><h1 class="text-2xl font-extrabold text-navy-900">Welcome back, {{ auth()->user()->name }}</h1><p class="mt-1 text-sm text-slate-500">Here is what is happening at {{ $store->name }}.</p></div><a href="{{ route('seller.products.create') }}" class="btn-primary"><x-seller.icon name="plus"/>Add Product</a></div>
<div class="seller-quick-actions mt-5 flex flex-wrap gap-3"><a href="{{ route('seller.products.create') }}" class="btn-primary btn-sm"><x-seller.icon name="plus"/>Add Product</a><a href="{{ route('seller.orders.index') }}" class="btn-outline btn-sm"><x-seller.icon name="orders"/>View Orders</a><a href="{{ route('seller.inventory.index') }}" class="btn-outline btn-sm"><x-seller.icon name="box"/>Update Stock</a><a href="{{ route('seller.marketing.index') }}" class="btn-outline btn-sm"><x-seller.icon name="ticket"/>Create Voucher</a></div>
<div class="seller-kpis mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
<x-admin.stat-card label="Today's Sales" :value="'₱'.number_format($stats['today_sales'],2)" color="bg-brand-50 text-brand-600" icon="M5 20V12H8V20M11 20V4H14V20M17 20V8H20V20"/>
<x-admin.stat-card label="New Orders" :value="$stats['new_orders']" color="bg-sun-50 text-sun-500" icon="M3 3H5L8 15H19L22 6H6M9 20h.01M18 20h.01"/>
<x-admin.stat-card label="Products" :value="$stats['products']" color="bg-sky-50 text-sky-600" icon="M20 7l-8-4-8 4v10l8 4 8-4V7ZM4 7l8 5 8-5M12 12v9M8 5l8 5"/>
<x-admin.stat-card label="Low Stock" :value="$stats['low_stock']" color="bg-rose-50 text-rose-600" icon="M12 9v2m0 4h.01M5.07 19h13.86c1.54 0 2.5-1.67 1.73-3L13.73 4c-.77-1.33-2.69-1.33-3.46 0L3.34 16c-.77 1.33.19 3 1.73 3z"/>
<x-admin.stat-card label="Total Earnings" :value="'₱'.number_format($stats['earnings'],2)" color="bg-leaf-50 text-leaf-500" icon="M8 3h8l-2 4h-4L8 3ZM10 7C3 12 3 21 12 21S21 12 14 7M15 12h-4a2 2 0 000 4h2a2 2 0 010 4M12 10v11"/>
</div>
<div class="card mt-6 p-5"><h2 class="font-bold text-navy-900">Sales · Last 7 Days</h2>@php($max=max(1,$salesChart->max('value'))) <div class="seller-sales-chart mt-5 flex h-28 items-end gap-3">@foreach($salesChart as $point)<div class="flex flex-1 flex-col items-center gap-2"><span class="text-xs text-slate-500">₱{{ number_format($point['value']) }}</span><div class="w-full max-w-12 rounded-t bg-brand-500" style="height:{{ max(4,($point['value']/$max)*105) }}px"></div><span class="text-xs text-slate-500">{{ $point['label'] }}</span></div>@endforeach</div></div>
<div class="card mt-6 p-5"><div class="flex items-center justify-between"><div><h2 class="seller-section-title font-bold text-navy-900"><x-seller.icon name="orders"/>Recent Orders</h2><p class="text-xs text-slate-500">Latest orders received by your store</p></div><a href="{{ route('seller.orders.index') }}" class="text-sm font-semibold text-brand-600">View all <x-seller.icon name="right"/></a></div><div class="mt-4 overflow-x-auto"><table class="seller-orders-table w-full min-w-[600px] text-left text-sm"><thead><tr class="border-b text-xs uppercase tracking-wide text-slate-400"><th class="py-3">Order</th><th>Buyer</th><th>Items</th><th>Status</th><th class="text-right">Total</th></tr></thead><tbody>@forelse($recentOrders as $order)<tr class="border-b border-slate-100"><td class="py-4 font-semibold text-navy-800">{{ $order->seller_order_number }}</td><td>{{ $order->order->buyer_name }}</td><td>{{ $order->items->count() }}</td><td><x-admin.status-badge :status="$order->status"/></td><td class="text-right font-bold">₱{{ number_format($order->subtotal,2) }}</td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-500">No orders yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="card p-5"><div class="flex justify-between"><h2 class="seller-section-title font-bold"><x-seller.icon name="box"/>Low Stock Products</h2><a href="{{ route('seller.inventory.index') }}" class="text-sm text-brand-600">Update stock <x-seller.icon name="right"/></a></div>@forelse($lowStockProducts as $product)<div class="flex justify-between border-t py-3 text-sm"><span>{{ $product->name }}</span><b class="text-rose-600">{{ $product->stock }} left</b></div>@empty<div class="seller-empty"><x-seller.icon name="box"/><p>Your stock levels look good.</p><span>No low stock products at the moment.</span></div>@endforelse</div><div class="card p-5"><div class="flex justify-between"><h2 class="seller-section-title font-bold"><x-seller.icon name="star"/>Recent Reviews</h2><a href="{{ route('seller.reviews.index') }}" class="text-sm text-brand-600">View reviews <x-seller.icon name="right"/></a></div>@forelse($recentReviews as $review)<div class="border-t py-3 text-sm"><div class="flex justify-between"><b>{{ $review->product->name }}</b><span class="text-sun-500">{{ str_repeat('★',$review->rating) }}</span></div><p class="mt-1 line-clamp-1 text-slate-500">{{ $review->comment ?: 'No written comment.' }}</p></div>@empty<div class="seller-empty"><x-seller.icon name="chat"/><p>Customer reviews will appear here.</p><span>Build trust with great service!</span></div>@endforelse</div></div>
@endsection
