@extends('layouts.seller')
@section('title','Seller Dashboard')
@section('content')
<div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-semibold text-brand-600">Seller Center</p><h1 class="text-2xl font-extrabold text-navy-900">Welcome back, {{ auth()->user()->name }}</h1><p class="mt-1 text-sm text-slate-500">Here is what is happening at {{ $store->name }}.</p></div><a href="{{ route('seller.products.create') }}" class="btn-primary">+ Add Product</a></div>
<div class="mt-5 flex flex-wrap gap-2"><a href="{{ route('seller.products.create') }}" class="btn-primary btn-sm">+ Add Product</a><a href="{{ route('seller.orders.index') }}" class="btn-outline btn-sm">View Orders</a><a href="{{ route('seller.inventory.index') }}" class="btn-outline btn-sm">Update Stock</a><a href="{{ route('seller.marketing.index') }}" class="btn-outline btn-sm">Create Voucher</a></div>
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
<x-admin.stat-card label="Today's Sales" :value="'₱'.number_format($stats['today_sales'],2)" color="bg-brand-50 text-brand-600" icon="M12 8v8m-4-4h8"/>
<x-admin.stat-card label="New Orders" :value="$stats['new_orders']" color="bg-sun-50 text-sun-500" icon="M12 8v4l3 3"/>
<x-admin.stat-card label="Products" :value="$stats['products']" color="bg-slate-100 text-navy-700" icon="M20 7l-8-4-8 4"/>
<x-admin.stat-card label="Low Stock" :value="$stats['low_stock']" color="bg-rose-50 text-rose-600" icon="M12 9v2m0 4h.01M5.07 19h13.86c1.54 0 2.5-1.67 1.73-3L13.73 4c-.77-1.33-2.69-1.33-3.46 0L3.34 16c-.77 1.33.19 3 1.73 3z"/>
<x-admin.stat-card label="Total Earnings" :value="'₱'.number_format($stats['earnings'],2)" color="bg-leaf-50 text-leaf-500" icon="M12 8v8m-4-4h8"/>
</div>
<div class="card mt-6 p-5"><h2 class="font-bold text-navy-900">Sales · Last 7 Days</h2>@php($max=max(1,$salesChart->max('value'))) <div class="mt-5 flex h-40 items-end gap-3">@foreach($salesChart as $point)<div class="flex flex-1 flex-col items-center gap-2"><span class="text-xs text-slate-500">₱{{ number_format($point['value']) }}</span><div class="w-full max-w-12 rounded-t bg-brand-500" style="height:{{ max(4,($point['value']/$max)*105) }}px"></div><span class="text-xs text-slate-500">{{ $point['label'] }}</span></div>@endforeach</div></div>
<div class="card mt-6 p-5"><div class="flex items-center justify-between"><div><h2 class="font-bold text-navy-900">Recent Orders</h2><p class="text-xs text-slate-500">Latest orders received by your store</p></div><a href="{{ route('seller.orders.index') }}" class="text-sm font-semibold text-brand-600">View all</a></div><div class="mt-4 overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><thead><tr class="border-b text-xs uppercase tracking-wide text-slate-400"><th class="py-3">Order</th><th>Buyer</th><th>Items</th><th>Status</th><th class="text-right">Total</th></tr></thead><tbody>@forelse($recentOrders as $order)<tr class="border-b border-slate-100"><td class="py-4 font-semibold text-navy-800">{{ $order->seller_order_number }}</td><td>{{ $order->order->buyer_name }}</td><td>{{ $order->items->count() }}</td><td><x-admin.status-badge :status="$order->status"/></td><td class="text-right font-bold">₱{{ number_format($order->subtotal,2) }}</td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-500">No orders yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="card p-5"><div class="flex justify-between"><h2 class="font-bold">Low Stock Products</h2><a href="{{ route('seller.inventory.index') }}" class="text-sm text-brand-600">Update stock</a></div>@forelse($lowStockProducts as $product)<div class="flex justify-between border-t py-3 text-sm"><span>{{ $product->name }}</span><b class="text-rose-600">{{ $product->stock }} left</b></div>@empty<p class="py-8 text-center text-sm text-slate-500">Your stock levels look good.</p>@endforelse</div><div class="card p-5"><div class="flex justify-between"><h2 class="font-bold">Recent Reviews</h2><a href="{{ route('seller.reviews.index') }}" class="text-sm text-brand-600">View reviews</a></div>@forelse($recentReviews as $review)<div class="border-t py-3 text-sm"><div class="flex justify-between"><b>{{ $review->product->name }}</b><span class="text-sun-500">{{ str_repeat('★',$review->rating) }}</span></div><p class="mt-1 line-clamp-1 text-slate-500">{{ $review->comment ?: 'No written comment.' }}</p></div>@empty<p class="py-8 text-center text-sm text-slate-500">Customer reviews will appear here.</p>@endforelse</div></div>
@endsection
