<?php
namespace App\Http\Controllers\Seller;
use App\Http\Controllers\Controller;
use App\Models\Voucher;
use Illuminate\Http\Request;
class MarketingController extends Controller {
 public function index(){ $store=auth()->user()->store;$vouchers=$store->vouchers()->where('source_type','shop')->withCount('usages')->with(['products','usages.order'])->latest()->paginate(15);$products=$store->products()->where('is_active',true)->orderBy('name')->get(['id','name']);return view('seller.marketing.index',compact('vouchers','products')); }
 public function store(Request $request){$data=$this->validated($request);$data['code']=strtoupper($data['code']);$data['status']=$request->input('status','active');$data['source_type']='shop';$data['platform_scope']='all_shops';$data['created_by']=$request->user()->id;$voucher=$request->user()->store->vouchers()->create($data);$this->syncProducts($voucher,$request);return back()->with('success','Shop Voucher created successfully.');}
 public function update(Request $request,Voucher $voucher){$this->own($voucher);$data=$this->validated($request,$voucher);$data['code']=strtoupper($data['code']);$voucher->update($data);$this->syncProducts($voucher,$request);return back()->with('success','Voucher updated successfully.');}
 public function toggle(Voucher $voucher){$this->own($voucher);$voucher->update(['status'=>$voucher->status==='active'?'inactive':'active']);return back()->with('success','Voucher status updated.');}
 private function validated(Request $request,?Voucher $voucher=null):array{$data=$request->validate(['code'=>['required','alpha_dash','max:30','unique:vouchers,code'.($voucher?','.$voucher->id:'')],'title'=>['required','string','max:120'],'description'=>['nullable','string','max:500'],'type'=>['required','in:percent,fixed,free_shipping'],'value'=>['nullable','numeric','min:0','required_unless:type,free_shipping'],'min_purchase'=>['nullable','numeric','min:0'],'max_discount'=>['nullable','numeric','min:0'],'usage_limit'=>['nullable','integer','min:1'],'per_user_limit'=>['required','integer','min:1'],'starts_at'=>['nullable','date'],'ends_at'=>['nullable','date','after_or_equal:starts_at'],'status'=>['nullable','in:active,inactive'],'application_scope'=>['required','in:entire_shop,selected_products'],'product_ids'=>['nullable','array','required_if:application_scope,selected_products'],'product_ids.*'=>['integer']]);if($data['type']==='percent'&&(float)$data['value']>100)throw \Illuminate\Validation\ValidationException::withMessages(['value'=>'Percentage discount may not exceed 100%.']);if($data['type']==='free_shipping')$data['value']=0;return $data;}
 private function syncProducts(Voucher $voucher,Request $request):void{$ids=$request->input('application_scope')==='selected_products'?$request->input('product_ids',[]):[];$valid=$request->user()->store->products()->whereIn('id',$ids)->pluck('id');$voucher->products()->sync($valid);}
 private function own(Voucher $voucher):void{abort_unless($voucher->source_type==='shop'&&$voucher->store_id===auth()->user()->store->id,403);}
}
