<?php

namespace App\Http\Controllers\Seller;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\AdminActivityLog;
use App\Models\Product;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    public function __construct(private ProductService $products) {}
    public function index(Request $request) { $query=auth()->user()->store->products()->with(['category','images','store']); if($request->q)$query->where('name','like','%'.$request->q.'%'); if($request->category)$query->where('category_id',$request->category); if($request->status==='active')$query->where('is_active',true); if($request->status==='draft')$query->where('publication_status','draft'); if($request->status==='low')$query->whereColumn('stock','<=','low_stock_threshold')->where('stock','>',0); if($request->status==='out')$query->where('stock',0); $products=$query->latest()->paginate(15)->withQueryString(); $categories=Category::active()->orderBy('sort_order')->orderBy('name')->get(); return view('seller.products.status-index',compact('products','categories')); }
    public function create() { $categories = Category::active()->orderBy('sort_order')->orderBy('name')->get(); return view('seller.products.create-form', compact('categories')); }
    public function store(Request $request) { $this->sellerCanManage($request); $data = $this->validateProduct($request); $publish=$request->input('publication_action','publish')==='publish'; $data['store_id'] = $request->user()->store->id; $data['publication_status'] = $publish ? 'published' : 'draft'; $data['is_active'] = $publish; $product=$this->products->create($data); return redirect()->route('seller.products.index')->with('success', $product->fresh()->is_active ? 'Product published successfully.' : ($publish ? 'Product saved and is under image review.' : 'Product saved as a draft.')); }
    public function edit(Request $request, Product $product) { $this->own($product); $this->sellerCanManage($request); $product->load(['images','variants','category','store']); $categories = Category::active()->orderBy('sort_order')->orderBy('name')->get(); return view('seller.products.edit-form', compact('product', 'categories')); }
    public function update(Request $request, Product $product) { $this->own($product); $this->sellerCanManage($request); $data = $this->validateProduct($request, $product); $before=$product->only(['name','price','stock','is_active','publication_status']); $data['store_id'] = $request->user()->store->id; $data['publication_status'] = $request->boolean('is_active') ? 'published' : 'draft'; $data['is_active'] = $request->boolean('is_active') && in_array($product->moderation_status, ['clean','approved']); $updated=$this->products->update($product, $data); AdminActivityLog::record('seller.product.updated','product',$product->id,['before'=>$before,'after'=>$updated->only(['name','price','stock','is_active','publication_status'])]); return redirect()->route('seller.products.index')->with('success', 'Product updated successfully.'); }
    public function destroy(Product $product) { $this->own($product); $product->update(['is_active'=>false,'publication_status'=>'draft']); $product->delete(); AdminActivityLog::record('seller.product.archived','product',$product->id,['name'=>$product->name]); return back()->with('success', 'Product archived.'); }
    public function showArchived(Product $product) { $this->ownArchived($product); $product->load(['category','images']); return view('seller.products.archived-show',compact('product')); }
    public function restore(Product $product) { $this->ownArchived($product); $product->restore(); $product->update(['is_active'=>false,'publication_status'=>'draft']); AdminActivityLog::record('seller.product.restored','product',$product->id,['name'=>$product->name]); return redirect()->route('seller.products.index',['status'=>'draft'])->with('success','Product restored as a draft. You may edit and publish it when ready.'); }
    public function forceDestroy(Product $product) { $this->ownArchived($product); if($product->orderItems()->exists()) return back()->with('error','This product has order history and cannot be permanently deleted.'); $paths=$product->images()->pluck('path')->filter()->all(); $id=$product->id; $name=$product->name; $product->forceDelete(); Storage::disk('public')->delete($paths); AdminActivityLog::record('seller.product.permanently_deleted','product',$id,['name'=>$name]); return redirect()->route('seller.products.index',['status'=>'archived'])->with('success','Product permanently deleted.'); }
    public function publication(Request $request, Product $product) { $this->own($product); $this->sellerCanManage($request); $data=$request->validate(['action'=>['required','in:activate,deactivate']]); if($data['action']==='deactivate'){ $product->update(['is_active'=>false,'publication_status'=>'draft']); AdminActivityLog::record('seller.product.deactivated','product',$product->id); return back()->with('success','Product deactivated successfully.'); } if(!in_array($product->moderation_status,['clean','approved'],true)) return back()->with('error',in_array($product->moderation_status,['pending_scan','scanning','flagged','under_review'])?'This product is currently under review.':'This product cannot be activated until moderation is approved.'); if($product->price<=0) return back()->with('error','Add a valid product price before activation.'); if($product->stock<=0) return back()->with('error','Add available stock before activation.'); $product->update(['is_active'=>true,'publication_status'=>'published']); AdminActivityLog::record('seller.product.activated','product',$product->id); return back()->with('success','Product activated successfully.'); }
    private function own(Product $product): void { abort_unless($product->store_id === auth()->user()->store?->id, 403, 'You do not have permission to edit this product.'); }
    private function ownArchived(Product $product): void { $this->own($product); abort_unless($product->trashed(),404); }
    private function sellerCanManage(Request $request): void { abort_unless($request->user()->sellerProfile?->status==='approved',403,'Your Seller account is currently suspended.'); abort_unless($request->user()->store?->status==='active',403,'Your shop is currently suspended or restricted.'); }
    private function validateProduct(Request $request, ?Product $product = null): array { return $request->validate([
        'name'=>['required','string','max:255'],'category_id'=>['required','exists:categories,id'],'description'=>['nullable','string'],
        'brand'=>['nullable','string','max:100'],'sku'=>['nullable','string','max:100','unique:products,sku,'.($product?->id ?? 'NULL')],
        'price'=>['required','numeric','min:0'],'discount'=>['nullable','numeric','between:0,100'],'stock'=>['required','integer','min:0'],
        'low_stock_threshold'=>['nullable','integer','min:0'],'is_active'=>['nullable','boolean'],'images'=>['nullable','array'],'images.*'=>['image','mimes:jpeg,png,jpg,webp','max:2048'],
        'remove_image_ids'=>['nullable','array'],'remove_image_ids.*'=>['integer'],
        'variants'=>['nullable','array'],'variants.*.id'=>['nullable','integer'],'variants.*.type'=>['required_with:variants','string','max:50'],'variants.*.value'=>['required_with:variants','string','max:100'],'variants.*.sku'=>['nullable','string','max:100'],'variants.*.price'=>['nullable','numeric','min:0'],'variants.*.stock'=>['required_with:variants','integer','min:0']]); }
}
