@extends('layouts.seller')
@section('title','Promotions & Vouchers')
@section('content')
<div><p class="text-sm font-semibold text-brand-600">Promotions</p><h1 class="text-2xl font-extrabold text-navy-900">My Vouchers</h1><p class="text-sm text-slate-500">Create shop discounts and seller-sponsored shipping offers.</p></div>
<div class="mt-6 grid gap-6 xl:grid-cols-[380px_1fr]">
<form method="POST" action="{{ route('seller.marketing.vouchers.store') }}" class="card h-fit space-y-4 p-5" x-data="{type:'fixed'}">@csrf
 <div><span class="badge bg-brand-50 text-brand-700">Shop Voucher</span><h2 class="mt-2 font-bold">Create Shop Voucher</h2><p class="text-xs text-slate-500">Applies only to {{ auth()->user()->store->name }}.</p></div>
 <div><label class="label">Voucher Name</label><input class="input" name="title" value="{{ old('title') }}" required></div>
 <div><label class="label">Voucher Code</label><input class="input uppercase" name="code" value="{{ old('code') }}" required></div>
 <div><label class="label">Voucher Type</label><select class="input" name="type" x-model="type"><option value="fixed">Fixed Amount Discount</option><option value="percent">Percentage Discount</option><option value="free_shipping">Free Shipping</option></select></div>
 <div class="grid grid-cols-2 gap-3"><div x-show="type!=='free_shipping'"><label class="label" x-text="type==='percent'?'Discount Percentage':'Discount Amount'"></label><input class="input" type="number" step=".01" min="0" name="value"></div><div><label class="label">Minimum Spend</label><input class="input" type="number" step=".01" min="0" name="min_purchase" value="0"></div></div>
 <div><label class="label" x-text="type==='free_shipping'?'Maximum Shipping Discount':'Maximum Discount (optional)'"></label><input class="input" type="number" step=".01" min="0" name="max_discount"><p x-show="type==='free_shipping'" class="mt-1 text-xs text-slate-400">The Buyer pays any shipping amount above this limit.</p></div>
 <div class="grid grid-cols-2 gap-3"><div><label class="label">Total Usage Limit</label><input class="input" type="number" min="1" name="usage_limit"></div><div><label class="label">Per Buyer</label><input class="input" type="number" min="1" name="per_user_limit" value="1" required></div></div>
 <div class="grid grid-cols-2 gap-3"><div><label class="label">Start Date</label><input class="input" type="datetime-local" name="starts_at"></div><div><label class="label">End Date</label><input class="input" type="datetime-local" name="ends_at"></div></div>
 <div><label class="label">Applies To</label><select class="input" name="application_scope"><option value="entire_shop">Entire Shop</option><option value="selected_products">Selected Products</option></select></div>
 <div><label class="label">Applicable Products</label><select class="input min-h-28" name="product_ids[]" multiple>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-400">Select products only when using Selected Products.</p></div>
 <div><label class="label">Status</label><select class="input" name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
 <button class="btn-primary w-full">Create Voucher</button>
</form>
<div class="space-y-3">
 @forelse($vouchers as $voucher)
 <article class="card p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex items-center gap-2"><b class="text-lg">{{ $voucher->code }}</b><x-admin.status-badge :status="$voucher->isActive()?'active':($voucher->ends_at?->isPast()?'expired':$voucher->status)"/></div><p class="font-semibold text-navy-800">{{ $voucher->title }}</p><p class="text-sm text-slate-500">{{ $voucher->type==='free_shipping'?'Free Shipping up to ₱'.number_format($voucher->max_discount??0,2):($voucher->type==='percent'?$voucher->value.'% OFF':'₱'.number_format($voucher->value,2).' OFF') }} · Min ₱{{ number_format($voucher->min_purchase,2) }}</p><p class="mt-1 text-xs text-slate-400">Used {{ $voucher->usages_count }}{{ $voucher->usage_limit?' / '.$voucher->usage_limit:'' }} · Per Buyer {{ $voucher->per_user_limit }}</p></div><div class="flex gap-2"><form method="POST" action="{{ route('seller.marketing.vouchers.toggle',$voucher) }}">@csrf<button class="btn-outline btn-sm">{{ $voucher->status==='active'?'Deactivate':'Activate' }}</button></form></div></div>
 <details class="mt-4 border-t pt-3"><summary class="cursor-pointer text-sm font-semibold text-brand-600">Edit / View Usage</summary><form method="POST" action="{{ route('seller.marketing.vouchers.update',$voucher) }}" class="mt-4 grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input class="input" name="title" value="{{ $voucher->title }}" required><input class="input uppercase" name="code" value="{{ $voucher->code }}" required><select class="input" name="type">@foreach(['fixed'=>'Fixed Amount','percent'=>'Percentage','free_shipping'=>'Free Shipping'] as $key=>$label)<option value="{{ $key }}" @selected($voucher->type===$key)>{{ $label }}</option>@endforeach</select><input class="input" type="number" step=".01" min="0" name="value" value="{{ $voucher->value }}"><input class="input" type="number" step=".01" min="0" name="min_purchase" value="{{ $voucher->min_purchase }}"><input class="input" type="number" step=".01" min="0" name="max_discount" value="{{ $voucher->max_discount }}"><input class="input" type="number" min="1" name="usage_limit" value="{{ $voucher->usage_limit }}"><input class="input" type="number" min="1" name="per_user_limit" value="{{ $voucher->per_user_limit }}" required><input class="input" type="datetime-local" name="starts_at" value="{{ $voucher->starts_at?->format('Y-m-d\TH:i') }}"><input class="input" type="datetime-local" name="ends_at" value="{{ $voucher->ends_at?->format('Y-m-d\TH:i') }}"><select class="input" name="application_scope"><option value="entire_shop" @selected($voucher->application_scope==='entire_shop')>Entire Shop</option><option value="selected_products" @selected($voucher->application_scope==='selected_products')>Selected Products</option></select><select class="input min-h-24" name="product_ids[]" multiple>@foreach($products as $product)<option value="{{ $product->id }}" @selected($voucher->products->contains('id',$product->id))>{{ $product->name }}</option>@endforeach</select><input type="hidden" name="status" value="{{ $voucher->status }}"><button class="btn-primary sm:col-span-2">Save Changes</button></form>
 <div class="mt-4"><p class="text-xs font-bold uppercase text-slate-400">Usage History</p>@forelse($voucher->usages->take(8) as $usage)<p class="mt-2 text-xs">Buyer #{{ $usage->user_id }} · {{ $usage->order?->order_number }} · ₱{{ number_format($usage->discount_amount+$usage->shipping_discount_amount,2) }} · {{ ($usage->used_at??$usage->created_at)->format('M d, Y') }}</p>@empty<p class="mt-2 text-xs text-slate-400">Not used yet.</p>@endforelse</div></details>
 </article>
 @empty<div class="card p-10 text-center"><p class="font-semibold">No vouchers</p><p class="text-sm text-slate-500">Create your first store voucher.</p></div>@endforelse
 {{ $vouchers->links() }}
</div></div>
@endsection
