@extends('layouts.admin')
@section('title','Moderation Review')
@section('content')
@php
    $detection=match($scan->status){'approved'=>'Safe','flagged'=>'Potential Policy Violation','pending_scan','under_review'=>'Uncertain','scan_failed'=>'Scan Failed','rejected'=>'Policy Violation Confirmed',default=>'Processing'};
    $canDecide=in_array($scan->status,['pending_scan','under_review','flagged','scan_failed'],true);
@endphp
<a href="{{ route('admin.moderation.index') }}" class="text-sm text-brand-600">← Moderation Queue</a>
<div class="mt-5 grid gap-6 lg:grid-cols-2">
    <div class="card p-5"><img src="{{ $scan->image->url }}" class="max-h-[520px] w-full rounded-xl object-contain" alt="Product image for {{ $scan->product->name }}"><h1 class="mt-5 text-xl font-bold">{{ $scan->product->name }}</h1><p class="text-sm text-slate-500">{{ $scan->store?->name }} · {{ $scan->seller?->name }}</p><p class="mt-4 text-sm">{{ $scan->product->description }}</p></div>
    <div class="space-y-6">
        <div class="card p-5"><div class="flex items-center justify-between gap-3"><h2 class="font-bold">Moderation Result</h2><x-admin.status-badge :status="$scan->status"/></div><p class="mt-4 text-lg font-bold text-navy-900">{{ $detection }}</p>@if($scan->confidence!==null)<p class="mt-2 text-2xl font-black">{{ number_format($scan->confidence*100,1) }}%</p><p class="text-xs text-slate-500">Provider confidence; not a final determination.</p>@endif<dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-slate-400">Priority</dt><dd>{{ ucfirst($scan->risk_level) }}</dd></div><div><dt class="text-slate-400">Review</dt><dd>{{ $scan->review_type==='automatic'?'Auto Approved':($scan->review_type==='manual'?'Admin Review':'Required') }}</dd></div>@if($scan->reviewer)<div><dt class="text-slate-400">Actor</dt><dd>{{ $scan->reviewer->name }}</dd></div>@elseif($scan->review_type==='automatic')<div><dt class="text-slate-400">Actor</dt><dd>System</dd></div>@endif</dl>@if($scan->rejection_reason)<div class="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><strong>Rejection reason:</strong> {{ $scan->rejection_reason }}</div>@endif</div>
        @if($scan->status==='scan_failed')<form method="POST" action="{{ route('admin.moderation.retry',$scan) }}" class="card p-5" data-confirm-title="Retry this image scan?" data-confirm-message="The product remains held until the scan succeeds or an Admin approves it." data-confirm-action="Retry Scan" data-confirm-type="warning">@csrf<h2 class="font-bold">Scan Failed</h2><p class="mt-2 text-sm text-slate-500">{{ $scan->failure_message ?: 'The provider could not complete this scan.' }}</p><button class="btn-outline mt-4">Retry Scan</button></form>@endif
        @if($canDecide)<div class="card p-5"><h2 class="font-bold">Admin Final Review</h2><p class="mt-1 text-sm text-slate-500">Approve a safe image or reject it with a clear reason. Automated flags never reject products permanently.</p><div class="mt-4 flex flex-wrap gap-3"><form method="POST" action="{{ route('admin.moderation.review',$scan) }}" data-confirm-title="Approve this product image?" data-confirm-message="The product becomes eligible for sale when its other marketplace requirements pass." data-confirm-action="Approve" data-confirm-type="success">@csrf<input type="hidden" name="decision" value="approved"><button class="btn-primary">Approve</button></form><form method="POST" action="{{ route('admin.moderation.review',$scan) }}" data-confirm-title="Reject this product image?" data-confirm-message="The seller can replace the image and submit it through moderation again." data-confirm-action="Reject Image" data-confirm-type="danger" data-confirm-reason="true">@csrf<input type="hidden" name="decision" value="rejected"><button class="btn-outline text-rose-600">Reject Image</button></form></div></div>@endif
    </div>
</div>
@endsection
