<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>SHOPPICK Seller Sales Report</title>@include('admin.shops.sales-report.styles')</head><body><main class="shop-sales-report-content">
<h1>SHOPPICK Seller Sales Report</h1><p><strong>Report Period:</strong> {{ $period }}<br>Generated: {{ $generated->format('M d, Y H:i') }} {{ config('app.timezone') }}</p>
<p>Filters: @foreach($filters['query'] as $key=>$value){{ ucfirst(str_replace('_',' ',$key)) }}: {{ $value }}@if(!$loop->last) · @endif @endforeach</p>
<h2>Marketplace Summary — {{ $summary['shops'] }} Matching Shops</h2><table><thead><tr><th>Total Sales</th><th>Total Orders</th><th>Units Sold</th><th>Average Order Value</th></tr></thead><tbody><tr><td>₱{{ number_format($summary['sales'],2) }}</td><td>{{ $summary['orders'] }}</td><td>{{ $summary['units'] }}</td><td>₱{{ number_format($summary['average'],2) }}</td></tr></tbody></table>
@if($filters['from'])<p>Previous period: {{ $filters['previousFrom']->format('M d, Y') }} – {{ $filters['previousTo']->format('M d, Y') }}</p>@endif
<h2>Sales by Shop</h2><table><thead><tr><th>Shop / Seller</th><th>Orders</th><th>Sales</th><th>Units</th><th>Avg Order</th><th>Performance</th><th>Sales Trend</th></tr></thead><tbody>@forelse($shops as $shop)<tr><td>{{ $shop->name }}<br>{{ $shop->seller_name ?? 'Unavailable seller' }}</td><td>{{ $shop->orders }}</td><td>₱{{ number_format($shop->sales,2) }}</td><td>{{ $shop->units }}</td><td>₱{{ number_format($shop->average,2) }}</td><td>{{ $shop->performance }}</td><td>@include('admin.sales-reports.trend')</td></tr>@empty<tr><td colspan="7">No shop sales match your current filters.</td></tr>@endforelse
<tr><td><strong>Totals</strong></td><td>{{ $summary['orders'] }}</td><td>₱{{ number_format($summary['sales'],2) }}</td><td>{{ $summary['units'] }}</td><td>₱{{ number_format($summary['average'],2) }}</td><td colspan="2">All matching shops</td></tr></tbody></table>
<p>Completed seller-order net sales only; completion dates define the reporting period. This export includes all matching shops, across every page.</p>
</main>@if(!$pdf)<script>window.addEventListener('load', () => window.print());</script>@endif</body></html>
