@extends('layouts.storefront')
@section('title',$shipment->shipment_number)
@section('content')
<div class="mx-auto max-w-3xl px-4 py-8"><a href="{{ route('rider.dashboard') }}" class="text-sm text-brand-600">← Rider Dashboard</a><div class="mt-4 flex justify-between"><h1 class="text-2xl font-black">{{ $shipment->shipment_number }}</h1><x-admin.status-badge :status="$shipment->status"/></div>
<div class="card mt-5 p-5"><p><b>Pickup:</b> {{ data_get($shipment->pickup_address,'address','Shop') }}</p><p><b>Delivery:</b> {{ collect($shipment->delivery_address)->filter()->implode(', ') }}</p><p><b>Vehicle:</b> {{ $shipment->vehicle?->code??'None' }}</p><form method="POST" action="{{ route('rider.shipments.status',$shipment) }}" class="mt-5 flex gap-2">@csrf<select class="input" name="status">@foreach(['out_for_delivery','delivery_attempted','delivered','exception'] as $status)<option value="{{ $status }}">{{ ucwords(str_replace('_',' ',$status)) }}</option>@endforeach</select><input class="input" name="note" placeholder="Optional note"><button class="btn-primary">Update</button></form></div>
@if($shipment->order->payment_method==='cod')
@php($codPayment=$shipment->order->payments()->where('method','cod')->latest('id')->first())
<section class="card mt-5 p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Payment Collection</p><div class="mt-3 grid gap-3 sm:grid-cols-3"><div><p class="text-xs text-slate-400">Method</p><b>Cash on Delivery</b></div><div><p class="text-xs text-slate-400">Amount to Collect</p><b>₱{{ number_format($shipment->order->total,2) }}</b></div><div><p class="text-xs text-slate-400">Status</p><span class="badge {{ in_array($codPayment?->status,['cod_collected','paid'],true)?'bg-brand-100 text-brand-700':'bg-sun-100 text-sun-600' }}">{{ $codPayment?->status==='paid'?'Paid':($codPayment?->status==='cod_collected'?'COD Collected':'Pending COD') }}</span></div></div>@if(in_array($shipment->status,['out_for_delivery','delivery_attempted'],true)&&!in_array($codPayment?->status,['cod_collected','paid'],true))<form method="POST" action="{{ route('rider.shipments.cod-collection',$shipment) }}" class="mt-4" data-confirm-title="Confirm COD Collection" data-confirm-message="Order {{ $shipment->order->order_number }} · ₱{{ number_format($shipment->order->total,2) }}. Confirm that the Cash on Delivery payment was received." data-confirm-action="Confirm Collection" data-confirm-type="success">@csrf<button class="btn-primary">Confirm COD Collected</button></form>@elseif($codPayment?->collected_at)<p class="mt-3 text-xs text-slate-500">Collected {{ $codPayment->collected_at->format('M d, Y · h:i A') }}</p>@endif</section>
@endif
<section class="card mt-5 p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-bold">Live Delivery Tracking</h2><p id="gps-status" class="text-sm text-slate-500">Tracking paused. Your location is sent only while you start tracking this active assignment.</p></div><div class="flex gap-2"><button id="start-tracking" type="button" class="btn-primary">Start Tracking</button><button id="stop-tracking" type="button" class="btn-outline" disabled>Stop</button></div></div></section>
<form method="POST" enctype="multipart/form-data" action="{{ route('rider.shipments.pod',$shipment) }}" class="card mt-5 space-y-3 p-5">@csrf<h2 class="font-bold">Proof of Delivery</h2><input class="input" name="recipient_name" required placeholder="Recipient name"><input class="input" type="file" name="photo" accept="image/*"><p class="text-xs text-slate-500">POD evidence is stored privately and requires authorized access.</p><textarea class="input" name="notes" placeholder="Delivery notes"></textarea><button class="btn-primary">Submit POD</button></form></div>
<x-admin.confirm-modal/>
@endsection
@push('scripts')<script>
document.addEventListener('DOMContentLoaded',()=>{const start=document.getElementById('start-tracking'),stop=document.getElementById('stop-tracking'),status=document.getElementById('gps-status');let timer=null,sending=false;const send=()=>{if(sending)return;if(!navigator.geolocation){status.textContent='Current location is unavailable.';return;}sending=true;navigator.geolocation.getCurrentPosition(async position=>{try{const response=await fetch(@js(route('rider.shipments.location',$shipment)),{method:'POST',credentials:'same-origin',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,heading:position.coords.heading,speed:position.coords.speed})});if(!response.ok)throw new Error((await response.json()).message||'Location update rejected.');status.textContent='Live · Last update '+new Date().toLocaleTimeString();}catch(error){status.textContent=error.message;}finally{sending=false;}},error=>{status.textContent=error.code===1?'Location permission is required for live delivery tracking.':'Current location is unavailable.';sending=false;},{enableHighAccuracy:true,maximumAge:10000,timeout:15000});};start.addEventListener('click',()=>{send();timer=setInterval(send,@js(max(10,config('logistics.tracking_interval_seconds'))*1000));start.disabled=true;stop.disabled=false;});stop.addEventListener('click',()=>{clearInterval(timer);timer=null;start.disabled=false;stop.disabled=true;status.textContent='Tracking paused.';});window.addEventListener('beforeunload',()=>clearInterval(timer));});
</script>@endpush
