<div class="report-header"><div><h2 class="report-section-title">{{ $dashboard?'Sales Performance':'Period Overview' }}</h2><p class="report-note">{{ $period }} @if($previous) · Previous: {{ $filters['previousFrom']->format('M d, Y') }} – {{ $filters['previousTo']->format('M d, Y') }} @endif</p></div>
@if(!$dashboard)@include('admin.sales-reports.ui.export',['exportRoute'=>'admin.analytics','exportParams'=>$filters['query']])@else<a class="text-brand-700 font-semibold" href="{{ route('admin.sales-reports.index',array_intersect_key($filters['query'],array_flip(['range','from','to']))) }}">View Sales Reports →</a>@endif</div>
@include('admin.sales-reports.ui.metrics')
<p class="report-note mt-3">@include('admin.sales-reports.ui.badge',['label'=>$performance]) · Completed seller orders, stored net totals, completion dates. @if(isset($filters['query']['category']))Category-filtered net sales are allocated by item value.@endif</p>
<div class="analytics-grid">@include('admin.analytics.chart')<section class="report-card analytics-diagnostics" tabindex="0" aria-label="{{ $dashboard?'Sales Insights':'Diagnostic Insights' }}"><h2 class="report-section-title">{{ $dashboard?'Sales Insights':'Diagnostic Insights' }}</h2>@foreach($insights as $insight)<div class="analytics-insight"><span class="analytics-priority {{ $insight['priority']==='Needs Attention'?'attention':($insight['priority']==='Watch'?'watch':'') }}">{{ $insight['priority'] }}</span><p>{{ $insight['text'] }}</p></div>@endforeach</section></div>
@if(!$dashboard)
<section class="report-card analytics-section"><div class="analytics-mini"><div><span class="report-note">Shops with Sales</span><strong>{{ $counts['selling'] }} <small class="report-note">/ {{ $counts['shops'] }}</small></strong><span class="report-note">Previous: {{ $previous?$counts['previous_selling']:'No comparison' }}</span></div><div><span class="report-note">Shops with No Sales</span><strong>{{ $counts['no_sales'] }}</strong></div><div><span class="report-note">Cancellation Rate</span><strong>{{ number_format($cancellations['rate'],1) }}%</strong><span class="report-note">Previous: {{ $previous?number_format($cancellations['previous_rate'],1).'%':'No comparison' }}</span></div><div><span class="report-note">Top 5 Shop Contribution</span><strong>{{ number_format($topFiveShare,1) }}%</strong></div></div><p class="report-note">Rates use the selected seller-order status scope. This is an order-status snapshot, not a conversion funnel.</p></section>
@endif
<div class="{{ $dashboard?'analytics-pair':'analytics-section' }}">
<section class="report-card"><div class="report-header"><h2 class="report-section-title">{{ $dashboard?'Top Shops':'Sales by Shop' }}</h2>@if(!$dashboard)<label class="report-note">Sort <select class="input" data-analytics-sort>@foreach(\App\Services\AdminSalesAnalyticsService::SORTS as $value=>$label)<option value="{{ $value }}" @selected(($filters['query']['sort']??'sales_desc')===$value)>{{ $label }}</option>@endforeach</select></label>@endif</div><div class="analytics-scroll"><table><thead><tr><th>Shop</th><th>Sales</th><th>Orders</th>@if(!$dashboard)<th>Units</th><th>Share</th>@endif<th>Trend</th></tr></thead><tbody>@forelse($shops as $row)<tr><td><strong>{{ $row->name }}</strong>@if(!$dashboard)<p class="report-note">{{ $row->seller_name }}</p>@endif</td><td class="analytics-money">₱{{ number_format($row->sales,2) }}</td><td>{{ $row->orders }}</td>@if(!$dashboard)<td>{{ $row->units }}</td><td>{{ number_format($row->share_percent,1) }}%<div class="analytics-bar"><span style="width:{{ min(100,max(0,$row->share_percent)) }}%"></span></div></td>@endif<td>@include('admin.analytics.trend')</td></tr>@empty<tr><td colspan="6" class="analytics-empty">No shops match the selected filters.</td></tr>@endforelse</tbody></table></div>@if(!$dashboard&&$shops instanceof \Illuminate\Contracts\Pagination\Paginator)<div class="mt-4" data-analytics-pagination>{{ $shops->links() }}</div>@endif</section>
@if(!$dashboard)<div class="analytics-pair">@endif
@if(!$dashboard)<section class="report-card"><h2 class="report-section-title">Sales by Category</h2><p class="report-note">Top 20 · Net totals allocated by item value. Category order counts overlap when an order has multiple categories.</p>@include('admin.analytics.breakdown',['rows'=>$categories,'kind'=>'category'])</section>@endif
<section class="report-card"><h2 class="report-section-title">Top Products</h2><p class="report-note">Top {{ $dashboard?5:10 }} by allocated net sales · Selected period</p>@include('admin.analytics.breakdown',['rows'=>$products,'kind'=>'product'])</section>
</div>@if(!$dashboard)</div>
<div class="analytics-pair"><section class="report-card"><h2 class="report-section-title">Order Status Analysis</h2><p class="report-note">Completed rows use completion dates; other statuses use placement dates. Changes describe current status snapshots.</p><div class="analytics-scroll"><table><thead><tr><th>Status</th><th>Orders</th><th>Share</th><th>Previous</th><th>Change</th></tr></thead><tbody>@foreach($statusRows as $row)@php($status=$row->status)@php($count=$row->orders)<tr><td>{{ ucwords(str_replace('_',' ',$status)) }}</td><td>{{ $count }}</td><td>{{ number_format($row->share_percent,1) }}%<div class="analytics-bar"><span style="width:{{ $row->share_percent }}%"></span></div></td><td>{{ $previous?($oldStatuses[$status]??0):'—' }}</td><td>{{ $row->change['difference']===null?'No comparison':sprintf('%+d',$row->change['difference']) }}</td></tr>@endforeach</tbody></table></div></section>
<section class="report-card"><h2 class="report-section-title">Cancellation Trend</h2><div class="analytics-mini"><div><span class="report-note">Current</span><strong>{{ $cancellations['current'] }}</strong></div><div><span class="report-note">Previous</span><strong>{{ $cancellations['previous']??'—' }}</strong></div><div><span class="report-note">Change</span><strong>{{ $previous?sprintf('%+d',$cancellations['current']-$cancellations['previous']):'—' }}</strong></div></div><p class="report-note">Cancelled seller orders do not contribute completed sales. A change in cancellations does not establish why sales changed.</p><h3 class="report-section-title mt-6">Period Comparison</h3><div class="analytics-scroll"><table><thead><tr><th>Metric</th><th>Previous</th><th>Difference</th><th>Change</th></tr></thead><tbody>@foreach(['sales'=>'Net Sales','orders'=>'Completed Orders','units'=>'Units','average'=>'Average Order Value'] as $key=>$label)<tr><td>{{ $label }}</td><td class="analytics-money">{{ $previous?(in_array($key,['sales','average'])?'₱'.number_format($previous[$key],2):number_format($previous[$key])):'—' }}</td><td class="analytics-money">{{ $previous?(in_array($key,['sales','average'])?'₱'.number_format($changes[$key]['difference'],2):sprintf('%+d',$changes[$key]['difference'])):'—' }}</td><td>@include('admin.sales-reports.ui.change',['change'=>$changes[$key]])</td></tr>@endforeach</tbody></table></div></section></div>
<div class="analytics-pair"><section class="report-card"><h2 class="report-section-title">Shops with No Sales</h2><p class="report-note">{{ $counts['no_sales'] }} shops · Up to 10 shown · No completed seller orders in selected scope.</p><div class="analytics-scroll"><table><thead><tr><th>Shop</th><th>Seller</th></tr></thead><tbody>@forelse($noSaleShops as $row)<tr><td>{{ $row->name }}</td><td>{{ $row->seller_name }}</td></tr>@empty<tr><td colspan="2" class="analytics-empty">All selected shops recorded completed sales.</td></tr>@endforelse</tbody></table></div></section>
<section class="report-card"><h2 class="report-section-title">Products with No Sales</h2><p class="report-note">{{ $noSaleProducts['count'] }} products · {{ $noSaleProducts['out_of_stock'] }} currently out of stock · Up to 10 shown. Current stock provides context.</p><div class="analytics-scroll"><table><thead><tr><th>Product</th><th>Shop</th><th>Current Stock</th></tr></thead><tbody>@forelse($noSaleProducts['rows'] as $row)<tr><td>{{ $row->name }}</td><td>{{ $row->store?->name }}</td><td>{{ $row->stock }}</td></tr>@empty<tr><td colspan="3" class="analytics-empty">No products without completed sales in this scope.</td></tr>@endforelse</tbody></table></div></section></div>
@endif
