<!doctype html><html lang="en"><head><meta charset="utf-8"><title>SHOPPICK Sales &amp; Marketplace Analytics</title><style>
@page{margin:30px 32px 45px}body{font-family:DejaVu Sans,Arial,sans-serif;font-size:10px;color:#24364a}h1{font-size:21px;color:#0f766e}h2{font-size:14px;margin-top:22px}p{line-height:1.6}table{width:100%;border-collapse:collapse;margin:8px 0}th,td{padding:7px 5px;border-bottom:1px solid #dce5e9;text-align:left}th{background:#eef7f6;font-size:9px}tr{page-break-inside:avoid}thead{display:table-header-group}.note{color:#64748b;font-size:9px}.toolbar{margin-bottom:15px}.money{white-space:nowrap}@media print{.toolbar{display:none}}.insight{margin:6px 0}
</style></head><body>
@if(!($pdf??false))<div class="toolbar"><button onclick="window.print()">Print Report</button></div>@endif
<h1>SHOPPICK</h1><h2>Sales &amp; Marketplace Analytics</h2><p>{{ $period }}<br>Generated: {{ $generated->format('M d, Y H:i') }} {{ config('app.timezone') }}</p>
<p class="note">@foreach($filters['query'] as $key=>$value){{ ucfirst($key) }}: {{ $value }} · @endforeach</p>
<p class="note">Completed seller orders; stored seller_total; completed_at. Category/product sales allocate stored net totals by item value (quantity/equal shares when all values are zero). Archived/suspended shops remain included; deleted shops follow Sales Reports exclusion. Completed status snapshots recognize stored net totals without independent payment/refund adjustments.</p>
<h2>Sales Performance · {{ $performance }}</h2><p class="note">@if($previous)Previous period: {{ $filters['previousFrom']->format('M d, Y') }} – {{ $filters['previousTo']->format('M d, Y') }}@else No comparable previous period.@endif</p>
<table><thead><tr><th>Metric</th><th>Current</th><th>Previous</th><th>Difference</th><th>Change</th></tr></thead><tbody>@foreach(['sales'=>'Total Sales','orders'=>'Completed Orders','units'=>'Units Sold','average'=>'Average Order Value'] as $key=>$label)<tr><td>{{ $label }}</td><td>{{ in_array($key,['sales','average'])?'₱'.number_format($summary[$key],2):number_format($summary[$key]) }}</td><td>{{ $previous?(in_array($key,['sales','average'])?'₱'.number_format($previous[$key],2):number_format($previous[$key])):'—' }}</td><td>{{ $previous?number_format($changes[$key]['difference'],2):'—' }}</td><td>{{ $changes[$key]['label'] }}</td></tr>@endforeach</tbody></table>
<p>Shops with sales: {{ $counts['selling'] }} / {{ $counts['shops'] }} · Shops with no sales: {{ $counts['no_sales'] }} · Top 5 contribution: {{ number_format($topFiveShare,1) }}%</p>
<h2>Diagnostic Insights</h2>@foreach($insights as $insight)<p class="insight"><strong>{{ $insight['priority'] }}</strong> · {{ $insight['text'] }}</p>@endforeach
@foreach(['shops'=>'Sales by Shop','categories'=>'Sales by Category','products'=>'Top 10 Products'] as $key=>$title)<h2>{{ $title }}</h2><table><thead><tr><th>Name</th><th>Sales</th><th>Orders</th><th>Units</th><th>Share</th><th>Previous Sales</th><th>Trend</th></tr></thead><tbody>@forelse($$key as $row)<tr><td>{{ $row->name }}@if($key==='products')<br><span class="note">{{ $row->shop_name }}</span>@endif</td><td class="money">₱{{ number_format($row->sales,2) }}</td><td>{{ $row->orders }}</td><td>{{ $row->units }}</td><td>{{ number_format($row->share_percent,1) }}%</td><td class="money">{{ $previous?'₱'.number_format($row->previous_sales,2):'—' }}</td><td>{{ $row->trend['label'] }}</td></tr>@empty<tr><td colspan="7">No qualifying sales.</td></tr>@endforelse</tbody></table>@endforeach
<p class="note">Category and product order counts are distinct within each group and can overlap across groups. Their attributed net sales reconcile to marketplace totals, including an unallocated category for missing items. Products are limited to top 10.</p>
<h2>Order Status Analysis</h2><table><thead><tr><th>Status</th><th>Orders</th><th>Share</th><th>Previous</th><th>Change</th></tr></thead><tbody>@foreach($statusRows as $row)@php($status=$row->status)@php($count=$row->orders)<tr><td>{{ ucwords(str_replace('_',' ',$status)) }}</td><td>{{ $count }}</td><td>{{ number_format($row->share_percent,1) }}%</td><td>{{ $previous?($oldStatuses[$status]??0):'—' }}</td><td>{{ $previous?sprintf('%+d',$count-($oldStatuses[$status]??0)):'—' }}</td></tr>@endforeach</tbody></table>
<h2>Cancellation Trend</h2><p>Current: {{ $cancellations['current'] }} · Previous: {{ $cancellations['previous']??'No comparison' }} · Change: {{ $previous?sprintf('%+d',$cancellations['current']-$cancellations['previous']):'No comparison' }}<br>Rate: {{ number_format($cancellations['rate'],1) }}% · Previous rate: {{ $previous?number_format($cancellations['previous_rate'],1).'%':'No comparison' }}</p>
<h2>No-Sales Diagnostics</h2><p>{{ $counts['no_sales'] }} shops and {{ $noSaleProducts['count'] }} products have no completed sales in the selected scope. {{ $noSaleProducts['out_of_stock'] }} of these products are currently out of stock.</p>
<p class="note">Order status counts use completion dates for completed orders and placement dates for other statuses. Inventory is a current snapshot. Observed changes do not establish causation. This report is read-only.</p>
</body></html>
