<?php
namespace App\Http\Controllers\Logistics;

use App\Http\Controllers\Controller;
use App\Models\{LogisticsHub,LogisticsInsight,LogisticsInvoice,LogisticsSetting,NotificationModel,ProofOfDelivery,RiderProfile,SellerOrder,Shipment,User,Vehicle};
use App\Services\{NotificationService,OrderProgressService,ShipmentService,ShipmentTrackingService};
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class LogisticsController extends Controller
{
    public function dashboard(){
        $counts=collect(Shipment::STATUSES)->mapWithKeys(fn($s)=>[$s=>Shipment::where('status',$s)->count()]);
        $stats=['ready'=>Shipment::where('status','ready_for_pickup')->count(),'pending'=>Shipment::whereNull('rider_id')->whereNotIn('status',['delivered'])->count(),'transit'=>Shipment::whereIn('status',['picked_up','at_hub','hub_transfer','in_transit','out_for_delivery'])->count(),'riders'=>RiderProfile::where('account_status','active')->where('availability','available')->count(),'vehicles'=>Vehicle::where('status','available')->count(),'exceptions'=>Shipment::where('status','exception')->count(),'delivered'=>Shipment::whereDate('delivered_at',today())->count(),'pod'=>ProofOfDelivery::where('status','pending')->count()];
        $today=Shipment::with(['store','rider','vehicle'])->whereDate('assigned_at',today())->latest()->limit(8)->get();
        $tracked=Shipment::with(['rider','vehicle','latestTrackingPoint'])->whereNotNull('rider_id')->whereNotIn('status',['delivered','ready_for_pickup'])->latest('updated_at')->limit(30)->get();
        $alerts=Shipment::with('store')->where(fn($q)=>$q->where('status','exception')->orWhere(fn($x)=>$x->whereNull('rider_id')->where('ready_at','<',now()->subHours(2)))->orWhere(fn($x)=>$x->whereNotNull('estimated_delivery_at')->where('estimated_delivery_at','<',now())->where('status','!=','delivered')))->latest()->limit(6)->get();
        $eligibleSellerOrders=SellerOrder::with(['order','store','items'])->where('status','ready_to_ship')->whereDoesntHave('shipment')->latest()->get();
        $unassignedLoads=Shipment::with('store')->whereNull('rider_id')->whereNotIn('status',['delivered'])->latest()->get();
        $availableRiders=User::whereHas('roles',fn($q)=>$q->where('slug','rider'))->where('is_active',true)->whereHas('riderProfile',fn($q)=>$q->where('account_status','active')->where('availability','available'))->orderBy('name')->get();
        $availableVehicles=Vehicle::where('status','available')->orderBy('code')->get();
        $invoiceEligibleLoads=Shipment::with(['store','sellerOrder','invoice'])->whereDoesntHave('invoice')->latest()->get();
        $routeLoads=Shipment::with(['rider','vehicle','currentHub'])->whereNotIn('status',['ready_for_pickup','delivered'])->latest()->get();
        return view('logistics.dashboard',compact('counts','stats','today','tracked','alerts','eligibleSellerOrders','unassignedLoads','availableRiders','availableVehicles','invoiceEligibleLoads','routeLoads'));
    }
    public function quickCreateLoad(Request $r,ShipmentService $service){$d=$r->validate(['seller_order_id'=>'required|exists:seller_orders,id']);$shipment=$service->createForSellerOrder(SellerOrder::findOrFail($d['seller_order_id']),$r->user());return redirect()->route('logistics.shipments.index',['view'=>$shipment->id])->with('success','Load created from the ready-to-ship Seller Order.');}
    public function quickInvoice(Request $r){$d=$r->validate(['shipment_id'=>'required|exists:shipments,id']);$invoice=DB::transaction(function()use($d){$load=Shipment::with('sellerOrder')->whereKey($d['shipment_id'])->lockForUpdate()->firstOrFail();return LogisticsInvoice::firstOrCreate(['shipment_id'=>$load->id],['invoice_number'=>LogisticsInvoice::number(),'delivery_fee'=>$load->sellerOrder->shipping_fee,'adjustments'=>0,'total'=>$load->sellerOrder->shipping_fee,'status'=>'issued','due_at'=>now()->addDays(30),'notes'=>'Generated from the existing Load delivery fee.']);});$message=$invoice->wasRecentlyCreated?'Logistics invoice generated.':'An invoice already exists for this Load.';return redirect()->route('logistics.billing',['view'=>$invoice->id])->with('success',$message);}
    protected function shipmentQuery(Request $r){return Shipment::with(['order','sellerOrder.items','store.user','rider','vehicle','proofOfDelivery'])->when($r->q,fn($q,$v)=>$q->where(fn($x)=>$x->where('shipment_number','like',"%$v%")->orWhereHas('order',fn($o)=>$o->where('order_number','like',"%$v%"))->orWhereHas('sellerOrder',fn($s)=>$s->where('seller_order_number','like',"%$v%"))->orWhereHas('store',fn($s)=>$s->where('name','like',"%$v%"))))->when($r->status,fn($q,$v)=>$q->where('status',$v))->when($r->rider_id,fn($q,$v)=>$q->where('rider_id',$v))->when($r->vehicle_id,fn($q,$v)=>$q->where('vehicle_id',$v));}
    public function shipments(Request $r){$shipments=$this->shipmentQuery($r)->when($r->shop_id,fn($q,$v)=>$q->where('store_id',$v))->when($r->date_from,fn($q,$v)=>$q->whereDate('created_at','>=',$v))->when($r->date_to,fn($q,$v)=>$q->whereDate('created_at','<=',$v))->latest()->paginate(20)->withQueryString();$riders=User::whereHas('roles',fn($q)=>$q->where('slug','rider'))->orderBy('name')->get();$vehicles=Vehicle::orderBy('code')->get();$shops=\App\Models\Store::orderBy('name')->get();$selected=$r->view?Shipment::with(['order.user','sellerOrder.items.product','store.user','rider.riderProfile','vehicle','currentHub','events.actor','assignments.rider','assignments.vehicle','proofOfDelivery','invoice'])->find($r->view):null;$hubs=LogisticsHub::where('status','active')->get();return view('logistics.shipments',compact('shipments','riders','vehicles','shops','selected','hubs'));}
    public function show(Shipment $shipment){$shipment->load(['order.user','sellerOrder.items.product','sellerOrder.items.variant','store.user','rider.riderProfile','vehicle','currentHub','events.actor.roles','assignments.rider','assignments.vehicle','proofOfDelivery','invoice']);$hubs=LogisticsHub::where('status','active')->get();return view('logistics.shipment-show',compact('shipment','hubs'));}
    public function dispatch(){ $shipments=Shipment::with(['store','rider','vehicle'])->latest()->get()->groupBy('status');$riders=User::whereHas('roles',fn($q)=>$q->where('slug','rider'))->whereHas('riderProfile',fn($q)=>$q->where('account_status','active')->where('availability','available'))->get();$vehicles=Vehicle::where('status','available')->get();return view('logistics.dispatch',compact('shipments','riders','vehicles')); }
    public function assign(Request $r,Shipment $shipment,ShipmentService $service){$d=$r->validate(['rider_id'=>'required|exists:users,id','vehicle_id'=>'nullable|exists:vehicles,id','reason'=>'nullable|string|max:500']);$service->assign($shipment,$r->user(),User::findOrFail($d['rider_id']),isset($d['vehicle_id'])?Vehicle::find($d['vehicle_id']):null,$d['reason']??null);return back()->with('success','Shipment assignment saved.');}
    public function status(Request $r,Shipment $shipment,ShipmentService $service){$d=$r->validate(['status'=>'required|in:'.implode(',',Shipment::STATUSES),'note'=>'nullable|string|max:500']);$service->transition($shipment,$r->user(),$d['status'],$d['note']??null);return back()->with('success','Shipment status updated.');}
    public function tracking(Request $r){$shipments=$this->shipmentQuery($r)->with('latestTrackingPoint')->where('status','!=','ready_for_pickup')->latest('updated_at')->paginate(20)->withQueryString();$selected=$r->shipment?Shipment::with(['rider','vehicle','latestTrackingPoint','events'])->find($r->shipment):$shipments->first();return view('logistics.tracking',compact('shipments','selected'));}
    public function trackingFeed(Shipment $shipment,ShipmentTrackingService $tracking){return response()->json($tracking->logisticsFeed($shipment));}
    public function trackingSimulate(Request $r,Shipment $shipment,ShipmentTrackingService $tracking){$d=$r->validate(['latitude'=>'required|numeric|between:-90,90','longitude'=>'required|numeric|between:-180,180']);$tracking->simulate($shipment,$d);return back()->with('success','GPS Simulation — Development Only point recorded.');}
    public function fleet(Request $r){$query=Vehicle::with(['hub','shipments.rider'])->when($r->q,fn($q,$v)=>$q->where(fn($x)=>$x->where('code','like',"%$v%")->orWhere('plate_number','like',"%$v%")->orWhere('make','like',"%$v%")->orWhere('model','like',"%$v%")))->when($r->type,fn($q,$v)=>$q->where('type',$v))->when($r->status,fn($q,$v)=>$q->where('status',$v))->when($r->hub_id,fn($q,$v)=>$q->where('hub_id',$v));$stats=['total'=>(clone $query)->count(),'available'=>(clone $query)->where('status','available')->count(),'in_use'=>(clone $query)->where('status','in_use')->count(),'maintenance'=>(clone $query)->where('status','maintenance')->count()];$vehicles=$query->latest()->paginate(20)->withQueryString();$selected=$r->view?Vehicle::with(['hub','shipments.rider','shipments.latestTrackingPoint'])->find($r->view):null;$hubs=LogisticsHub::where('status','active')->get();return view('logistics.fleet',compact('vehicles','hubs','stats','selected')); }
    public function vehicleStore(Request $r){Vehicle::create($r->validate(['code'=>'required|string|max:40|unique:vehicles','plate_number'=>'nullable|string|max:40|unique:vehicles','type'=>'required|in:motorcycle,scooter,tricycle,car,van,delivery_truck,other','make'=>'nullable|string|max:80','model'=>'nullable|string|max:80','year'=>'nullable|integer|min:1990|max:'.(now()->year+1),'capacity_kg'=>'nullable|numeric|min:0','hub_id'=>'nullable|exists:logistics_hubs,id','status'=>'required|in:available,in_use,maintenance,unavailable,retired','notes'=>'nullable|string|max:1000']));return back()->with('success','Vehicle saved.');}
    public function vehicleStatus(Request $r,Vehicle $vehicle){$d=$r->validate(['status'=>'required|in:available,maintenance,unavailable,retired','notes'=>'nullable|string|max:1000']);abort_if($vehicle->status==='in_use',422,'End the active shipment assignment first.');$vehicle->update($d);return back()->with('success','Vehicle status updated.');}
    public function riders(Request $r){$query=RiderProfile::with(['user','hub'])->when($r->q,fn($q,$v)=>$q->whereHas('user',fn($u)=>$u->where('name','like',"%$v%")->orWhere('email','like',"%$v%")))->when($r->account_status,fn($q,$v)=>$q->where('account_status',$v))->when($r->availability,fn($q,$v)=>$q->where('availability',$v))->when($r->hub_id,fn($q,$v)=>$q->where('hub_id',$v));$stats=['active'=>(clone $query)->where('account_status','active')->count(),'available'=>(clone $query)->where('availability','available')->count(),'delivery'=>(clone $query)->whereIn('availability',['assigned','on_delivery'])->count(),'unavailable'=>(clone $query)->whereIn('availability',['off_duty','unavailable'])->count(),'rating'=>round((float)(clone $query)->avg('rating'),1)];$riders=$query->latest()->paginate(20)->withQueryString();$selected=$r->view?RiderProfile::with(['user','hub'])->find($r->view):null;if($selected)$selectedShipments=Shipment::with(['store','vehicle'])->where('rider_id',$selected->user_id)->latest()->limit(10)->get();else $selectedShipments=collect();$hubs=LogisticsHub::where('status','active')->get();return view('logistics.riders',compact('riders','hubs','stats','selected','selectedShipments')); }
    public function riderStore(Request $r){$d=$r->validate(['name'=>'required|string|max:100','email'=>'required|email|unique:users','phone'=>'required|string|max:30','hub_id'=>'nullable|exists:logistics_hubs,id']);DB::transaction(function()use($d){$u=User::create(['name'=>$d['name'],'email'=>$d['email'],'phone'=>$d['phone'],'password'=>'password','is_active'=>true,'email_verified_at'=>now()]);$u->assignRole('rider');RiderProfile::create(['user_id'=>$u->id,'hub_id'=>$d['hub_id']??null]);});return back()->with('success','Rider account created.');}
    public function riderUpdate(Request $r,RiderProfile $rider){$rider->update($r->validate(['account_status'=>'required|in:active,inactive,suspended','availability'=>'required|in:available,assigned,on_delivery,off_duty,unavailable','hub_id'=>'nullable|exists:logistics_hubs,id','notes'=>'nullable|string|max:1000']));$rider->user->update(['is_active'=>$rider->account_status==='active']);return back()->with('success','Rider updated.');}
    public function hubs(Request $r){$query=LogisticsHub::withCount(['shipments','riders','vehicles'])->when($r->q,fn($q,$v)=>$q->where(fn($x)=>$x->where('name','like',"%$v%")->orWhere('code','like',"%$v%")->orWhere('address','like',"%$v%")))->when($r->status,fn($q,$v)=>$q->where('status',$v));$hubs=$query->latest()->get();$selected=$r->view?LogisticsHub::with(['shipments.store','riders.user','vehicles'])->withCount(['shipments','riders','vehicles'])->find($r->view):null;return view('logistics.hubs',compact('hubs','selected')); }
    public function hubStore(Request $r){LogisticsHub::create($r->validate(['code'=>'required|string|max:30|unique:logistics_hubs','name'=>'required|string|max:100','address'=>'required|string|max:500','capacity'=>'nullable|integer|min:1','status'=>'required|in:active,inactive,maintenance','notes'=>'nullable|string|max:1000']));return back()->with('success','Hub saved.');}
    public function hubMove(Request $r,Shipment $shipment,OrderProgressService $progress){$d=$r->validate(['hub_id'=>'required|exists:logistics_hubs,id','type'=>'required|in:inbound,transfer,outbound','note'=>'nullable|string|max:500']);DB::transaction(function()use($r,$shipment,$d,$progress){$shipment=Shipment::whereKey($shipment->id)->lockForUpdate()->firstOrFail();DB::table('hub_movements')->insert(['shipment_id'=>$shipment->id,'from_hub_id'=>$shipment->current_hub_id,'to_hub_id'=>$d['hub_id'],'recorded_by'=>$r->user()->id,'type'=>$d['type'],'note'=>$d['note']??null,'moved_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);$shipment->update(['current_hub_id'=>$d['hub_id'],'status'=>$d['type']==='outbound'?'in_transit':'at_hub']);$shipment->events()->create(['actor_id'=>$r->user()->id,'status'=>$shipment->status,'location'=>LogisticsHub::find($d['hub_id'])->name,'note'=>$d['note']??ucfirst($d['type']).' Hub movement']);$progress->syncShipment($shipment);});return back()->with('success','Hub movement recorded.');}
    public function pod(Request $r){$query=ProofOfDelivery::with(['shipment.store','shipment.rider','submitter'])->when($r->q,fn($q,$v)=>$q->whereHas('shipment',fn($s)=>$s->where('shipment_number','like',"%$v%")->orWhereHas('store',fn($x)=>$x->where('name','like',"%$v%"))))->when($r->status,fn($q,$v)=>$q->where('status',$v));$summary=['pending'=>(clone $query)->where('status','pending')->count(),'approved'=>(clone $query)->where('status','approved')->count(),'rejected'=>(clone $query)->where('status','rejected')->count(),'total'=>(clone $query)->count()];$pods=$query->latest()->paginate(20)->withQueryString();$selected=$r->view?ProofOfDelivery::with(['shipment.store','shipment.rider','submitter'])->find($r->view):null;return view('logistics.pod',compact('pods','summary','selected')); }
    public function podReview(Request $r,ProofOfDelivery $pod){$d=$r->validate(['status'=>'required|in:approved,rejected','review_notes'=>'nullable|required_if:status,rejected|string|max:1000']);abort_unless($pod->status==='pending',422);$pod->update(['status'=>$d['status'],'review_notes'=>$d['review_notes']??null,'reviewed_by'=>$r->user()->id,'reviewed_at'=>now()]);NotificationService::send($pod->submitted_by,'Proof of Delivery '.$d['status'].'.',$d['status']==='rejected'?'Reason: '.$d['review_notes']:'Your POD was approved.','logistics',route('rider.shipments.show',$pod->shipment_id),['pod_id'=>$pod->id],'package');return back()->with('success','POD review saved.');}
    public function podFile(ProofOfDelivery $pod){abort_unless($pod->photo_path&&Storage::disk('local')->exists($pod->photo_path),404);return Storage::disk('local')->download($pod->photo_path);}
    public function billing(Request $r){$query=LogisticsInvoice::with(['shipment.order','shipment.store'])->when($r->q,fn($q,$v)=>$q->where('invoice_number','like',"%$v%")->orWhereHas('shipment',fn($s)=>$s->where('shipment_number','like',"%$v%")->orWhereHas('store',fn($x)=>$x->where('name','like',"%$v%"))))->when($r->status,fn($q,$v)=>$q->where('status',$v));$summary=['outstanding'=>(clone $query)->whereNotIn('status',['paid','void'])->sum('total'),'paid'=>(clone $query)->where('status','paid')->sum('total'),'pending'=>(clone $query)->whereIn('status',['draft','issued'])->sum('total'),'overdue'=>(clone $query)->where('status','overdue')->sum('total')];$invoices=$query->latest()->paginate(20)->withQueryString();$selected=$r->view?LogisticsInvoice::with(['shipment.order','shipment.store'])->find($r->view):null;return view('logistics.billing',compact('invoices','summary','selected')); }
    public function billingUpdate(Request $r,LogisticsInvoice $invoice){$d=$r->validate(['adjustments'=>'required|numeric|min:-999999|max:999999','status'=>'required|in:draft,issued,paid,overdue,void','notes'=>'nullable|string|max:1000']);$invoice->update(['adjustments'=>$d['adjustments'],'total'=>$invoice->delivery_fee+$d['adjustments'],'status'=>$d['status'],'notes'=>$d['notes']??null,'paid_at'=>$d['status']==='paid'?now():null]);return back()->with('success','Logistics invoice updated without changing the Buyer Order total.');}
    public function reports(Request $r){
        $r->validate(['date_from'=>'nullable|date','date_to'=>'nullable|date|after_or_equal:date_from','rider_id'=>'nullable|exists:users,id','shop_id'=>'nullable|exists:stores,id']);$from=$r->date_from?\Carbon\Carbon::parse($r->date_from)->startOfDay():now()->subDays(29)->startOfDay();$to=$r->date_to?\Carbon\Carbon::parse($r->date_to)->endOfDay():now()->endOfDay();if($from->diffInDays($to)>366)$from=$to->copy()->subDays(366)->startOfDay();
        $base=Shipment::query()->whereBetween('created_at',[$from,$to])->when($r->rider_id,fn($q,$v)=>$q->where('rider_id',$v))->when($r->shop_id,fn($q,$v)=>$q->where('store_id',$v));
        $shipments=(clone $base)->with(['rider','store','invoice'])->get();$delivered=$shipments->where('status','delivered');$eligible=$delivered->filter(fn($s)=>$s->estimated_delivery_at);$onTime=$eligible->filter(fn($s)=>$s->delivered_at->lte($s->estimated_delivery_at));
        $invoices=LogisticsInvoice::whereIn('shipment_id',$shipments->pluck('id'))->get();
        $data=['total'=>$shipments->count(),'delivered'=>$delivered->count(),'exceptions'=>$shipments->where('status','exception')->count(),'revenue'=>$invoices->sum('total'),'outstanding'=>$invoices->whereNotIn('status',['paid','void'])->sum('total'),'on_time_rate'=>$eligible->count()?round($onTime->count()/$eligible->count()*100,1):null,'eligible'=>$eligible->count(),'delayed'=>$eligible->count()-$onTime->count()];
        $days=collect(range(0,(int)$from->diffInDays($to)))->map(fn($n)=>$from->copy()->addDays($n));
        $charts=['labels'=>$days->map->format('M d'),'on_time'=>$days->map(fn($d)=>$eligible->filter(fn($s)=>$s->delivered_at->isSameDay($d))->pipe(fn($set)=>$set->count()?round($set->filter(fn($s)=>$s->delivered_at->lte($s->estimated_delivery_at))->count()/$set->count()*100,1):0)),'revenue'=>$days->map(fn($d)=>$invoices->filter(fn($i)=>$i->created_at->isSameDay($d))->sum('total'))];
        $lanes=$shipments->groupBy(fn($s)=>(data_get($s->pickup_address,'address','Shop')).' → '.(data_get($s->delivery_address,'city','Destination')))->map(fn($set)=>$set->where('status','exception')->count())->sortDesc()->take(8);
        $riderPerformance=$delivered->whereNotNull('rider_id')->groupBy('rider_id')->map(fn($set)=>['name'=>$set->first()->rider?->name??'Rider','delivered'=>$set->count(),'on_time'=>$set->filter(fn($s)=>$s->estimated_delivery_at&&$s->delivered_at->lte($s->estimated_delivery_at))->count()]);
        $aging=['Current'=>0,'1–30'=>0,'31–60'=>0,'61–90'=>0,'90+'=>0];foreach($invoices->whereNotIn('status',['paid','void']) as $i){$age=$i->created_at->diffInDays(now());$aging[$age<=0?'Current':($age<=30?'1–30':($age<=60?'31–60':($age<=90?'61–90':'90+')))] += $i->total;}
        $charts+=['lane_labels'=>$lanes->keys()->values(),'lane_delays'=>$lanes->values(),'rider_labels'=>$riderPerformance->pluck('name'),'rider_deliveries'=>$riderPerformance->pluck('delivered'),'rider_on_time'=>$riderPerformance->map(fn($x)=>$x['delivered']?round($x['on_time']/$x['delivered']*100,1):0)->values(),'aging_labels'=>collect($aging)->keys(),'aging_values'=>collect($aging)->values(),'accessorial_labels'=>['Approved Adjustments'],'accessorial_values'=>[$invoices->where('adjustments','>',0)->sum('adjustments')]];
        $riders=User::whereHas('roles',fn($q)=>$q->where('slug','rider'))->get();$shops=\App\Models\Store::orderBy('name')->get();
        $reportRows=$shipments->sortByDesc('created_at')->take(50);
        return view('logistics.reports',compact('data','charts','riders','shops','from','to','reportRows'));
    }
    public function ai(){ $insights=LogisticsInsight::latest()->paginate(20);return view('logistics.ai',compact('insights')); }
    public function analyze(){foreach(Shipment::whereNull('rider_id')->where('ready_at','<',now()->subHours(4))->get() as $s)LogisticsInsight::firstOrCreate(['type'=>'delay_risk','target_type'=>Shipment::class,'target_id'=>$s->id,'status'=>'generated'],['severity'=>'warning','title'=>'Shipment awaiting assignment','explanation'=>"{$s->shipment_number} has remained unassigned for more than four hours."]);return back()->with('success','Rule-based analysis completed using current shipment data.');}
    public function insight(Request $r,LogisticsInsight $insight){$d=$r->validate(['status'=>'required|in:viewed,accepted,dismissed,resolved']);$insight->update(['status'=>$d['status'],'acted_by'=>$r->user()->id,'acted_at'=>now()]);return back()->with('success','Insight decision recorded.');}
    public function notifications(Request $r){$items=$r->user()->notificationsData()->latest()->paginate(20);return view('logistics.notifications',compact('items'));}
    public function openNotification(Request $r,NotificationModel $notification){abort_unless($notification->user_id===$r->user()->id,404);$notification->markAsRead();return redirect($notification->link?:route('logistics.notifications'));}
    public function readAllNotifications(Request $r){$r->user()->notificationsData()->unread()->update(['read_at'=>now()]);return back()->with('success','Notifications marked as read.');}
    public function settings(){ $settings=LogisticsSetting::pluck('value','key');$hubs=LogisticsHub::where('status','active')->get();return view('logistics.settings',compact('settings','hubs')); }
    public function settingsUpdate(Request $r){$booleans=['require_pod','require_pod_review','pod_photo_required','recipient_name_required','enable_live_tracking','buyer_tracking_visibility','eta_updates','route_deviation_alerts','notify_ready_pickup','notify_unassigned','notify_pickup_delay','notify_delivery_delay','notify_exception','notify_failed_delivery','notify_vehicle_maintenance','notify_hub_alert','notify_pod','notify_billing','notify_critical_ai','ai_rider_vehicle','ai_delay_risk','ai_cost_leak','ai_billing_anomaly','ai_explainability','ai_override_tracking'];$rules=['default_hub_id'=>'nullable|exists:logistics_hubs,id','tracking_interval_seconds'=>'required|integer|min:10|max:300'];foreach($booleans as $key)$rules[$key]='required|boolean';$d=$r->validate($rules);foreach($d as $k=>$v)LogisticsSetting::updateOrCreate(['key'=>$k],['value'=>['value'=>$v],'updated_by'=>$r->user()->id]);return back()->with('success','Logistics settings saved.');}
}
