@extends('layouts.logistics')
@section('title','Logistics Dashboard')
@push('head')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">@endpush
@section('content')
<div class="log-page-head"><div><h1>Logistics Dashboard</h1><p>Live delivery operations from SHOPPICK Seller Orders.</p></div><a href="{{ route('logistics.dispatch') }}" class="btn-primary btn-sm">Open Dispatch Board</a></div>
<div class="log-kpis">@foreach(['Ready for Pickup'=>$stats['ready'],'Pending Dispatch'=>$stats['pending'],'In Transit'=>$stats['transit'],'Available Riders'=>$stats['riders'],'Available Vehicles'=>$stats['vehicles'],'Exceptions'=>$stats['exceptions']] as $label=>$value)<div class="log-kpi"><b>{{ $value }}</b><p>{{ $label }}</p></div>@endforeach</div>
<div class="mt-4 grid gap-4 xl:grid-cols-[minmax(0,2fr)_340px]"><section class="log-card overflow-hidden"><div class="flex items-center justify-between border-b p-4"><h2 class="text-sm font-extrabold">Live Operations</h2><a href="{{ route('logistics.tracking') }}" class="text-xs font-semibold text-brand-600">View tracking</a></div><div id="dashboard-map" class="h-[430px] bg-slate-100"></div><div class="grid grid-cols-3 border-t p-3 text-center text-xs"><div><b>{{ $tracked->count() }}</b><p class="text-slate-400">Active routes</p></div><div><b>{{ $stats['riders'] }}</b><p class="text-slate-400">Riders available</p></div><div><b>{{ $stats['vehicles'] }}</b><p class="text-slate-400">Vehicles available</p></div></div></section><section class="log-card"><div class="border-b p-4"><h2 class="text-sm font-extrabold">Today's Dispatch</h2></div>@forelse($today as $s)<a href="{{ route('logistics.shipments.index',['view'=>$s->id]) }}" class="block border-b p-4 text-xs hover:bg-slate-50"><div class="flex justify-between gap-2"><b>{{ $s->shipment_number }}</b><x-admin.status-badge :status="$s->status"/></div><p class="mt-1 text-slate-500">{{ $s->store?->name }}</p><p class="text-slate-400">{{ $s->rider?->name??'Unassigned' }} · {{ $s->vehicle?->code??'No vehicle' }}</p></a>@empty<div class="log-empty">No Loads scheduled for dispatch today.</div>@endforelse</section></div>
<div class="mt-4 grid gap-4 xl:grid-cols-2"><section class="log-card p-4"><h2 class="text-sm font-extrabold">Alerts & Exceptions</h2>@forelse($alerts as $s)<a href="{{ route('logistics.shipments.index',['view'=>$s->id]) }}" class="mt-3 block rounded-lg border-l-4 {{ $s->status==='exception'?'border-rose-500 bg-rose-50':'border-orange-400 bg-orange-50' }} p-3 text-xs"><b>{{ $s->status==='exception'?'Delivery Exception':'Operational Delay' }}</b><p>{{ $s->shipment_number }} · {{ $s->store?->name }}</p></a>@empty<p class="log-empty">No current operational alerts.</p>@endforelse</section>
<section class="log-card p-4"><h2 class="text-sm font-extrabold">Quick Actions</h2><div class="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
@if(auth()->user()->hasPermissionTo('manage_shipments'))<button type="button" data-open-quick="create-load" class="quick-action bg-brand-500 hover:bg-brand-600 focus:ring-brand-300"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg><span>Create Load</span></button>@endif
@if(auth()->user()->hasPermissionTo('assign_shipments'))<button type="button" data-open-quick="assign-rider" class="quick-action bg-green-600 hover:bg-green-700 focus:ring-green-300"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3.5 19c.6-3.4 2.4-5 5.5-5s4.9 1.6 5.5 5M16 11h5m-2.5-2.5v5"/></svg><span>Assign Rider</span></button>@endif
@if(auth()->user()->hasPermissionTo('manage_logistics_billing'))<button type="button" data-open-quick="generate-invoice" class="quick-action bg-navy-800 hover:bg-navy-900 focus:ring-navy-300"><svg viewBox="0 0 24 24"><path d="M6 3h9l3 3v15H6zM9 11h6M9 15h6M9 7h3"/></svg><span>Generate Invoice</span></button>@endif
@if(auth()->user()->hasPermissionTo('view_shipments'))<button type="button" data-open-quick="plan-route" class="quick-action bg-orange-500 hover:bg-orange-600 focus:ring-orange-300"><svg viewBox="0 0 24 24"><circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M7.5 16.5 16.5 7.5M7 6h4l2 2"/></svg><span>Plan Route</span></button>@endif
</div></section></div>

@if(auth()->user()->hasPermissionTo('manage_shipments'))<div data-quick-modal="create-load" class="quick-modal hidden"><form method="POST" action="{{ route('logistics.quick.create-load') }}" class="quick-modal-panel">@csrf<div class="quick-modal-head"><div><h3>Create Load</h3><p>Select a ready-to-ship Seller Order without an existing Load.</p></div><button type="button" data-close-quick aria-label="Close">×</button></div><label class="quick-field">Eligible Order<select name="seller_order_id" required data-create-order><option value="">Select Ready-to-Ship Order</option>@foreach($eligibleSellerOrders as $so)<option value="{{ $so->id }}" data-shop="{{ $so->store?->name }}" data-pickup="{{ $so->store?->location?:'Not provided' }}" data-delivery="{{ collect($so->order?->shipping_address)->filter()->implode(', ') }}" data-items="{{ $so->items->sum('quantity') }} item(s)">{{ $so->seller_order_number }} · {{ $so->store?->name }}</option>@endforeach</select></label><div class="quick-summary" data-create-summary><p>Select an eligible Order to preview its Shop, addresses, and items.</p></div>@if($eligibleSellerOrders->isEmpty())<p class="quick-empty">No eligible ready-to-ship Seller Orders.</p>@endif<div class="quick-modal-actions"><button type="button" data-close-quick class="btn-outline">Cancel</button><button class="btn-primary" @disabled($eligibleSellerOrders->isEmpty())>Create Load</button></div></form></div>@endif

@if(auth()->user()->hasPermissionTo('assign_shipments'))<div data-quick-modal="assign-rider" class="quick-modal hidden"><form method="POST" data-assignment-form data-action-template="{{ url('/logistics/shipments/__LOAD__/assign') }}" class="quick-modal-panel">@csrf<div class="quick-modal-head"><div><h3>Assign Rider</h3><p>Only eligible Riders and Vehicles are listed.</p></div><button type="button" data-close-quick aria-label="Close">×</button></div><label class="quick-field">Load / Order<select name="load_id" required data-assignment-load><option value="">Select unassigned Load</option>@foreach($unassignedLoads as $load)<option value="{{ $load->id }}">{{ $load->shipment_number }} · {{ $load->store?->name }}</option>@endforeach</select></label><label class="quick-field">Rider<select name="rider_id" required><option value="">Select available Rider</option>@foreach($availableRiders as $rider)<option value="{{ $rider->id }}">{{ $rider->name }}</option>@endforeach</select></label><label class="quick-field">Vehicle<select name="vehicle_id"><option value="">No Vehicle</option>@foreach($availableVehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->code }} · {{ ucwords(str_replace('_',' ',$vehicle->type)) }}</option>@endforeach</select></label><div class="quick-modal-actions"><button type="button" data-close-quick class="btn-outline">Cancel</button><button class="btn-primary" @disabled($unassignedLoads->isEmpty()||$availableRiders->isEmpty())>Assign Rider</button></div></form></div>@endif

@if(auth()->user()->hasPermissionTo('manage_logistics_billing'))<div data-quick-modal="generate-invoice" class="quick-modal hidden"><form method="POST" action="{{ route('logistics.quick.invoice') }}" class="quick-modal-panel">@csrf<div class="quick-modal-head"><div><h3>Generate Logistics Invoice</h3><p>Only the existing Load delivery fee is invoiced.</p></div><button type="button" data-close-quick aria-label="Close">×</button></div><label class="quick-field">Load<select name="shipment_id" required data-invoice-load><option value="">Select eligible Load</option>@foreach($invoiceEligibleLoads as $load)<option value="{{ $load->id }}" data-shop="{{ $load->store?->name }}" data-fee="{{ (float)$load->sellerOrder->shipping_fee }}">{{ $load->shipment_number }} · {{ $load->store?->name }}</option>@endforeach</select></label><div class="quick-summary" data-invoice-summary><p>Select a Load to preview the delivery fee.</p></div><div class="quick-modal-actions"><button type="button" data-close-quick class="btn-outline">Cancel</button><button class="btn-primary" @disabled($invoiceEligibleLoads->isEmpty())>Generate Invoice</button></div></form></div>@endif

@if(auth()->user()->hasPermissionTo('view_shipments'))<div data-quick-modal="plan-route" class="quick-modal hidden"><form method="GET" action="{{ route('logistics.tracking') }}" class="quick-modal-panel"><div class="quick-modal-head"><div><h3>Plan Route</h3><p>Open the existing Routes & Tracking workspace.</p></div><button type="button" data-close-quick aria-label="Close">×</button></div><label class="quick-field">Load<select name="shipment" required data-route-load><option value="">Select active Load</option>@foreach($routeLoads as $load)<option value="{{ $load->id }}" data-rider="{{ $load->rider?->name??'Unassigned' }}" data-vehicle="{{ $load->vehicle?->code??'—' }}" data-pickup="{{ data_get($load->pickup_address,'address','Not provided') }}" data-hub="{{ $load->currentHub?->name??'Direct delivery' }}" data-destination="{{ collect($load->delivery_address)->filter()->implode(', ') }}">{{ $load->shipment_number }}</option>@endforeach</select></label><div class="quick-summary" data-route-summary><p>Select a Load to preview its route details.</p></div>@unless(filled(config('logistics.routing_provider'))&&filled(config('logistics.routing_api_key')))<div class="rounded-lg border border-orange-200 bg-orange-50 p-3 text-xs text-orange-800">Routing provider is not configured. @if(auth()->user()->hasPermissionTo('manage_logistics_settings'))<a class="font-bold underline" href="{{ route('logistics.settings') }}">Open Settings</a>@endif</div>@endunless<div class="quick-modal-actions"><button type="button" data-close-quick class="btn-outline">Cancel</button><button class="btn-primary" @disabled($routeLoads->isEmpty())>Open Route Planner</button></div></form></div>@endif
@endsection
@push('scripts')<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{if(typeof L!=='undefined'){const map=L.map('dashboard-map').setView([12.8797,121.774],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);const points=@json($tracked->map(fn($s)=>$s->latestTrackingPoint?['lat'=>(float)$s->latestTrackingPoint->latitude,'lng'=>(float)$s->latestTrackingPoint->longitude,'label'=>$s->shipment_number.' · '.($s->rider?->name??'Rider')]:null)->filter()->values());if(!points.length)document.getElementById('dashboard-map').insertAdjacentHTML('beforeend','<div class="relative z-[500] m-4 rounded-lg bg-white/90 p-3 text-xs shadow">No active deliveries currently being tracked.</div>');else{const bounds=[];points.forEach(p=>{L.marker([p.lat,p.lng]).addTo(map).bindPopup(p.label);bounds.push([p.lat,p.lng]);});map.fitBounds(bounds,{padding:[40,40],maxZoom:13});}}
const close=m=>{m.classList.add('hidden');document.body.classList.remove('overflow-hidden')};document.querySelectorAll('[data-open-quick]').forEach(b=>b.addEventListener('click',()=>{const m=document.querySelector(`[data-quick-modal="${b.dataset.openQuick}"]`);if(m){m.classList.remove('hidden');document.body.classList.add('overflow-hidden');m.querySelector('select,button,input')?.focus();}}));document.querySelectorAll('[data-close-quick]').forEach(b=>b.addEventListener('click',()=>close(b.closest('[data-quick-modal]'))));document.querySelectorAll('[data-quick-modal]').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)close(m)}));
const summary=(select,target,render)=>select?.addEventListener('change',()=>{const o=select.selectedOptions[0];target.innerHTML=o?.value?render(o.dataset):'<p>Select an option to preview details.</p>'});summary(document.querySelector('[data-create-order]'),document.querySelector('[data-create-summary]'),d=>`<dl><div><dt>Shop</dt><dd>${d.shop}</dd></div><div><dt>Pickup</dt><dd>${d.pickup}</dd></div><div><dt>Delivery</dt><dd>${d.delivery}</dd></div><div><dt>Items</dt><dd>${d.items}</dd></div></dl>`);summary(document.querySelector('[data-invoice-load]'),document.querySelector('[data-invoice-summary]'),d=>`<dl><div><dt>Shop</dt><dd>${d.shop}</dd></div><div><dt>Delivery Fee</dt><dd>₱${Number(d.fee).toFixed(2)}</dd></div><div><dt>Additional Charges</dt><dd>₱0.00</dd></div><div><dt>Total</dt><dd>₱${Number(d.fee).toFixed(2)}</dd></div></dl>`);summary(document.querySelector('[data-route-load]'),document.querySelector('[data-route-summary]'),d=>`<dl><div><dt>Rider / Vehicle</dt><dd>${d.rider} · ${d.vehicle}</dd></div><div><dt>Pickup</dt><dd>${d.pickup}</dd></div><div><dt>Hub</dt><dd>${d.hub}</dd></div><div><dt>Destination</dt><dd>${d.destination}</dd></div></dl>`);const assignment=document.querySelector('[data-assignment-form]');assignment?.addEventListener('submit',e=>{const id=assignment.querySelector('[data-assignment-load]').value;if(!id){e.preventDefault();return;}assignment.action=assignment.dataset.actionTemplate.replace('__LOAD__',id)});
});</script>@endpush
