@extends('layouts.logistics')
@section('title','Delivery Assignment')
@section('content')
<div class="log-page-head"><div><h1>Delivery Assignment</h1><p>Assign only available Delivery Riders configured for each parcel area.</p></div></div>
<details class="log-card mt-4 p-5"><summary class="cursor-pointer font-semibold">Configure Rider Delivery Areas</summary><div class="mt-4 grid gap-4 md:grid-cols-2">@foreach($riderProfiles as $profile)<form method="POST" action="{{ route('logistics.riders.areas',$profile) }}" class="rounded-lg border p-4">@csrf @method('PUT')<b>{{ $profile->user?->name }}</b><div class="mt-2 flex flex-wrap gap-3">@foreach($areas as $area)<label class="text-sm"><input type="checkbox" name="delivery_area_ids[]" value="{{ $area->id }}" @checked($profile->deliveryAreas->contains($area))> {{ $area->name }}</label>@endforeach</div><button class="btn-outline btn-sm mt-3">Save Areas</button></form>@endforeach</div></details>
<div class="log-card mt-4 overflow-x-auto"><table class="log-table min-w-[850px]"><thead><tr><th>Parcel</th><th>Delivery Area</th><th>Buyer</th><th>Status</th><th>Delivery Rider</th></tr></thead><tbody>
@forelse($shipments as $shipment)<tr><td><b>{{ $shipment->parcel_code ?: $shipment->shipment_number }}</b><small>{{ $shipment->store?->name }}</small></td><td>{{ $shipment->deliveryArea?->name ?: '—' }}</td><td>{{ $shipment->order?->user?->name }}</td><td><span class="status-pill">{{ str($shipment->status)->headline() }}</span></td><td>@if($shipment->rider){{ $shipment->rider->name }}@else<form method="POST" action="{{ route('logistics.delivery.assign',$shipment) }}" class="flex gap-2">@csrf<select name="rider_id" required><option value="">Area Rider</option>@foreach(($areas->firstWhere('id',$shipment->delivery_area_id)?->riders ?? collect())->filter(fn($p)=>$p->account_status==='active'&&$p->availability==='available'&&$p->user?->is_active) as $profile)<option value="{{ $profile->user_id }}">{{ $profile->user->name }}</option>@endforeach</select><button class="btn-primary">Assign</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="text-center">No sorted parcels awaiting assignment.</td></tr>@endforelse
</tbody></table></div>{{ $shipments->links() }}
@endsection
