@extends('layouts.logistics')
@section('title','Pickup Requests')
@section('content')
<div class="log-page-head"><div><h1>Pickup Requests</h1><p>Assign a Pickup Rider to parcels prepared by Sellers.</p></div></div>
<form class="log-filters" method="GET"><input class="input flex-1" name="q" value="{{ request('q') }}" placeholder="Parcel code, shipment, or shop"><button class="btn-outline">Search</button></form>
<div class="log-card mt-4 overflow-x-auto"><table class="log-table min-w-[1100px]"><thead><tr><th>Parcel / Order</th><th>Seller / Pickup</th><th>Buyer Destination</th><th>Items</th><th>Ready Time</th><th>Status</th><th>Pickup Rider / Action</th></tr></thead><tbody>
@forelse($shipments as $shipment)<tr><td><b>{{ $shipment->parcel_code ?: $shipment->shipment_number }}</b><small>{{ $shipment->order?->order_number }}</small></td><td>{{ $shipment->store?->name }}<small>{{ data_get($shipment->pickup_address,'address','—') }}</small></td><td>{{ collect($shipment->delivery_address)->filter()->implode(', ') }}</td><td>{{ $shipment->sellerOrder?->items?->sum('quantity') ?: 0 }}</td><td>{{ $shipment->ready_at?->format('M d, g:i A') }}</td><td><x-admin.status-badge :status="$shipment->status"/></td><td>@if($shipment->pickupRider){{ $shipment->pickupRider->name }}<small>{{ $shipment->pickupRider->riderProfile?->vehicle_type }} {{ $shipment->pickupRider->riderProfile?->plate_number }}</small>@else<form method="POST" action="{{ route('logistics.pickup.assign',$shipment) }}" class="flex gap-2">@csrf<select class="input" name="rider_id" required><option value="">Available Rider</option>@foreach($riders as $rider)<option value="{{ $rider->id }}">{{ $rider->name }} · {{ $rider->riderProfile?->vehicle_type }} {{ $rider->riderProfile?->plate_number }}</option>@endforeach</select><button class="btn-primary">Assign</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="text-center">No Pickup Requests found.</td></tr>@endforelse
</tbody></table></div>{{ $shipments->links() }}
@endsection
