@extends('layouts.logistics')
@section('title','Logistics Reports')
@section('content')
<div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-2xl font-black">Logistics Reports</h1><p class="text-sm text-slate-500">Operational and financial performance from real delivery records.</p></div><button type="button" onclick="window.print()" class="btn-outline">Export / Print</button></div>
<form class="card mt-5 grid gap-3 p-4 md:grid-cols-5"><input class="input" type="date" name="date_from" value="{{ $from->toDateString() }}"><input class="input" type="date" name="date_to" value="{{ $to->toDateString() }}"><select class="input" name="rider_id"><option value="">All Riders</option>@foreach($riders as $rider)<option value="{{ $rider->id }}" @selected(request('rider_id')==$rider->id)>{{ $rider->name }}</option>@endforeach</select><select class="input" name="shop_id"><option value="">All Shops</option>@foreach($shops as $shop)<option value="{{ $shop->id }}" @selected(request('shop_id')==$shop->id)>{{ $shop->name }}</option>@endforeach</select><button class="btn-primary">Apply Filters</button></form>
<div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">@foreach(['Orders / Loads'=>$data['total'],'Delivered'=>$data['delivered'],'On-Time Rate'=>$data['on_time_rate']===null?'No eligible data':$data['on_time_rate'].'%','Revenue'=>'₱'.number_format($data['revenue'],2),'Outstanding'=>'₱'.number_format($data['outstanding'],2)] as $label=>$value)<div class="card p-4"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-1 text-xl font-black">{{ $value }}</p></div>@endforeach</div>
<div class="mt-6 grid gap-4 xl:grid-cols-3">
@foreach([['On-Time Performance','onTimeChart','Line: estimated versus actual delivery eligibility.'],['Delays by Lane','laneChart','Exception counts by real pickup and destination lane.'],['Rider Performance','riderChart','Completed deliveries and eligible on-time rate.'],['Revenue Trends','revenueChart','Logistics invoice totals only.'],['Accessorials','accessorialChart','Approved positive invoice adjustments.'],['AR Aging','agingChart','Outstanding Logistics invoices by age.']] as [$title,$id,$description])<section class="log-card p-4"><div class="flex justify-between"><h2 class="text-sm font-bold">{{ $title }}</h2><span class="text-[10px] text-slate-400">{{ $from->format('M d') }}–{{ $to->format('M d') }}</span></div><p class="text-[10px] text-slate-500">{{ $description }}</p><div class="mt-3 h-52"><canvas id="{{ $id }}"></canvas></div><a href="{{ request()->fullUrlWithQuery(['report'=>$id]) }}" class="mt-3 block text-right text-xs font-bold text-brand-600">View Details</a></section>@endforeach
<section class="card p-5 xl:col-span-2"><h2 class="font-bold">Margin Analysis</h2><div class="flex h-40 items-center justify-center text-slate-500">Insufficient cost data. Revenue is available, but SHOPPICK does not yet record verified Logistics operating costs.</div></section>
</div>
@if(request('report'))<aside class="log-drawer !w-[min(720px,100vw)]"><div class="log-drawer-head"><h2 class="font-extrabold">Detailed Logistics Report</h2><a href="{{ route('logistics.reports',request()->except('report')) }}">×</a></div><section class="log-drawer-section"><div class="grid grid-cols-3 gap-3 text-center"><div class="log-kpi"><b>{{ $data['total'] }}</b><p>Records</p></div><div class="log-kpi"><b>{{ $data['on_time_rate']===null?'—':$data['on_time_rate'].'%' }}</b><p>On-Time</p></div><div class="log-kpi"><b>{{ $data['exceptions'] }}</b><p>Exceptions</p></div></div></section><section class="log-drawer-section"><h3>Detailed Data</h3><div class="overflow-x-auto"><table class="log-table"><thead><tr><th>Date</th><th>Shipment</th><th>Rider</th><th>Status</th><th>ETA</th></tr></thead><tbody>@forelse($reportRows as $row)<tr><td>{{ $row->created_at->format('M d, Y') }}</td><td>{{ $row->shipment_number }}</td><td>{{ $row->rider?->name??'Unassigned' }}</td><td>{{ ucwords(str_replace('_',' ',$row->status)) }}</td><td>{{ $row->estimated_delivery_at?->format('M d H:i')??'Not Available' }}</td></tr>@empty<tr><td colspan="5" class="log-empty">No records for this period.</td></tr>@endforelse</tbody></table></div></section><button type="button" onclick="window.print()" class="btn-primary">Export / Print Current Report</button></aside>@endif
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{const teal='#0d9488',orange='#f59e0b',navy='#172554',green='#16a34a',red='#dc2626';const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'},tooltip:{enabled:true}},scales:{y:{beginAtZero:true}}};
new Chart(document.getElementById('onTimeChart'),{type:'line',data:{labels:@json($charts['labels']),datasets:[{label:'On-Time %',data:@json($charts['on_time']),borderColor:teal,backgroundColor:'#ccfbf1',fill:true,tension:.3}]},options:base});
new Chart(document.getElementById('laneChart'),{type:'bar',data:{labels:@json($charts['lane_labels']),datasets:[{label:'Delay / Exception Count',data:@json($charts['lane_delays']),backgroundColor:orange}]},options:base});
new Chart(document.getElementById('riderChart'),{data:{labels:@json($charts['rider_labels']),datasets:[{type:'bar',label:'Delivered',data:@json($charts['rider_deliveries']),backgroundColor:teal},{type:'line',label:'On-Time %',data:@json($charts['rider_on_time']),borderColor:orange}]},options:base});
new Chart(document.getElementById('revenueChart'),{type:'line',data:{labels:@json($charts['labels']),datasets:[{label:'Revenue (PHP)',data:@json($charts['revenue']),borderColor:green,backgroundColor:'#dcfce7',fill:true,tension:.3}]},options:base});
new Chart(document.getElementById('accessorialChart'),{type:'bar',data:{labels:@json($charts['accessorial_labels']),datasets:[{label:'Approved Amount (PHP)',data:@json($charts['accessorial_values']),backgroundColor:navy}]},options:base});
new Chart(document.getElementById('agingChart'),{type:'doughnut',data:{labels:@json($charts['aging_labels']),datasets:[{data:@json($charts['aging_values']),backgroundColor:[teal,green,orange,red,navy]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'},tooltip:{enabled:true}}}});
});</script>@endpush
