@extends('layouts.logistics')
@section('title','Settings')
@section('content')
@php($enabled=fn($key,$default=false)=>(bool)data_get($settings->get($key),'value',$default))
@php($value=fn($key,$default)=>data_get($settings->get($key),'value',$default))
<div class="log-page-head"><div><h1>Settings</h1><p>Status notifications, operational thresholds, POD, and rule-based automation.</p></div><button form="settings-form" class="btn-primary btn-sm">Save All Changes</button></div>
<form id="settings-form" method="POST" action="{{ route('logistics.settings.update') }}" class="mt-5 space-y-4">@csrf @method('PUT')
<section class="log-card p-5"><h2 class="text-sm font-extrabold">Logistics Operations</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-xs font-semibold">Default Hub<select class="input mt-2" name="default_hub_id"><option value="">No default Hub</option>@foreach($hubs as $hub)<option value="{{ $hub->id }}" @selected($value('default_hub_id',null)==$hub->id)>{{ $hub->name }}</option>@endforeach</select></label><div class="rounded-lg border p-3 text-xs"><b>Status-based monitoring</b><p class="mt-1 text-slate-500">Delivery visibility comes from recorded status, Hub, exception, and POD events. No GPS or map provider is required.</p></div></div></section>
<section class="log-card p-5"><h2 class="text-sm font-extrabold">Operational Thresholds</h2><div class="mt-4 grid gap-3 md:grid-cols-3"><label class="text-xs font-semibold">Maximum Pickup Wait (hours)<input class="input mt-2" type="number" name="pickup_wait_hours" min="1" max="168" value="{{ $value('pickup_wait_hours',config('logistics.pickup_wait_hours')) }}"></label><label class="text-xs font-semibold">Maximum Hub Dwell (hours)<input class="input mt-2" type="number" name="hub_dwell_hours" min="1" max="168" value="{{ $value('hub_dwell_hours',config('logistics.hub_dwell_hours')) }}"></label><label class="text-xs font-semibold">Delivery Delay Threshold (hours)<input class="input mt-2" type="number" name="delivery_delay_hours" min="1" max="720" value="{{ $value('delivery_delay_hours',config('logistics.delivery_delay_hours')) }}"></label></div></section>
@php($sections=['Notifications & Alerts'=>['delivery_status_notifications'=>'Delivery Status Notifications','notify_ready_pickup'=>'Ready for Pickup','notify_unassigned'=>'Unassigned Shipment','notify_pickup_delay'=>'Pickup Delay','notify_delivery_delay'=>'Delivery Delay','notify_exception'=>'Delivery Exception','notify_failed_delivery'=>'Failed Delivery','notify_vehicle_maintenance'=>'Vehicle Maintenance','notify_hub_alert'=>'Hub Alert','notify_pod'=>'POD Updates','notify_billing'=>'Billing Issue','notify_critical_ai'=>'Critical AI Insight'],'Buyer Tracking'=>['buyer_tracking_visibility'=>'Show Delivery Status Timeline to Buyer'],'AI & Automation Controls'=>['ai_rider_vehicle'=>'Rider–Vehicle Suggestions','ai_delay_risk'=>'Status Delay Risk Detection','ai_cost_leak'=>'Cost Leak Detection','ai_billing_anomaly'=>'Billing Anomaly Detection','ai_explainability'=>'AI Explainability','ai_override_tracking'=>'Decision / Override Audit'],'Proof of Delivery'=>['require_pod'=>'Proof of Delivery Required','pod_photo_required'=>'Photo Required','recipient_name_required'=>'Recipient Name Required','require_pod_review'=>'Logistics Review Required']])
@foreach($sections as $title=>$items)<section class="log-card p-5"><h2 class="text-sm font-extrabold">{{ $title }}</h2><div class="mt-4 grid gap-2 md:grid-cols-2">@foreach($items as $key=>$label)<label class="flex items-center justify-between rounded-lg border p-3 text-xs"><span>{{ $label }}</span><span><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked($enabled($key,in_array($key,['delivery_status_notifications','buyer_tracking_visibility','require_pod','require_pod_review','ai_explainability','ai_override_tracking'],true)))></span></label>@endforeach</div></section>@endforeach
<section class="log-card p-5"><h2 class="text-sm font-extrabold">System Integrations</h2><div class="mt-4 grid gap-3 md:grid-cols-3"><div class="rounded-lg border p-3 text-xs"><b>Status Events</b><p class="mt-1 text-green-700">Connected</p></div><div class="rounded-lg border p-3 text-xs"><b>Rule-based Operations</b><p class="mt-1 text-green-700">Connected</p></div><div class="rounded-lg border p-3 text-xs"><b>Private POD Storage</b><p class="mt-1 text-green-700">Connected</p></div></div></section>
</form>
@endsection
