@extends('layouts.logistics')
@section('title','Orders / Loads')
@section('content')
<div class="log-page-head"><div><h1>Orders / Loads</h1><p>Order is the Buyer purchase; Load is one Seller Order logistics fulfillment unit.</p></div></div>
<form class="log-filters"><input class="input flex-1" name="q" value="{{ request('q') }}" placeholder="Search Order or Load ID…"><select class="input" name="status"><option value="">All statuses</option>@foreach(\App\Models\Shipment::STATUSES as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><select class="input" name="shop_id"><option value="">All Shops</option>@foreach($shops as $shop)<option value="{{ $shop->id }}" @selected(request('shop_id')==$shop->id)>{{ $shop->name }}</option>@endforeach</select><select class="input" name="rider_id"><option value="">All Riders</option>@foreach($riders as $r)<option value="{{ $r->id }}" @selected(request('rider_id')==$r->id)>{{ $r->name }}</option>@endforeach</select><input class="input" type="date" name="date_from" value="{{ request('date_from') }}"><button class="btn-primary btn-sm">Apply</button><a href="{{ route('logistics.shipments.index') }}" class="text-xs text-slate-500">Clear</a></form>
<div class="log-card mt-4 overflow-x-auto"><table class="log-table min-w-[1250px]"><thead><tr><th>Load ID / Order</th><th>Shop</th><th>Pickup → Delivery</th><th>Ready / ETA</th><th>Status</th><th>Rider</th><th>Vehicle</th><th>Items</th><th>Payment</th><th>POD</th><th>Action</th></tr></thead><tbody>@forelse($shipments as $s)<tr><td><b class="text-brand-700">{{ $s->shipment_number }}</b><small class="block text-slate-400">Order {{ $s->order->order_number }}</small></td><td><b>{{ $s->store?->name }}</b></td><td class="max-w-[190px] truncate">{{ data_get($s->pickup_address,'address','Seller Shop') }} → @if($s->currentHub){{ $s->currentHub->name }} → @endif{{ data_get($s->delivery_address,'city','Buyer') }}</td><td>{{ $s->ready_at?->format('M d, H:i')??'—' }}<small class="block text-slate-400">ETA {{ $s->estimated_delivery_at?->format('M d, H:i')??'Not Available' }}</small></td><td><x-admin.status-badge :status="$s->status"/></td><td>{{ $s->rider?->name??'Unassigned' }}</td><td>{{ $s->vehicle?->code??'—' }}</td><td>{{ $s->sellerOrder->items->sum('quantity') }}</td><td>{{ strtoupper($s->order->payment_method) }}<small class="block text-slate-400">{{ ucfirst($s->order->payment_status) }}</small></td><td><x-admin.status-badge :status="($s->proofOfDelivery?->status==='pending'&&!$s->proofOfDelivery?->photo_path)?'pending_upload':($s->proofOfDelivery?->status??'pending_upload')"/></td><td><a class="log-action log-action-info" href="{{ request()->fullUrlWithQuery(['view'=>$s->id]) }}"><span class="log-icon">👁</span> View Load</a></td></tr>@empty<tr><td colspan="11" class="log-empty">No Orders / Loads match these filters.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $shipments->links() }}</div>
@if($selected)<aside class="log-drawer"><div class="log-drawer-head"><div><h2 class="font-extrabold">Load Details</h2><p class="text-xs text-slate-400">{{ $selected->shipment_number }} · Order {{ $selected->order->order_number }}</p></div><a href="{{ route('logistics.shipments.index',request()->except('view')) }}">×</a></div><div class="flex gap-4 border-b py-3 text-xs font-semibold"><button data-load-tab="overview" class="text-brand-600">Overview</button><button data-load-tab="items">Items</button><button data-load-tab="tracking">Tracking</button><button data-load-tab="documents">Documents</button><button data-load-tab="notes">Notes</button></div>
<section data-load-panel="overview"><div class="log-drawer-section"><div class="flex justify-between"><h3>{{ $selected->store?->name }}</h3><x-admin.status-badge :status="$selected->status"/></div><div class="log-drawer-grid"><div><span>Rider</span><b>{{ $selected->rider?->name??'Unassigned' }}</b></div><div><span>Vehicle</span><b>{{ $selected->vehicle?->code??'—' }}</b></div><div><span>Payment</span><b>{{ strtoupper($selected->order->payment_method) }} / {{ ucfirst($selected->order->payment_status) }}</b></div><div><span>POD</span><b>{{ ucwords(str_replace('_',' ',$selected->proofOfDelivery?->status??'pending_upload')) }}</b></div></div></div><div class="log-drawer-section"><h3>Route</h3><p class="text-xs"><b>Pickup:</b> {{ data_get($selected->pickup_address,'address','Seller Shop') }}</p>@if($selected->currentHub)<p class="mt-2 text-xs"><b>Hub:</b> {{ $selected->currentHub->name }}</p>@endif<p class="mt-2 text-xs"><b>Delivery:</b> {{ collect($selected->delivery_address)->filter()->implode(', ') }}</p><p class="mt-2 text-xs"><b>ETA:</b> {{ $selected->estimated_delivery_at?->format('M d, Y g:i A')??'Not Available' }}</p></div></section>
<section data-load-panel="items" class="hidden log-drawer-section"><h3>Order Items</h3>@foreach($selected->sellerOrder->items as $item)<div class="flex justify-between border-t py-3 text-xs"><span>{{ $item->product_name }} {{ $item->variant_label }}</span><b>{{ $item->quantity }} × ₱{{ number_format($item->price,2) }}</b></div>@endforeach</section>
<section data-load-panel="tracking" class="hidden log-drawer-section"><h3>Tracking History</h3>@forelse($selected->events->sortByDesc('created_at') as $event)<div class="border-t py-3 text-xs"><b>{{ ucwords(str_replace('_',' ',$event->status)) }}</b><p>{{ $event->note }}</p><p class="text-slate-400">{{ $event->actor?->name??'System' }} · {{ $event->created_at->format('M d, g:i A') }}</p></div>@empty<p class="text-xs text-slate-400">No tracking events.</p>@endforelse</section>
<section data-load-panel="documents" class="hidden log-drawer-section"><h3>Documents</h3>@if($selected->proofOfDelivery?->photo_path)<a href="{{ route('logistics.pod.file',$selected->proofOfDelivery) }}" class="text-xs font-bold text-brand-600">Open private POD evidence</a>@else<p class="text-xs text-slate-400">POD evidence is pending upload.</p>@endif</section>
<section data-load-panel="notes" class="hidden log-drawer-section"><h3>Internal Notes</h3><p class="text-xs text-slate-600">{{ $selected->internal_notes?:'No internal notes.' }}</p></section></aside>@endif
@endsection
@push('scripts')<script>document.querySelectorAll('[data-load-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-load-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.loadPanel!==button.dataset.loadTab));document.querySelectorAll('[data-load-tab]').forEach(b=>b.classList.toggle('text-brand-600',b===button));}));</script>@endpush
