@extends('layouts.logistics')
@section('title','Load Details')
@section('content')
<a href="{{ route('logistics.shipments.index') }}" class="text-sm text-brand-600">← Orders / Loads</a>
<div class="mt-3 flex justify-between"><div><h1 class="text-2xl font-black">{{ $shipment->shipment_number }}</h1><p class="text-sm text-slate-500">{{ $shipment->order->order_number }} · {{ $shipment->sellerOrder->seller_order_number }}</p></div><x-admin.status-badge :status="$shipment->status"/></div>
<div class="mt-5 grid gap-3 lg:grid-cols-2">
<form method="POST" action="{{ route('logistics.shipments.status',$shipment) }}" class="card grid gap-2 p-4 sm:grid-cols-3">@csrf<select class="input" name="status">@foreach(['pickup_scheduled','picked_up','at_hub','in_transit','exception'] as $status)<option value="{{ $status }}">{{ ucwords(str_replace('_',' ',$status)) }}</option>@endforeach</select><input class="input" name="note" placeholder="Operational note"><button class="btn-primary">Update Stage</button></form>
<form method="POST" action="{{ route('logistics.shipments.hub',$shipment) }}" class="card grid gap-2 p-4 sm:grid-cols-3">@csrf<select class="input" name="hub_id" required><option value="">Select Hub</option>@foreach($hubs as $hub)<option value="{{ $hub->id }}">{{ $hub->name }}</option>@endforeach</select><select class="input" name="type"><option value="inbound">Inbound</option><option value="transfer">Transfer</option><option value="outbound">Outbound</option></select><button class="btn-outline">Record Hub</button></form>
</div>
<div class="mt-6 grid gap-6 lg:grid-cols-3"><section class="card p-5 lg:col-span-2"><h2 class="font-bold">Overview</h2><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-slate-400">Shop / Seller</dt><dd>{{ $shipment->store?->name }} · {{ $shipment->store?->user?->name }}</dd></div><div><dt class="text-slate-400">Buyer</dt><dd>{{ $shipment->order->buyer_name }}</dd></div><div><dt class="text-slate-400">Rider</dt><dd>{{ $shipment->rider?->name??'Unassigned' }}</dd></div><div><dt class="text-slate-400">Vehicle</dt><dd>{{ $shipment->vehicle?->code??'Unassigned' }}</dd></div><div><dt class="text-slate-400">Pickup</dt><dd>{{ data_get($shipment->pickup_address,'address','Not provided') }}</dd></div><div><dt class="text-slate-400">Delivery</dt><dd>{{ collect($shipment->delivery_address)->filter()->implode(', ') }}</dd></div></dl><h3 class="mt-6 font-bold">Items</h3>@foreach($shipment->sellerOrder->items as $item)<div class="flex justify-between border-t py-3 text-sm"><span>{{ $item->product_name }} {{ $item->variant_label }}</span><b>{{ $item->quantity }} × ₱{{ number_format($item->price,2) }}</b></div>@endforeach</section><aside class="card p-5"><h2 class="font-bold">Tracking</h2>@forelse($shipment->events->sortByDesc('created_at') as $event)<div class="border-t py-3 text-sm"><b>{{ ucwords(str_replace('_',' ',$event->status)) }}</b><p>{{ $event->note }}</p><p class="text-xs text-slate-400">{{ $event->actor?->name??'System' }} · {{ $event->created_at->format('M d, g:i A') }}</p></div>@empty<p class="mt-4 text-sm text-slate-500">No tracking events.</p>@endforelse</aside></div>
@endsection
