@extends('layouts.logistics')
@section('title','Sorting')
@section('content')
<div class="log-page-head"><div><h1>Parcel Sorting</h1><p>Group received parcels into configurable Delivery Areas.</p></div></div>
<details class="log-card mt-4 p-5"><summary class="cursor-pointer font-semibold">Add Delivery Area</summary><form method="POST" action="{{ route('logistics.areas.store') }}" class="mt-4 grid gap-3 md:grid-cols-5">@csrf<input class="input" name="code" placeholder="Code" required><input class="input" name="name" placeholder="Area name" required><input class="input" name="province" placeholder="Province" required><input class="input" name="municipality" placeholder="Municipality / City"><input class="input" name="barangays" placeholder="Barangays, comma-separated"><button class="btn-primary">Save Area</button></form></details>
<div class="log-card mt-4 overflow-x-auto"><table class="log-table min-w-[800px]"><thead><tr><th>Parcel</th><th>Buyer Address</th><th>Scan</th><th>Delivery Area</th></tr></thead><tbody>
@forelse($shipments as $shipment)@php($detected=$detectedAreas[$shipment->id]??null)<tr><td><b>{{ $shipment->parcel_code ?: $shipment->shipment_number }}</b><small>{{ $shipment->store?->name }}</small></td><td>{{ collect($shipment->delivery_address)->filter()->implode(', ') }}<small>Detected area: {{ $detected?->name ?: 'No matching coverage rule' }}</small></td><td>{{ $shipment->parcel_scanned_at ? 'Code confirmed '.$shipment->parcel_scanned_at->format('M d, g:i A') : 'Confirm code first' }}</td><td>@if($shipment->status==='sorted')<b>{{ $shipment->deliveryArea?->name }}</b>@elseif($shipment->parcel_scanned_at)<form method="POST" action="{{ route('logistics.sorting.update',$shipment) }}" class="flex gap-2">@csrf<select class="input" name="delivery_area_id" required><option value="">Choose Area</option>@foreach($areas->where('is_active',true) as $area)<option value="{{ $area->id }}" @selected($detected?->id===$area->id)>{{ $area->name }}</option>@endforeach</select><button class="btn-primary">Confirm Sorting</button></form>@else<span class="text-slate-400">Pending parcel confirmation</span>@endif</td></tr>@empty<tr><td colspan="4" class="text-center">No parcels awaiting sorting.</td></tr>@endforelse
</tbody></table></div>{{ $shipments->links() }}
@endsection
