@extends('layouts.logistics')
@section('title','Delivery Monitoring')
@section('content')
@php
    $stages=['ready_for_pickup','pickup_assigned','pickup_accepted','picked_up','at_sorting_center','sorted','assigned_to_rider','out_for_delivery','delivered','completed'];
@endphp
<div class="log-page-head"><div><h1>Delivery Monitoring</h1><p>Status-based parcel monitoring from Seller pickup through Buyer confirmation.</p></div></div>
<form method="GET" class="log-card mt-5 grid gap-3 p-4 md:grid-cols-[1fr_220px_auto]"><input class="input" name="q" value="{{ request('q') }}" placeholder="Search Parcel, Order, or Shop"><select class="input" name="status"><option value="">All statuses</option>@foreach(\App\Models\Shipment::STATUSES as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="btn-primary">Filter</button></form>
<div class="mt-5 overflow-x-auto rounded-xl border bg-white"><table class="w-full min-w-[1050px] text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-4">Parcel / Order</th><th>Shop</th><th>Area</th><th>Pickup Rider</th><th>Delivery Rider</th><th>Current Status</th><th>Last Update</th><th>Action</th></tr></thead><tbody class="divide-y">@forelse($shipments as $shipment)<tr><td class="p-4"><b>{{ $shipment->parcel_code ?: $shipment->shipment_number }}</b><p class="text-xs text-slate-400">{{ $shipment->order?->order_number }}</p></td><td>{{ $shipment->store?->name??'—' }}</td><td>{{ $shipment->deliveryArea?->name??'Awaiting sorting' }}</td><td>{{ $shipment->pickupRider?->name??'Unassigned' }}</td><td>{{ $shipment->rider?->name??'Unassigned' }}</td><td><x-admin.status-badge :status="$shipment->status"/></td><td>{{ $shipment->events->sortByDesc('created_at')->first()?->created_at?->format('M d, Y · g:i A')??$shipment->updated_at->format('M d, Y · g:i A') }}</td><td><a class="font-semibold text-brand-600" href="{{ route('logistics.tracking',['shipment'=>$shipment->id]+request()->only(['q','status'])) }}">View Progress</a></td></tr>@empty<tr><td colspan="8" class="log-empty">No Parcels match these filters.</td></tr>@endforelse</tbody></table></div>
<div class="mt-4">{{ $shipments->links() }}</div>
@if($selected)
@php
 $eventStatuses=$selected->events->pluck('status')->unique();
 $isDemo=str_starts_with($selected->shipment_number,'DEMO-')||str_contains((string)$selected->internal_notes,'DEMO ONLY');
 $facility=match($selected->status){'ready_for_pickup','pickup_assigned','pickup_accepted'=>'Seller / Shop','picked_up'=>'With Pickup Rider','at_sorting_center','sorted','assigned_to_rider'=>'SHOPPICK Sorting Center','out_for_delivery'=>'With Delivery Rider','delivered'=>'Delivered to Buyer','completed'=>'Buyer Received','delivery_failed'=>'With Delivery Rider — Delivery Failed','returned'=>'Returning to Seller',default=>'Operational status recorded'};
 $nextAction=match($selected->status){'ready_for_pickup'=>'Assign Pickup Rider','pickup_assigned'=>'Pickup Rider accepts assignment','pickup_accepted'=>'Pickup Rider confirms collection','picked_up'=>'Receive at Sorting Center','at_sorting_center'=>$selected->parcel_scanned_at?'Confirm Delivery Area and Sorting':'Confirm Parcel Code','sorted'=>'Assign Delivery Rider','assigned_to_rider'=>'Delivery Rider accepts and collects Parcel','out_for_delivery'=>'Deliver Parcel to Buyer','delivered'=>'Buyer confirms receipt','delivery_failed'=>'Reschedule or Return Parcel',default=>null};
@endphp
<section class="log-card mt-5 p-5">
 <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wide text-brand-600">Delivery Summary</p><div class="mt-1 flex items-center gap-2"><h2 class="text-xl font-black">{{ $selected->parcel_code ?: $selected->shipment_number }}</h2>@if($isDemo)<span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-500">Demo Data</span>@endif</div><p class="text-sm text-slate-500">{{ $selected->order?->order_number }} · {{ $selected->store?->name }}</p></div><a class="btn-outline btn-sm" href="{{ route('logistics.shipments.show',$selected) }}">View Parcel</a></div>
 <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
  <div><p class="text-xs text-slate-400">Pickup Rider</p><b>{{ $selected->pickupRider?->name??'Unassigned' }}</b></div><div><p class="text-xs text-slate-400">Pickup Vehicle</p><b>{{ $selected->pickupRider?->riderProfile?->vehicle_type??'—' }}@if($selected->pickupRider?->riderProfile?->plate_number) · {{ $selected->pickupRider->riderProfile->plate_number }}@endif</b></div>
  <div><p class="text-xs text-slate-400">Delivery Rider</p><b>{{ $selected->rider?->name??'Unassigned' }}</b></div><div><p class="text-xs text-slate-400">Delivery Vehicle</p><b>{{ $selected->rider?->riderProfile?->vehicle_type??'—' }}@if($selected->rider?->riderProfile?->plate_number) · {{ $selected->rider->riderProfile->plate_number }}@endif</b></div>
  <div><p class="text-xs text-slate-400">Current Stage</p><x-admin.status-badge :status="$selected->status"/></div><div><p class="text-xs text-slate-400">Current Facility</p><b>{{ $facility }}</b></div><div><p class="text-xs text-slate-400">Delivery Area</p><b>{{ $selected->deliveryArea?->name??'Awaiting sorting' }}</b></div><div><p class="text-xs text-slate-400">Next Action</p><b>{{ $nextAction??'No further action' }}</b>@if($selected->status==='sorted')<a class="mt-2 block text-sm font-semibold text-brand-600" href="{{ route('logistics.delivery-assignment') }}">Assign Rider →</a>@endif</div>
 </div>
 <div class="mt-7"><h3 class="font-bold">Delivery Progress</h3><p class="mt-1 text-xs text-slate-500">A stage is completed only when its event exists in parcel history.</p><div class="mt-3 flex flex-wrap gap-2">@foreach($stages as $stage)@php($recorded=$eventStatuses->contains($stage))@php($current=$selected->status===$stage)<span class="rounded-full border px-3 py-2 text-xs font-semibold {{ $current?'border-brand-600 bg-brand-600 text-white shadow-sm':($recorded?'border-brand-300 bg-brand-50 text-brand-700':'border-slate-200 bg-white text-slate-400') }}">{{ $current?'●':($recorded?'✓':'○') }} {{ str($stage)->headline() }}@if($current) · Current @endif</span>@endforeach</div></div>
 <div class="mt-7"><h3 class="font-bold">Progress Timeline</h3><div class="mt-3 border-l-2 border-brand-100 pl-5">@forelse($selected->events->sortByDesc('created_at') as $event)@php($note=trim(preg_replace('/^DEMO ONLY\s*[—-]\s*/u','',(string)$event->note)))@php($description=$note?:match($event->status){'ready_for_pickup'=>($selected->store?->name??'Seller').' completed Parcel preparation.','pickup_assigned'=>($selected->pickupRider?->name??'Pickup Rider').' assigned for Seller pickup.','pickup_accepted'=>($selected->pickupRider?->name??'Pickup Rider').' accepted the pickup assignment.','picked_up'=>'Parcel collected from Seller by '.($selected->pickupRider?->name??'Pickup Rider').'.','pickup_arrived'=>'Pickup Rider arrived at SHOPPICK Sorting Center.','at_sorting_center'=>'Parcel received at SHOPPICK Sorting Center.','parcel_confirmed'=>'Parcel code confirmed at SHOPPICK Sorting Center.','sorted'=>'Assigned to '.($selected->deliveryArea?->name??'the selected Delivery Area').'.','assigned_to_rider'=>($selected->rider?->name??'Delivery Rider').' assigned for '.($selected->deliveryArea?->name??'the Delivery Area').'.','delivery_accepted'=>($selected->rider?->name??'Delivery Rider').' accepted the delivery assignment.','out_for_delivery'=>($selected->rider?->name??'Delivery Rider').' collected the Parcel from SHOPPICK Sorting Center.','delivered'=>($selected->rider?->name??'Delivery Rider').' confirmed successful Parcel delivery.','completed'=>'Buyer confirmed receipt of the Parcel.','delivery_failed'=>($selected->rider?->name??'Delivery Rider').' reported: '.($selected->failure_reason??'Delivery failed').'.','returned'=>'Parcel marked for return to '.($selected->store?->name??'the Seller').'.',default=>str($event->status)->headline().' recorded.'})<div class="relative pb-5"><span class="absolute -left-[27px] top-1 h-3 w-3 rounded-full {{ in_array($event->status,['delivery_failed','returned'])?'bg-rose-500':'bg-brand-500' }}"></span><b class="text-sm">{{ str($event->status)->headline() }}</b>@if($event->location)<p class="text-sm font-medium text-slate-600">Destination Area: {{ $event->location }}</p>@endif<p class="text-sm text-slate-500">{{ $description }}</p><p class="text-xs text-slate-400">Performed by: {{ $event->actor?->name??'System' }}<br>{{ $event->created_at->format('M d, Y · g:i A') }}</p></div>@empty<p class="text-sm text-slate-500">No parcel events recorded.</p>@endforelse</div></div>
 @if($selected->status==='delivery_failed')<div class="mt-4 rounded-lg border border-rose-200 bg-rose-50 p-4"><b class="text-rose-700">Delivery Exception</b><p class="text-sm text-rose-600">{{ $selected->failure_reason }}</p><div class="mt-3 flex flex-wrap gap-3"><form method="POST" action="{{ route('logistics.delivery.reschedule',$selected) }}">@csrf<button class="btn-primary btn-sm">Reschedule</button></form><form method="POST" action="{{ route('logistics.delivery.return',$selected) }}" class="flex gap-2">@csrf<input class="input" name="reason" required placeholder="Return reason"><button class="btn-outline btn-sm">Return Parcel</button></form></div></div>@elseif($selected->status==='returned')<div class="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-4"><b class="text-amber-800">Parcel Returned</b><p class="text-sm text-amber-700">{{ $selected->failure_reason ?: 'Parcel is being returned to the Seller.' }}</p></div>@endif
</section>
@endif
@endsection
