<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\AdminActivityLog; use App\Models\ModerationScan; use App\Models\Store; use App\Models\Violation; use App\Services\NotificationService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class ModerationController extends Controller {
 public function index(Request $r){
  $search=trim((string)$r->input('q'));
  $query=ModerationScan::with(['product','image','seller','store.user','store.sellerProfile'])
   ->whereHas('store',fn($store)=>$store->marketplaceActive())
   ->when($r->status,fn($q,$status)=>$q->where('status',$status))
   ->when($r->filled('shop'),fn($q)=>$q->where('store_id',$r->integer('shop')))
   ->when($search!=='',fn($q)=>$q->where(function($match)use($search){$match->whereHas('product',fn($product)=>$product->where('name','like',"%{$search}%"))->orWhereHas('store',fn($store)=>$store->where('name','like',"%{$search}%"))->orWhereHas('seller',fn($seller)=>$seller->where('name','like',"%{$search}%"));}));
  $scans=$query->latest()->paginate(20)->withQueryString();
  $groupedScans=$scans->getCollection()->groupBy(fn($scan)=>(string)($scan->store_id??'unassigned'));
  $storeIds=$groupedScans->keys()->filter(fn($id)=>is_numeric($id))->values();
  $summaries=$storeIds->isEmpty()?collect():ModerationScan::whereIn('store_id',$storeIds)->selectRaw("store_id, COUNT(DISTINCT product_id) as product_count, SUM(CASE WHEN status = 'pending_scan' THEN 1 ELSE 0 END) as pending_count, SUM(CASE WHEN status = 'flagged' THEN 1 ELSE 0 END) as flagged_count, SUM(CASE WHEN status = 'approved' THEN 1 ELSE 0 END) as approved_count, SUM(CASE WHEN status = 'rejected' THEN 1 ELSE 0 END) as rejected_count")->groupBy('store_id')->get()->keyBy('store_id');
  $shopOptions=Store::marketplaceActive()->whereHas('products.moderationScans')->orderBy('name')->get(['id','name']);
  return view('admin.moderation.index',compact('scans','groupedScans','summaries','shopOptions'));
 }
 public function show(ModerationScan $scan){$scan->load(['product.images','image','seller.violations','store.violations','reviewer']);return view('admin.moderation.show',compact('scan'));} public function review(Request $r,ModerationScan $scan){$data=$r->validate(['decision'=>['required','in:approved,rejected,false_positive,escalated'],'notes'=>['required','string','max:1500']]);DB::transaction(function()use($r,$scan,$data){$scan->loadMissing(['store.user','store.sellerProfile']);$scan->update(['status'=>$data['decision']==='escalated'?'under_review':$data['decision'],'decision'=>$data['decision'],'review_notes'=>$data['notes'],'reviewed_by'=>$r->user()->id,'reviewed_at'=>now()]);if(in_array($data['decision'],['approved','false_positive'])){$blocked=$scan->product->moderationScans()->whereKeyNot($scan->id)->whereIn('status',['pending_scan','scanning','flagged','under_review','scan_failed'])->exists();$scan->product->update(['moderation_status'=>$blocked?'pending_scan':'approved','is_active'=>!$blocked&&$scan->store?->isMarketplaceActive()&&$scan->product->publication_status==='published']);}elseif($data['decision']==='rejected'){$scan->product->update(['moderation_status'=>'rejected','is_active'=>false,'suspension_reason'=>$data['notes']]);Violation::create(['seller_id'=>$scan->seller_id,'store_id'=>$scan->store_id,'product_id'=>$scan->product_id,'moderation_scan_id'=>$scan->id,'recorded_by'=>$r->user()->id,'category'=>$scan->detected_category??'other','severity'=>$scan->risk_level,'description'=>$data['notes'],'action_taken'=>'product_rejected']);}if($scan->seller_id)NotificationService::send($scan->seller_id,$data['decision']==='rejected'?'Product not approved':($scan->product->fresh()->is_active?'Your product is now live on SHOPPICK':'Product moderation updated'),$data['notes'],'moderation',route('seller.products.index'));AdminActivityLog::record('moderation.'.$data['decision'],'moderation_scan',$scan->id,['notes'=>$data['notes']]);});return back()->with('success','Moderation decision saved.');} }
