<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\AdminActivityLog; use App\Models\Report; use App\Models\Role; use App\Models\Product; use App\Models\Store; use App\Services\NotificationService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class ReportManagementController extends Controller {
 public function index(Request $r){$q=Report::with(['reporter','assignee','target']);foreach(['status','reason','source','priority','target_type'] as $f)if($r->filled($f))$q->where($f,$r->$f);if($r->q)$q->where(fn($x)=>$x->where('report_number','like','%'.$r->q.'%')->orWhere('description','like','%'.$r->q.'%'));$reports=$q->latest()->paginate(20)->withQueryString();return view('admin.case-reports.index',compact('reports'));}
 public function show(Report $report){$report->load(['reporter','assignee','target','evidence','notes.user','actions.user']);$violations=\App\Models\Violation::where(fn($q)=>$q->when($report->target instanceof Product,fn($x)=>$x->where('product_id',$report->target_id))->when($report->target instanceof Store,fn($x)=>$x->where('store_id',$report->target_id)))->latest()->get();$admins=Role::where('slug','admin')->with('users')->first()?->users??collect();return view('admin.case-reports.show',compact('report','violations','admins'));}
 public function update(Request $r,Report $report){$data=$r->validate(['status'=>['required','in:open,under_review,resolved,dismissed,escalated'],'assigned_to'=>['nullable','exists:users,id'],'note'=>['nullable','string','max:2000']]);DB::transaction(function()use($r,$report,$data){$report->update(['status'=>$data['status'],'assigned_to'=>$data['assigned_to']??$report->assigned_to,'resolved_at'=>in_array($data['status'],['resolved','dismissed'])?now():null]);if($data['note']??null)$report->notes()->create(['user_id'=>$r->user()->id,'note'=>$data['note'],'is_super_admin'=>$r->user()->isSuperAdmin()]);$report->actions()->create(['user_id'=>$r->user()->id,'action'=>'status_'.$data['status'],'reason'=>$data['note']??null]);AdminActivityLog::record('report.'.$data['status'],'report',$report->id,['reason'=>$data['note']??null]);});return back()->with('success','Report updated.');}
 public function enforce(Request $r,Report $report){abort_unless($r->user()->isSuperAdmin(),403);$data=$r->validate(['action'=>['required','in:warn_seller,hide_product,suspend_product,restore_product,suspend_shop,restrict_shop,reactivate_shop'],'reason'=>['required','string','max:1000']]);$target=$report->target;DB::transaction(function()use($data,$report,$target,$r){$seller=null;$store=null;$product=null;if($target instanceof Product){$product=$target;$store=$product->store;$seller=$store?->user;}if($target instanceof Store){$store=$target;$seller=$store->user;}if(in_array($data['action'],['hide_product','suspend_product'])&&$product)$product->update(['is_active'=>false,'moderation_status'=>'rejected','suspension_reason'=>$data['reason']]);if($data['action']==='restore_product'&&$product)$product->update(['is_active'=>true,'moderation_status'=>'approved','suspension_reason'=>null]);if(in_array($data['action'],['suspend_shop','restrict_shop'])&&$store)$store->update(['status'=>$data['action']==='suspend_shop'?'suspended':'restricted','status_reason'=>$data['reason']]);if($data['action']==='reactivate_shop'&&$store)$store->update(['status'=>'active','status_reason'=>null]);if($seller)NotificationService::send($seller->id,'Marketplace policy update',$data['reason'],'moderation',route('seller.notifications.index'));if($data['action']!=='warn_seller')\App\Models\Violation::create(['seller_id'=>$seller?->id,'store_id'=>$store?->id,'product_id'=>$product?->id,'report_id'=>$report->id,'recorded_by'=>$r->user()->id,'category'=>$report->reason,'severity'=>$report->priority,'description'=>$data['reason'],'action_taken'=>$data['action']]);$report->actions()->create(['user_id'=>$r->user()->id,'action'=>$data['action'],'reason'=>$data['reason']]);AdminActivityLog::record('moderation.'.$data['action'],get_class($target),$target->id,['reason'=>$data['reason']]);});return back()->with('success','Moderation action completed.');}
}
